// FR lang variables
// Modified by Motte, last updated 2006-03-23

tinyMCE.addToLang('advlink',{
target_same : 'Ouvre dans la m&ecirc;me fen&ecirc;tre / Cadre',
target_parent : 'Ouvre dans la fen&ecirc;tre / cadre parente',
target_top : 'Ouvre dans le Top frame (remplace toutes les cadres)',
target_blank : 'Ouvre dans une nouvelle fen&ecirc;tre',
target_name : 'Nom de la cible',
popup : 'JS-Popup',
popup_url : 'URL de la Popup',
popup_name : 'Nom de la fen&ecirc;tre',
popup_return : 'Insert \'return false\'',
popup_scrollbars : 'Montrer la barre de d&eacute;filement ',
popup_statusbar : 'Montrer la barre d\'&eacute;tat',
popup_toolbar : 'Montrer la barre d\'outils',
popup_menubar : 'Montrer la barre du menu',
popup_location : 'Montre la barre d\'adresse',
popup_resizable : 'Fabriquer une fen&ecirc;tre redimensionnable',
popup_dependent : 'Dependent (Mozilla/Firefox only)',
popup_size : 'Taille',
popup_position : 'Position (X/Y)',
popup_missingtarget : 'Veuillez ins&eacute;rer un nom pour la cible ou choisissez une autre option.',
general_tab : 'G&eacute;n&eacute;ral',
popup_tab : 'Popup',
events_tab : 'Ev&ecirc;nements',
advanced_tab : 'Avanc&eacute;',
general_props : 'Propri&eacute;t&eacute;s g&eacute;n&eacute;rales',
popup_props : 'Propri&eacute;t&eacute;s Popup',
event_props : 'Ev&ecirc;nements',
advanced_props : 'Propri&eacute;t&eacute;s Avanc&eacute;es',
popup_opts : 'Options',
anchor_names : 'Ancres',
id : 'Id',
style: 'Style',
classes : 'Classes',
langdir : 'Sens d\'&eacute;criture',
target_langcode : 'Langage cible',
langcode : 'Code langue',
encoding : 'Codage caract&egrave;res de la cible',
mime : 'Type MIME de la cible',
rel : 'Page relative &agrave; la cible',
rev : 'Cible relative &agrave; la page',
tabindex : 'Tabindex',
accesskey : 'Touche d\'acc&egrave;s',
ltr : 'De gauche &agrave; droite',
rtl : 'De droite &agrave; gauche'
});
