tinyMCE.addI18n('fi.xhtmlxtras_dlg',{
attribute_label_title:"Otsikko",
attribute_label_id:"ID",
attribute_label_class:"Luokka",
attribute_label_style:"Tyyli",
attribute_label_cite:"Sitaatti",
attribute_label_datetime:"P\u00E4iv\u00E4/Aika",
attribute_label_langdir:"Tekstin suunta",
attribute_option_ltr:"Vasemmalta oikealle",
attribute_option_rtl:"Oikealta vasemmalle",
attribute_label_langcode:"Kieli",
attribute_label_tabindex:"TabIndex",
attribute_label_accesskey:"AccessKey",
attribute_events_tab:"Tapahtumat",
attribute_attrib_tab:"Attribuutit",
general_tab:"Yleiset",
attrib_tab:"Attribuutit",
events_tab:"Tapahtumat",
fieldset_general_tab:"Yleiset asetukset",
fieldset_attrib_tab:"Elementin attribuutit",
fieldset_events_tab:"Elementin tapahtumat",
title_ins_element:"Lis\u00E4ys elementit",
title_del_element:"Poisto elementit",
title_acronym_element:"Kirjainlyhenne elementit",
title_abbr_element:"Lyhenne elementit",
title_cite_element:"Sitaatti elementit",
remove:"Poista",
insert_date:"Lis\u00E4\u00E4 t\u00E4m\u00E4nhetkinen p\u00E4iv\u00E4/aika",
option_ltr:"Vasemmalta oikealle",
option_rtl:"Oikealta vasemmalle",
attribs_title:"Lis\u00E4\u00E4/muokkaa attribuutteja"
});