tinyMCE.addI18n('lv.xhtmlxtras_dlg',{
attribute_label_title:"Nosaukums",
attribute_label_id:"ID",
attribute_label_class:"Klase",
attribute_label_style:"Stils",
attribute_label_cite:"Cite",
attribute_label_datetime:"Datums/Laiks",
attribute_label_langdir:"Teksta v\u012Brziens",
attribute_option_ltr:"No kreisas puses uz labo",
attribute_option_rtl:"No labas puses uz kreiso",
attribute_label_langcode:"Valoda",
attribute_label_tabindex:"TabIndex",
attribute_label_accesskey:"Pieejas poga",
attribute_events_tab:"Notikumi",
attribute_attrib_tab:"\u012Apa\u0161\u012Bbas",
general_tab:"General",
attrib_tab:"Attributes",
events_tab:"Events",
fieldset_general_tab:"General Settings",
fieldset_attrib_tab:"Element Attributes",
fieldset_events_tab:"Element Events",
title_ins_element:"Insertion Element",
title_del_element:"Deletion Element",
title_acronym_element:"Acronym Element",
title_abbr_element:"Abbreviation Element",
title_cite_element:"Citation Element",
remove:"Remove",
insert_date:"Insert current date/time",
option_ltr:"Left to right",
option_rtl:"Right to left",
attribs_title:"Insert/Edit Attributes"
});