tinyMCE.addI18n('ms.xhtmlxtras_dlg',{
attribute_label_title:"Tajuk",
attribute_label_id:"ID",
attribute_label_class:"Kelas",
attribute_label_style:"Gaya",
attribute_label_cite:"Cuplik",
attribute_label_datetime:"Tarikh/Masa",
attribute_label_langdir:"Arah Teks",
attribute_option_ltr:"Kiri ke kanan",
attribute_option_rtl:"Kanan ke kiri",
attribute_label_langcode:"Bahasa",
attribute_label_tabindex:"Tanda indeks",
attribute_label_accesskey:"Kunci akses",
attribute_events_tab:"Peristiwa",
attribute_attrib_tab:"Ciri-ciri",
general_tab:"Am",
attrib_tab:"Ciri-ciri",
events_tab:"Peristiwa",
fieldset_general_tab:"Susunan Am",
fieldset_attrib_tab:"Unsur Ciri-ciri",
fieldset_events_tab:"Unsur Peristiwa",
title_ins_element:"Kemasukkan Unsur",
title_del_element:"Pemadaman Unsur",
title_acronym_element:"Akronim Unsur",
title_abbr_element:"Singkatan Unsur",
title_cite_element:"Kutipan Unsur",
remove:"Alih",
insert_date:"Masukkan tarikh/masa sekarang",
option_ltr:"Kiri ke kanan",
option_rtl:"Kanan ke kiri",
attribs_title:"Masukkan/Sunting Ciri-ciri"
});