tinyMCE.addI18n('pl.xhtmlxtras_dlg',{
attribute_label_title:"Tytu\u0142",
attribute_label_id:"ID",
attribute_label_class:"Klasa",
attribute_label_style:"Styl",
attribute_label_cite:"Cytat",
attribute_label_datetime:"Data/Czas",
attribute_label_langdir:"Kierunek czytania tekstu",
attribute_option_ltr:"Kierunek z lewej do prawej",
attribute_option_rtl:"Kierunek z prawej do lewej",
attribute_label_langcode:"J\u0119zyk",
attribute_label_tabindex:"TabIndex",
attribute_label_accesskey:"AccessKey",
attribute_events_tab:"Wydarzenia",
attribute_attrib_tab:"Atrybuty",
general_tab:"G\u0142wny",
attrib_tab:"Atrybuty",
events_tab:"Wydarzenia",
fieldset_general_tab:"G\u0142\u00F3wne ustawienia",
fieldset_attrib_tab:"Atrybuty",
fieldset_events_tab:"Zdarzenia",
title_ins_element:"Insertion Element",
title_del_element:"Deletion Element",
title_acronym_element:"Akronim Element",
title_abbr_element:"Abbreviation Element",
title_cite_element:"Cytat",
remove:"Usu\u0144",
insert_date:"Wklej aktualn\u0105 dat\u0119/czas",
option_ltr:"Kierunek z lewej do prawej",
option_rtl:"Kierunek z prawej do lewej",
attribs_title:"Wklej/edytuj atrybuty"
});