tinyMCE.addI18n('tr.xhtmlxtras_dlg',{
attribute_label_title:"Ba\u015F",
attribute_label_id:"ID",
attribute_label_class:"S\u0131",
attribute_label_style:"Stil",
attribute_label_cite:"Belirt",
attribute_label_datetime:"Tarih/Zaman",
attribute_label_langdir:"Metin y\u00F6neli",
attribute_option_ltr:"Soldan sa",
attribute_option_rtl:"Sa\u011Fdan so",
attribute_label_langcode:"Dil",
attribute_label_tabindex:"Sekme \u0130ndek",
attribute_label_accesskey:"Eri\u015Fim Anahta",
attribute_events_tab:"Olaylar",
attribute_attrib_tab:"Nitelikler",
general_tab:"Genel",
attrib_tab:"Nitelikler",
events_tab:"Olaylar",
fieldset_general_tab:"Genel Ayarlar",
fieldset_attrib_tab:"Eleman Nitelikleri",
fieldset_events_tab:"Eleman Olaylar",
title_ins_element:"Ekleme Eleman",
title_del_element:"Silme Eleman ",
title_acronym_element:"K\u0131saltma Elema",
title_abbr_element:"K\u0131saad Elema",
title_cite_element:"Belirtme Eleman",
remove:"Kald",
insert_date:"\u015Eimdiki tarih/zaman\u0131 ",
option_ltr:"Soldan sa",
option_rtl:"Sa\u011Fdan so",
attribs_title:"Nitelik ekle/d\u00FCzen"
});