version: 2

updates:
  # Keep Github Actions dependencies up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"


  # 10.0/bugfixes branch
  # -> no update for production dependencies (old policy applied until now)
  # -> patch (bugfixes) updates for development dependencies (plugins may use the GLPI toolchain, we want them to be stable)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 1 * *"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    rebase-strategy: "disabled"
    target-branch: "10.0/bugfixes"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "development"
    ignore:
      # ignore minor/major versions for all dependencies
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 1 * *"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    rebase-strategy: "disabled"
    target-branch: "10.0/bugfixes"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "development"
    ignore:
      # ignore minor/major versions for all dependencies
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
    groups:
      dev-dependencies:
        patterns:
          - "*"


  # 11.0/bugfixes branch
  # -> patch (bugfixes) updates for both production and developement dependencies (new policy applied since GLPI 11.0)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 11 1 * *"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    rebase-strategy: "disabled"
    target-branch: "11.0/bugfixes"
    versioning-strategy: "increase"
    ignore:
      # ignore minor/major versions for all dependencies
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
    groups:
      # dev-dependencies group first, to be sure that they will not be included in the following groups
      dev-dependencies:
        dependency-type: "development"
      cytoscape:
        patterns:
          - "cytoscape"
          - "cytoscape-*"
      leaflet:
        patterns:
          - "leaflet"
          - "leaflet-*"
          - "leaflet.*"
      fullcalendar:
        patterns:
          - "@fullcalendar/*"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 11 1 * *"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    rebase-strategy: "disabled"
    target-branch: "11.0/bugfixes"
    versioning-strategy: "increase"
    ignore:
      # ignore minor/major versions for all dependencies
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
    groups:
      # dev-dependencies group first, to be sure that they will not be included in the following groups
      dev-dependencies:
        dependency-type: "development"
      guzzlehttp:
        patterns:
          - "guzzlehttp/*"
      sabre:
        patterns:
          - "sabre/*"
      symfony:
        patterns:
          - "symfony/*"
        exclude-patterns:
          - "symfony/polyfill-*"
      symfony-polyfills:
        patterns:
          - "symfony/polyfill-*"
      twig:
        patterns:
          - "twig/*"


  # main branch (next version is a minor version, i.e. 11.x)
  # -> minor updates for both production and developement dependencies (prevent BC breaks)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 13 1 * *"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    rebase-strategy: "disabled"
    target-branch: "main"
    versioning-strategy: "increase"
    ignore:
      # ignore major versions for all dependencies
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      # dev-dependencies group first, to be sure that they will not be included in the following groups
      dev-dependencies:
        dependency-type: "development"
      cytoscape:
        patterns:
          - "cytoscape"
          - "cytoscape-*"
      leaflet:
        patterns:
          - "leaflet"
          - "leaflet-*"
          - "leaflet.*"
      fullcalendar:
        patterns:
          - "@fullcalendar/*"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 13 1 * *"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    rebase-strategy: "disabled"
    target-branch: "main"
    versioning-strategy: "increase"
    ignore:
      # ignore major versions for all dependencies
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      # dev-dependencies group first, to be sure that they will not be included in the following groups
      dev-dependencies:
        dependency-type: "development"
      guzzlehttp:
        patterns:
          - "guzzlehttp/*"
      sabre:
        patterns:
          - "sabre/*"
      symfony:
        patterns:
          - "symfony/*"
        exclude-patterns:
          - "symfony/polyfill-*"
      symfony-polyfills:
        patterns:
          - "symfony/polyfill-*"
      twig:
        patterns:
          - "twig/*"
