tinyMCE.addI18n('ca.style_dlg',{
title:"Edita els estils CSS",
apply:"Aplica",
text_tab:"Text",
background_tab:"Fons",
block_tab:"Bloc",
box_tab:"Quadre",
border_tab:"Contorn",
list_tab:"Llista",
positioning_tab:"Posicionament",
text_props:"Text",
text_font:"Font",
text_size:"Mida",
text_weight:"Pes",
text_style:"Estil",
text_variant:"Variant",
text_lineheight:"Al\u00E7ada de l\u00EDnia",
text_case:"Cas",
text_color:"Color",
text_decoration:"Decoraci\u00F3",
text_overline:"sobreratllat",
text_underline:"subratllat",
text_striketrough:"barrat",
text_blink:"parpelleig",
text_none:"cap",
background_color:"Color de fons",
background_image:"Imatge de fons",
background_repeat:"Repeteix",
background_attachment:"Adjunt",
background_hpos:"Posici\u00F3 horitzontal",
background_vpos:"Posici\u00F3 vertical",
block_wordspacing:"Espaiat entre paraules",
block_letterspacing:"Espaiat entre lletres",
block_vertical_alignment:"Alineaci\u00F3 vertical",
block_text_align:"Alinea el text",
block_text_indent:"Sagna el text",
block_whitespace:"Espai en blanc",
block_display:"Visualitzaci\u00F3",
box_width:"Amplada",
box_height:"Al\u00E7ada",
box_float:"Flota",
box_clear:"Buida",
padding:"Separaci\u00F3",
same:"Igual per a tot",
top:"Dalt",
right:"Dreta",
bottom:"Avall",
left:"Esquerra",
margin:"Marge",
style:"Estil",
width:"Amplada",
height:"Al\u00E7ada",
color:"Color",
list_type:"Tipus",
bullet_image:"Imatge pic",
position:"Posici\u00F3",
positioning_type:"Tipus",
visibility:"Visibilitat",
zindex:"\u00CDndex Z",
overflow:"Desbordament",
placement:"Empla\u00E7ament",
clip:"Retall"
});