tinyMCE.addI18n('cy.style_dlg',{
title:"Golygu Arddull CSS",
apply:"Gosod",
text_tab:"Testun",
background_tab:"Cefndir",
block_tab:"Bloc",
box_tab:"Blwch",
border_tab:"Border",
list_tab:"Rhestr",
positioning_tab:"Lleoli",
text_props:"Testun",
text_font:"Ffont",
text_size:"Maint",
text_weight:"Pwysau",
text_style:"Arddull",
text_variant:"Amrywiad",
text_lineheight:"Uchder llinell",
text_case:"Llythrennau bach/mawr",
text_color:"Lliw",
text_decoration:"Addurniadau",
text_overline:"Llinell drosodd",
text_underline:"Llinell o dan",
text_striketrough:"Taro drwodd",
text_blink:"Blincio",
text_none:"Dim un",
background_color:"Lliw cefndir",
background_image:"Delwedd cefndir",
background_repeat:"Ailadrodd",
background_attachment:"Atodiad",
background_hpos:"Lleoliad llorweddol",
background_vpos:"Lleoliad fertigol",
block_wordspacing:"Bylchiad gair",
block_letterspacing:"Bylchiad lythyren",
block_vertical_alignment:"Aliniad fertigol",
block_text_align:"Alinio testun",
block_text_indent:"Mewnoli tetun",
block_whitespace:"Whitespace",
block_display:"Arddangos",
box_width:"Lled",
box_height:"Uchder",
box_float:"Arnofio",
box_clear:"Clirio",
padding:"Padio",
same:"Yr un ar gyfer pob un",
top:"Pen",
right:"De",
bottom:"Gwaelod",
left:"Chwith",
margin:"Ymyl",
style:"Arddull",
width:"Lled",
height:"Uchder",
color:"Lliw",
list_type:"Math",
bullet_image:"Delwedd bwled",
position:"Lleoliad",
positioning_type:"Math",
visibility:"Gwelededd",
zindex:"Mynegai-Z",
overflow:"Gorlif",
placement:"Gosodiad",
clip:"Clip"
});