tinyMCE.addI18n('et.style_dlg',{
title:"Muuda CSS stiili",
apply:"Rakenda",
text_tab:"Tekst",
background_tab:"Taust",
block_tab:"Plokk",
box_tab:"Kast",
border_tab:"Raam",
list_tab:"Nimekiri",
positioning_tab:"Positsioneerimine",
text_props:"Tekst",
text_font:"Font",
text_size:"Suurus",
text_weight:"Raskus",
text_style:"Stiil",
text_variant:"Variant",
text_lineheight:"Joone k\u00F5rgus",
text_case:"Kast",
text_color:"V\u00E4rv",
text_decoration:"Dekoratioon",
text_overline:"\u00FClejoon",
text_underline:"alajoon",
text_striketrough:"l\u00E4bikriipsutus",
text_blink:"vilgutus",
text_none:"mitte \u00FCkski",
background_color:"Tausta v\u00E4rv",
background_image:"Tausta pilt",
background_repeat:"Kordus",
background_attachment:"Manus",
background_hpos:"Horisontaalne asend",
background_vpos:"Vertikaalne asend",
block_wordspacing:"S\u00F5nade avardamine",
block_letterspacing:"T\u00E4he avardamine",
block_vertical_alignment:"Vertikaalne joondus",
block_text_align:"Teksti joondus",
block_text_indent:"Teksti taandus",
block_whitespace:"T\u00FChimik",
block_display:"Kuva",
box_width:"Laius",
box_height:"K\u00F5rgus",
box_float:"H\u00F5ljuv",
box_clear:"Puhas",
padding:"T\u00E4idis",
same:"Sama k\u00F5igile",
top:"\u00DCleval",
right:"Paremal",
bottom:"All",
left:"Vasakul",
margin:"Serv",
style:"Stiil",
width:"Laius",
height:"K\u00F5rgus",
color:"V\u00E4rv",
list_type:"T\u00FC\u00FCp",
bullet_image:"Punkt pilt",
position:"Positsioon",
positioning_type:"T\u00FC\u00FCp",
visibility:"N\u00E4htavus",
zindex:"Z-viit",
overflow:"\u00DClevool",
placement:"Asetus",
clip:"Klipp"
});