tinyMCE.addI18n('fi.style_dlg',{
title:"Muokkaa CSS-tyyli\u00E4",
apply:"K\u00E4yt\u00E4",
text_tab:"Teksti",
background_tab:"Tausta",
block_tab:"Palkki",
box_tab:"Laatikko",
border_tab:"Kehys",
list_tab:"Lista",
positioning_tab:"Sijainti",
text_props:"Teksti",
text_font:"Kirjasin",
text_size:"Koko",
text_weight:"Paino",
text_style:"Tyyli",
text_variant:"Variantti",
text_lineheight:"Rivin korkeus",
text_case:"Isot/pienet kirjaimet",
text_color:"V\u00E4ri",
text_decoration:"Koristelu",
text_overline:"Ylleviivattu",
text_underline:"Alleviivattu (Ctrl+U)",
text_striketrough:"Yliviivattu",
text_blink:"V\u00E4l\u00E4hdys",
text_none:"ei mit\u00E4\u00E4n",
background_color:"Taustav\u00E4ri",
background_image:"Taustakuva",
background_repeat:"Toistuvuus",
background_attachment:"Liite",
background_hpos:"Vaaka-asettelu",
background_vpos:"Pystyasettelu",
block_wordspacing:"Sanojen v\u00E4listys",
block_letterspacing:"Kirjainten v\u00E4listys",
block_vertical_alignment:"Pystyasettelu",
block_text_align:"Tekstin asettelu",
block_text_indent:"Tekstin sisennys",
block_whitespace:"Tyhj\u00E4 tila",
block_display:"N\u00E4ytt\u00F6",
box_width:"Leveys",
box_height:"Korkeus",
box_float:"Kellunta",
box_clear:"Nollaus",
padding:"Tyhj\u00E4 tila",
same:"Sama kaikille",
top:"Ylh\u00E4\u00E4ll\u00E4",
right:"Oikealla",
bottom:"Alhaalla",
left:"Vasemmalla",
margin:"Marginaali",
style:"Tyyli",
width:"Leveys",
height:"Korkeus",
color:"V\u00E4ri",
list_type:"Tyyppi",
bullet_image:"Listauskuva",
position:"Sijainti",
positioning_type:"Tyyppi",
visibility:"N\u00E4kyvyys",
zindex:"Z-indeksi",
overflow:"Ylivuoto",
placement:"Sijoittelu",
clip:"Leike"
});