tinyMCE.addI18n('gl.style_dlg',{
title:"Editar Estilo CSS",
apply:"Aplicar",
text_tab:"Texto",
background_tab:"Fondo",
block_tab:"Bloque",
box_tab:"Caixa",
border_tab:"Borde",
list_tab:"Lista",
positioning_tab:"Posici\u00F3n",
text_props:"Texto",
text_font:"Fonte",
text_size:"Tama\u00F1o",
text_weight:"Peso",
text_style:"Estilo",
text_variant:"Variante",
text_lineheight:"Ancho da fila",
text_case:"Min\u00FAs./May\u00FAs.",
text_color:"Cor",
text_decoration:"Decorativos",
text_overline:"Li\u00F1a superior",
text_underline:"Suli\u00F1ado",
text_striketrough:"Tachado",
text_blink:"Parpadeo",
text_none:"Neng\u00FAn",
background_color:"Cor de fondo",
background_image:"Imaxe de fondo",
background_repeat:"Repetir",
background_attachment:"Adxunto",
background_hpos:"Posici\u00F3n horizontal",
background_vpos:"Posici\u00F3n vertical",
block_wordspacing:"Espacio entre verbas",
block_letterspacing:"Espacio entre letras",
block_vertical_alignment:"Ali\u00F1aci\u00F3n vertical",
block_text_align:"Ali\u00F1aci\u00F3n do texto",
block_text_indent:"Sangr\u00EDa",
block_whitespace:"Espacio en branco",
block_display:"Display",
box_width:"Ancho",
box_height:"Alto",
box_float:"Float",
box_clear:"Limpar",
padding:"Recheo",
same:"O mesmo en todos",
top:"Arriba",
right:"Dereita",
bottom:"Abaixo",
left:"Esquerda",
margin:"Marxe",
style:"Estilo",
width:"Ancho",
height:"Alto",
color:"Cor",
list_type:"Tipo",
bullet_image:"Imaxe da vi\u00F1eta",
position:"Posici\u00F3n",
positioning_type:"Tipo",
visibility:"Visibilidade",
zindex:"\u00CDndize Z",
overflow:"Desbodramento",
placement:"Colocaci\u00F3n",
clip:"Clip"
});