tinyMCE.addI18n('lt.style_dlg',{
title:"Redaguoti CSS stili\u0173",
apply:"Taikyti",
text_tab:"Tekstas",
background_tab:"Fonas",
block_tab:"Blokas",
box_tab:"D\u0117\u017Eut\u0117",
border_tab:"R\u0117melis",
list_tab:"S\u0105ra\u0161as",
positioning_tab:"Pozicionavimas",
text_props:"Tekstas",
text_font:"\u0160riftas",
text_size:"Dydis",
text_weight:"Storis",
text_style:"Stilius",
text_variant:"Variantas",
text_lineheight:"Eilut\u0117s auk\u0161tis",
text_case:"Ma\u017Eosios/did\u017Eiosios raid\u0117s",
text_color:"Spalva",
text_decoration:"Dekoracija",
text_overline:"pabraukta vir\u0161uje",
text_underline:"pabraukta apa\u010Dioje",
text_striketrough:"perbraukta",
text_blink:"mirks\u0117jimas",
text_none:"joks",
background_color:"Fono spalva",
background_image:"Fono paveiksl\u0117lis",
background_repeat:"Kartoti",
background_attachment:"Priedas",
background_hpos:"Horizontali pozicija",
background_vpos:"Vertikali pozicija",
block_wordspacing:"Tarpai tarp \u017Eod\u017Ei\u0173",
block_letterspacing:"Tarpai tarp raid\u017Ei\u0173",
block_vertical_alignment:"Vertikalus lygiavimas",
block_text_align:"Teksto lygiavimas",
block_text_indent:"Teksto atitraukimas",
block_whitespace:"Tarpai",
block_display:"Rodymas",
box_width:"Ilgis",
box_height:"Auk\u0161tis",
box_float:"Slankus",
box_clear:"I\u0161valyti",
padding:"U\u017Epildymas",
same:"Tas pats visiems",
top:"Vir\u0161uje",
right:"De\u0161in\u0117je",
bottom:"Apa\u010Dioje",
left:"Kair\u0117je",
margin:"Para\u0161t\u0117",
style:"Stilius",
width:"Ilgis",
height:"Auk\u0161tis",
color:"Spalva",
list_type:"Tipas",
bullet_image:"\u017Denklelio paveiksl\u0117lis",
position:"Pozicija",
positioning_type:"Tipas",
visibility:"Matomumas",
zindex:"Z-indeksas",
overflow:"Perpildymas",
placement:"Talpinimas",
clip:"\u012Era\u0161as"
});