tinyMCE.addI18n('lv.style_dlg',{
title:"Edit CSS Style",
apply:"Apply",
text_tab:"Text",
background_tab:"Background",
block_tab:"Block",
box_tab:"Box",
border_tab:"Border",
list_tab:"List",
positioning_tab:"Positioning",
text_props:"Text",
text_font:"Font",
text_size:"Size",
text_weight:"Weight",
text_style:"Style",
text_variant:"Variant",
text_lineheight:"Line height",
text_case:"Case",
text_color:"Color",
text_decoration:"Decoration",
text_overline:"overline",
text_underline:"underline",
text_striketrough:"strikethrough",
text_blink:"blink",
text_none:"none",
background_color:"Background color",
background_image:"Background image",
background_repeat:"Repeat",
background_attachment:"Attachment",
background_hpos:"Horizont\u0101l\u0101 poz\u012Bcija",
background_vpos:"Vertik\u0101l\u0101 poz\u012Bcija",
block_wordspacing:"V\u0101rdu atstarpe",
block_letterspacing:"Burtu atstarpe",
block_vertical_alignment:"Vertik\u0101lais izl\u012Bdzin\u0101jums",
block_text_align:"Teksta izl\u012Bdzin\u0101jums",
block_text_indent:"\u00C9crit indent",
block_whitespace:"Tuk\u0161ais laukums",
block_display:"Display",
box_width:"Platums",
box_height:"Augstums",
box_float:"Float",
box_clear:"Clear",
padding:"Atstarpe",
same:"Same for all",
top:"Aug\u0161a",
right:"Pa labi",
bottom:"Apak\u0161a",
left:"Pa kreisi",
margin:"Mala",
style:"St\u012Bls",
width:"Platums",
height:"Augstums",
color:"Kr\u0101sa",
list_type:"Tips",
bullet_image:"Bullet bilde",
position:"Poz\u012Bcija",
positioning_type:"Tips",
visibility:"Redzam\u012Bba",
zindex:"Z-index",
overflow:"P\u0101rm\u0113rs",
placement:"Izvietojums",
clip:"Klips"
});