tinyMCE.addI18n('ms.style_dlg',{
title:"Sunting Gaya CSS",
apply:"Guna",
text_tab:"Teks",
background_tab:"Latar belakang",
block_tab:"Landasan",
box_tab:"Kotak",
border_tab:"Sempadan",
list_tab:"Senarai",
positioning_tab:"Kedudukan",
text_props:"Teks",
text_font:"Huruf",
text_size:"Saiz",
text_weight:"Beban",
text_style:"Gaya",
text_variant:"Varian",
text_lineheight:"Tinggi garisan",
text_case:"Kes",
text_color:"Warna",
text_decoration:"Dekorasi",
text_overline:"garis atas",
text_underline:"garis bawah",
text_striketrough:"garis tengah",
text_blink:"kelip",
text_none:"tiada",
background_color:"Warna Latar",
background_image:"Imej Latar",
background_repeat:"Ulangan",
background_attachment:"Sisipan",
background_hpos:"Posisi mengufuk",
background_vpos:"Posisi tegak",
block_wordspacing:"Jarak perkataan",
block_letterspacing:"Jarak huruf",
block_vertical_alignment:"Penjajaran tegak",
block_text_align:"Penjajaran teks",
block_text_indent:"Takukan teks",
block_whitespace:"Ruangan putih",
block_display:"Pamer",
box_width:"Lebar",
box_height:"Tinggi",
box_float:"Apungan",
box_clear:"Ruangan jelas",
padding:"Lapisan",
same:"Samakan kesemuanya",
top:"Atas",
right:"Kanan",
bottom:"Bawah",
left:"Kiri",
margin:"Ruangan tepi",
style:"Gaya",
width:"Lebar",
height:"Tinggi",
color:"Warna",
list_type:"Jenis",
bullet_image:"Imej peluru",
position:"Posisi",
positioning_type:"Jenis",
visibility:"Kelihatan",
zindex:"Indeks-Z",
overflow:"Limpahan",
placement:"Penempatan",
clip:"Klip"
});