tinyMCE.addI18n('nn.style_dlg',{
title:"Rediger CSS-stil",
apply:"Legg til",
text_tab:"Tekst",
background_tab:"Bakgrunn",
block_tab:"Blokk",
box_tab:"Boks",
border_tab:"Ramme",
list_tab:"Liste",
positioning_tab:"Posisjon",
text_props:"Eigenskapar for skrift",
text_font:"Skrifttype",
text_size:"Skriftstorleik",
text_weight:"Skriftvekt",
text_style:"Skriftstil",
text_variant:"Variant",
text_lineheight:"Linjeh\u00F8gd",
text_case:"Kapitelar/minusklar",
text_color:"Farge",
text_decoration:"Dekorasjon",
text_overline:"Heva skrift",
text_underline:"Senka skrift",
text_striketrough:"Gjennomstreking",
text_blink:"Blink",
text_none:"Ingen",
background_color:"Bakgrunnsfarge",
background_image:"Bakgrunnsbilete",
background_repeat:"Gjenta",
background_attachment:"Vedlegg",
background_hpos:"Horisontal posisjon",
background_vpos:"Vertikal posisjon",
block_wordspacing:"Ordmellomrom",
block_letterspacing:"Bokstavmellomrom",
block_vertical_alignment:"Vertikal justering",
block_text_align:"Justering",
block_text_indent:"Innrykk",
block_whitespace:"Mellomrom",
block_display:"Framsyning",
box_width:"Breidd",
box_height:"H\u00F8gd",
box_float:"Flyt",
box_clear:"Slett",
padding:"Utfylling",
same:"Likt i alle",
top:"Topp",
right:"H\u00F8gre",
bottom:"Bunn",
left:"Venstre",
margin:"Marg",
style:"Stil",
width:"Breidd",
height:"H\u00F8gd",
color:"Farge",
list_type:"Type",
bullet_image:"Kulepunktbilete",
position:"Posisjon",
positioning_type:"Type",
visibility:"Synlegheit",
zindex:"Z-indeks",
overflow:"Overfylt",
placement:"Plassering",
clip:"Klipp"
});