tinyMCE.addI18n('pl.style_dlg',{
title:"Edytuj CSS Style",
apply:"Zastosuj",
text_tab:"Text",
background_tab:"T\u0142o",
block_tab:"Zablokuj",
box_tab:"Box",
border_tab:"Obramowanie",
list_tab:"Lista",
positioning_tab:"Pozycjonowanie",
text_props:"Tekst",
text_font:"Wz\u00F3r czcionki",
text_size:"Rozmiar",
text_weight:"Waga",
text_style:"Styl",
text_variant:"Wariant",
text_lineheight:"Linia wysoko\u015Bci",
text_case:"Case",
text_color:"Kolor",
text_decoration:"Dekoracja",
text_overline:"Nadkre\u015Blenie",
text_underline:"Podkre\u015Blenie",
text_striketrough:"Przekre\u015Blenie",
text_blink:"Miganie",
text_none:"\u017Baden",
background_color:"Kolor t\u0142a",
background_image:"Obrazek t\u0142a",
background_repeat:"Powt\u00F3rz",
background_attachment:"Za\u0142\u0105cznik",
background_hpos:"Pozycja pozioma",
background_vpos:"Pozycja pionowa",
block_wordspacing:"Odst\u0119p mi\u0119dzy wyrazami",
block_letterspacing:"Odst\u0119p mi\u0119dzy literami",
block_vertical_alignment:"Pionowe wyr\u00F3wnanie",
block_text_align:"Wyr\u00F3wna\u0107 tekst",
block_text_indent:"Akapit w tek\u015Bcie",
block_whitespace:"Bia\u0142a przestrze\u0144",
block_display:"Widoczno\u015B\u0107",
box_width:"Szeroko\u015B\u0107",
box_height:"Wysoko\u015B\u0107",
box_float:"P\u0142ywanie",
box_clear:"Wyczy\u015B\u0107",
padding:"Odst\u0119py",
same:"To samo dla wszystkich",
top:"G\u00F3ra",
right:"Prawy",
bottom:"D\u00F3\u0142",
left:"Lewy",
margin:"Margines",
style:"Styl",
width:"Szeroko\u015B\u0107",
height:"Wysoko\u015B\u0107",
color:"Kolor",
list_type:"Typ",
bullet_image:"Obrazek listy",
position:"Pozycja",
positioning_type:"Typ",
visibility:"Widoczno\u015B\u0107",
zindex:"Z-index",
overflow:"Przepe\u0142niony",
placement:"Umieszczenie",
clip:"Clip"
});