tinyMCE.addI18n('ro.style_dlg',{
title:"Editare CSS",
apply:"Aplic\u0103",
text_tab:"Text",
background_tab:"Fundal",
block_tab:"Block",
box_tab:"Box",
border_tab:"Bordur\u0103",
list_tab:"List\u0103",
positioning_tab:"Pozi\u0163ionare",
text_props:"Text",
text_font:"Font",
text_size:"M\u0103rime",
text_weight:"Greutate",
text_style:"Stil",
text_variant:"Variant\u0103",
text_lineheight:"\u00CEn\u0103l\u0163ime linie",
text_case:"Caz",
text_color:"Culoare",
text_decoration:"Decora\u0163ii",
text_overline:"Peste linie",
text_underline:"Sub linie",
text_striketrough:"T\u0103iere",
text_blink:"Clipire",
text_none:"Nici unul",
background_color:"Culoare fundal",
background_image:"Imagine fundal",
background_repeat:"Repet\u0103",
background_attachment:"Ata\u015Fament",
background_hpos:"Pozi\u0163ionare orizontal\u0103",
background_vpos:"Pozi\u0163ionare vertical\u0103",
block_wordspacing:"Spa\u0163iere cuvinte",
block_letterspacing:"Spa\u0163iere litere",
block_vertical_alignment:"Aliniere vertical\u0103",
block_text_align:"Aliniere text",
block_text_indent:"Indentare text",
block_whitespace:"Spa\u0163iu alb",
block_display:"Afi\u015Fare",
box_width:"L\u0103\u0163ime",
box_height:"\u00CEn\u0103l\u0163ime",
box_float:"Plutitoare",
box_clear:"Normal\u0103",
padding:"Margini interne",
same:"La fel pentru toate",
top:"Sus",
right:"Dreapta",
bottom:"Jos",
left:"St\u00E2nga",
margin:"Margini",
style:"Stil",
width:"L\u0103\u0163ime",
height:"\u00CEn\u0103l\u0163ime",
color:"Culoare",
list_type:"Tip",
bullet_image:"Imagine",
position:"Pozi\u0163ionare",
positioning_type:"Tip",
visibility:"Vizibilitate",
zindex:"Z-index",
overflow:"Overflow",
placement:"Plasament",
clip:"Clip"
});