tinyMCE.addI18n('sk.style_dlg',{
title:"Upravi\u0165 CSS",
apply:"Aplikova\u0165",
text_tab:"Text",
background_tab:"Pozadie",
block_tab:"Blok",
box_tab:"Box",
border_tab:"R\u00E1m\u010Dek",
list_tab:"Zoznam",
positioning_tab:"Positioning",
text_props:"Text",
text_font:"Font",
text_size:"Ve\u013Ekos\u0165",
text_weight:"Weight",
text_style:"Style",
text_variant:"Variant",
text_lineheight:"Odsadenie riadkov",
text_case:"Case",
text_color:"Farba",
text_decoration:"Dekor\u00E1cia",
text_overline:"overline",
text_underline:"underline",
text_striketrough:"strikethrough",
text_blink:"blink",
text_none:"\u017Eiadne",
background_color:"Farba pozadia",
background_image:"Obr\u00E1zok pozadia",
background_repeat:"Repeat",
background_attachment:"Pr\u00EDloha",
background_hpos:"Horizontal position",
background_vpos:"Vertical position",
block_wordspacing:"Word spacing",
block_letterspacing:"Letter spacing",
block_vertical_alignment:"Vertical alignment",
block_text_align:"Text align",
block_text_indent:"Text indent",
block_whitespace:"Whitespace",
block_display:"Display",
box_width:"\u0160\u00EDrka",
box_height:"V\u00FD\u0161ka",
box_float:"Float",
box_clear:"Clear",
padding:"Padding",
same:"Same for all",
top:"Top",
right:"Right",
bottom:"Bottom",
left:"Left",
margin:"Margin",
style:"Style",
width:"\u0160\u00EDrka",
height:"V\u00FD\u0161ka",
color:"Farba",
list_type:"Type",
bullet_image:"Bullet image",
position:"Position",
positioning_type:"Type",
visibility:"Visibility",
zindex:"Z-index",
overflow:"Overflow",
placement:"Placement",
clip:"Clip"
});