tinyMCE.addI18n('sq.style_dlg',{
title:"Edito t\u00EB gjitha stilet",
apply:"Apliko",
text_tab:"Teksti",
background_tab:"Fusha",
block_tab:"Bllok",
box_tab:"Kuti",
border_tab:"Korniza",
list_tab:"Lista",
positioning_tab:"Pozicionimi",
text_props:"Teksti",
text_font:"Teksti",
text_size:"Madh\u00EBsia",
text_weight:"Pesha",
text_style:"Stili",
text_variant:"Varianti",
text_lineheight:"Gjat\u00EBsia e linj\u00EBs",
text_case:"Madh\u00EBsia e g\u00EBrm\u00EBs",
text_color:"Ngjyra",
text_decoration:"Zbukurimi",
text_overline:"mbi linj\u00EB",
text_underline:"n\u00EBn linj\u00EB",
text_striketrough:"n\u00EB mes",
text_blink:"fik-ndiz",
text_none:"asnj\u00EB",
background_color:"Ngjyra e fush\u00EBs",
background_image:"Foto e fush\u00EBs",
background_repeat:"P\u00EBrs\u00EBritja",
background_attachment:"Bashk\u00EBngjitja",
background_hpos:"Pozicionimi horizontal",
background_vpos:"Pozicionimi vertikal",
block_wordspacing:"Hap\u00EBsira e fjal\u00EBve",
block_letterspacing:"Hap\u00EBsira e g\u00EBrmave",
block_vertical_alignment:"Drejtimi vertikal",
block_text_align:"Drejtimi i tekstit",
block_text_indent:"Kryerradha",
block_whitespace:"Hap\u00EBsira bosh",
block_display:"Shfaqja",
box_width:"Gjer\u00EBsia",
box_height:"Gjat\u00EBsia",
box_float:"Pluskimi",
box_clear:"Pastro",
padding:"Hap\u00EBsira e br\u00EBndshme",
same:"E nj\u00EBjt\u00EB p\u00EBr t\u00EB gjitha",
top:"Krye",
right:"Djathtas",
bottom:"Fund",
left:"Majtas",
margin:"Hap\u00EBsira",
style:"Stili",
width:"Gjer\u00EBsia",
height:"Gjat\u00EBsia",
color:"Ngjyra",
list_type:"Tipi",
bullet_image:"Foto ndar\u00EBse",
position:"Pozicioni",
positioning_type:"Tipi",
visibility:"Shikueshm\u00EBria",
zindex:"Indeksi Z",
overflow:"Mbivendosja",
placement:"Vendosja",
clip:"Prerja"
});