tinyMCE.addI18n('tr.style_dlg',{
title:"CSS Stili D\u00FCzen",
apply:"Uygula",
text_tab:"Metin",
background_tab:"Arkaplan",
block_tab:"Blok",
box_tab:"Kutu",
border_tab:"Kenarl ",
list_tab:"Liste",
positioning_tab:"Konumland\u0131r",
text_props:"Metin",
text_font:"Yaz\u0131 Ti",
text_size:"Boyut",
text_weight:"Kal\u0131n",
text_style:"Stil",
text_variant:"De\u011Fi",
text_lineheight:"Sat\u0131r y\u00FCksek",
text_case:"B\u00FCy\u00FCk/",
text_color:"Renk",
text_decoration:"Dekorasyon",
text_overline:"\u00DCst \u00E7",
text_underline:"Alt \u00E7iz",
text_striketrough:"Ortas\u0131 \u00E7iz",
text_blink:"yan\u0131p s",
text_none:"hi\u00E7bi",
background_color:"Arkaplan rengi",
background_image:"Arkaplan resmi",
background_repeat:"Tekrarla",
background_attachment:"Eklenti",
background_hpos:"Yatay konum",
background_vpos:"Dikey konum",
block_wordspacing:"S\u00F6zc\u00FCk bo",
block_letterspacing:"Harf bo\u015Fl",
block_vertical_alignment:"Dikey hizalama",
block_text_align:"Metin hizalama",
block_text_indent:"Metin kayd\u0131r",
block_whitespace:"Bo\u015Fl",
block_display:"G\u00F6r\u00FCnt",
box_width:"Geni\u015Fl",
box_height:"Y\u00FCksekl",
box_float:"Kayan",
box_clear:"Serbest",
padding:"Dolgu",
same:"T\u00FCm\u00FC i\u00E7i",
top:"\u00DC",
right:"Sae",
bottom:"Alt",
left:"Sol",
margin:"Kenar bo\u015Flu",
style:"Stil",
width:"Geni\u015Fl",
height:"Y\u00FCksekl",
color:"Renk",
list_type:"Tip",
bullet_image:"Madde imi resmi",
position:"Konum",
positioning_type:"Tip",
visibility:"G\u00F6r\u00FCn",
zindex:"Z-s\u0131ra",
overflow:"Ta\u015F",
placement:"Yerle\u015Ftir",
clip:"K\u0131rp"
});