<?php

/**
 * ---------------------------------------------------------------------
 *
 * GLPI - Gestionnaire Libre de Parc Informatique
 *
 * http://glpi-project.org
 *
 * @copyright 2015-2024 Teclib' and contributors.
 * @copyright 2003-2014 by the INDEPNET Development Team.
 * @licence   https://www.gnu.org/licenses/gpl-3.0.html
 *
 * ---------------------------------------------------------------------
 *
 * LICENSE
 *
 * This file is part of GLPI.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * ---------------------------------------------------------------------
 */

namespace tests\units\Glpi\Form\Destination\CommonITILField;

use DbTestCase;
use Glpi\Form\AnswersSet;
use Glpi\Form\QuestionType\QuestionTypeShortText;
use Glpi\Form\Tag\AnswerTagProvider;
use Glpi\Form\Tag\Tag;
use Glpi\Tests\FormBuilder;
use Glpi\Tests\FormTesterTrait;

final class ContentField extends DbTestCase
{
    use FormTesterTrait;

    public const FAKE_QUESTION_ID = 5555;

    public function testApplyConfiguratedValueToInputUsingAnswers(): void
    {
        $tag = $this->getDummyTag();
        $value = "My custom content using tags: {$tag->html}";

        $field = new \Glpi\Form\Destination\CommonITILField\ContentField();
        $input = $field->applyConfiguratedValueToInputUsingAnswers(
            configurated_value: $value,
            input             : [],
            answers_set       : $this->getFakeAnswers(),
        );

        $this->string($input['content'])->isEqualTo(
            'My custom content using tags: content generated by tag'
        );
    }

    public function testGetAutoGeneratedValue(): void
    {
        $form_builder = new FormBuilder();
        $form_builder->addQuestion("First name", QuestionTypeShortText::class);
        $form_builder->addQuestion("Last name", QuestionTypeShortText::class);
        $form = $this->createForm($form_builder);

        $field = new \Glpi\Form\Destination\CommonITILField\ContentField();
        $generated_value = $field->getAutoGeneratedValue($form);

        $this->string($generated_value)->contains("Question: First name");
        $this->string($generated_value)->contains("Question: Last name");
        $this->string($generated_value)->contains("Answer: First name");
        $this->string($generated_value)->contains("Answer: Last name");
    }

    private function getDummyTag(): Tag
    {
        return new Tag(
            label   : 'Dummy label',
            value   : self::FAKE_QUESTION_ID,
            provider: AnswerTagProvider::class,
            color   : AnswerTagProvider::ACCENT_COLOR,
        );
    }

    private function getFakeAnswers(): AnswersSet
    {
        $answers = new AnswersSet();
        $answers->fields['answers'] = json_encode([
            [
                'question_id'       => self::FAKE_QUESTION_ID,
                'raw_answer'        => 'content generated by tag',
                'raw_question_type' => AnswerTagProvider::class,
                'question_label'    => 'Dummy label',
            ],
        ]);
        return $answers;
    }
}
