// Greek lang variables by Jacaranda Bill
// Revised by Dimitris Giannitsaros / MediSign SA

tinyMCE.addToLang('',{
table_desc : 'Εισαγωγή πίνακα',
table_insert_row_before_desc : 'Εισαγωγή γραμμής πάνω',
table_insert_row_after_desc : 'Εισαγωγή γραμμής κάτω',
table_delete_row_desc : 'Διαγραφή γραμμής',
table_insert_col_before_desc : 'Εισαγωγή στήλης αριστερά',
table_insert_col_after_desc : 'Εισαγωγή στήλης δεξιά',
table_delete_col_desc : 'Διαγραφή στήλης',
insert_table_title : 'Εισαγωγή/Διόρθωση πίνακα',
insert_table_width : 'Πλάτος',
insert_table_height : 'Ύψος',
insert_table_cols : 'Στήλες',
insert_table_rows : 'Γραμμές',
insert_table_cellspacing : 'Διάστιχο',
insert_table_cellpadding : 'Γέμισμα',
insert_table_border : 'Περίγραμμα',
insert_table_align : 'Στοίχιση',
insert_table_align_default : 'Προκαθ.',
insert_table_align_left : 'Αριστερά',
insert_table_align_right : 'Δεξιά',
insert_table_align_middle : 'Στο κέντρο',
insert_table_class : 'Κλάση',
table_row_title : 'Ιδιότητες γραμμής',
table_cell_title : 'Ιδιότητες κελιού',
table_row_desc : 'Ιδιότητες γραμμής',
table_cell_desc : 'Ιδιότητες κελιού',
insert_table_valign : 'Κάθετη στοίχιση',
insert_table_align_top : 'Πάνω',
insert_table_align_bottom : 'Κάτω',
table_props_desc : 'Ιδιότητες πίνακα',
table_bordercolor : 'Χρώμα περιθωρίου',
table_bgcolor : 'Χρώμα bg',
table_merge_cells_title : 'Ένωση κελιών',
table_split_cells_desc : 'Χώρισμα κελιών',
table_merge_cells_desc : 'Ένωση κελιών',
table_cut_row_desc : 'Αποκοπή γραμμής',
table_copy_row_desc : 'Αντιγραφή γραμμής',
table_paste_row_before_desc : 'Επικόλληση πριν τη γραμμή',
table_paste_row_after_desc : 'Επικόλληση μετά τη γραμμή',
table_insert_desc : 'Εισαγωγή νέου πίνακα'
});
