// FR lang variables
// Modified by Motte, last updated 2006-03-23

tinyMCE.addToLang('table',{
general_tab : 'G&eacute;n&eacute;ral',
advanced_tab : 'Avanc&eacute;',
general_props : 'Propri&eacute;t&eacute;s g&eacute;n&eacute;rales',
advanced_props : 'Propri&eacute;t&eacute;s avanc&eacute;es',
desc : 'Ins&eacute;rer/Modifier un tableau',
row_before_desc : 'Ins&eacute;rer une rang&eacute;e avant',
row_after_desc : 'Ins&eacute;rer une rang&eacute;e apr&egrave;s',
delete_row_desc : 'Effacer la rang&eacute;e',
col_before_desc : 'Ins&eacute;rer une colonne avant',
col_after_desc : 'Ins&eacute;rer une colonne apr&egrave;s',
delete_col_desc : 'Effacer la colonne',
rowtype : 'Type de rang&eacute;e',
title : 'Gestionnaire de tableau',
width : 'Largeur',
height : 'Hauteur',
cols : 'Colonnes',
rows : 'Rang&eacute;es',
cellspacing : 'Entre les cellules',
cellpadding : 'Marges int&eacute;rieures',
border : 'Bordures',
align : 'Alignement horizontal',
align_default : 'Par d&eacute;fault',
align_left : 'A gauche',
align_right : 'A droite',
align_middle : 'Centr&eacute;',
row_title : 'Propri&eacute;t&eacute;s des rang&eacute;es',
cell_title : 'Propri&eacute;t&eacute;s des cellules',
cell_type : 'Type',
row_desc : 'Propri&eacute;t&eacute;s des rang&eacute;es',
cell_desc : 'Propri&eacute;t&eacute;s des cellules',
valign : 'Alignement vertical',
align_top : 'Haut',
align_bottom : 'Bas',
props_desc : 'Propri&eacute;t&eacute;s du tableau',
bordercolor : 'Couleur des bordures',
bgcolor : 'Couleur d\'arri&egrave;re-plan',
merge_cells_title : 'Fusionner les cellules',
split_cells_desc : 'Scinder les cellules',
merge_cells_desc : 'Fusionner les cellules',
cut_row_desc : 'Eliminer la rang&eacute;e',
copy_row_desc : 'Copier la rang&eacute;e',
paste_row_before_desc : 'Coller la rang&eacute;e avant',
paste_row_after_desc : 'Coller la rang&eacute;e apr&egrave;s',
id : 'Id',
style: 'Style en ligne',
langdir : 'Sens d\'&eacute;criture',
langcode : 'Code de langue',
mime : 'Type MIME de la cible',
ltr : 'Vers la droite',
rtl : 'Vers la gauche',
bgimage : 'Image d\'arri&egrave;re-plan',
summary : 'Descriptif',
td : "Donn&eacute;e",
th : "En-t&ecirc;te",
cell_cell : 'Appliquer &agrave; la cellule',
cell_row : 'Appliquer &agrave; toute la rang&eacute;e',
cell_all : 'Appliquer &agrave; tout le tableau',
row_row : 'Appliquer &agrave; la rang&eacute;e',
row_odd : 'Appliquer aux rang&eacute;es pair',
row_even : 'Appliquer aux rang&eacute;es impair',
row_all : 'Appliquer &agrave; toutes les rang&eacute;es',
thead : 'En-t&ecirc;te',
tbody : 'Corps',
tfoot : 'Pied',
del : 'Effacer le tableau',
scope : 'Attribut scope',
row : 'Rang&eacute;e',
col : 'Colonne',
rowgroup : 'Groupe de rang&eacute;es',
colgroup : 'Groupe de colonnes',
missing_scope: 'Les attributs scope rendraient votre tableau de donn&eacute;es plus\naccessible &agrave; certains groupes d\'utilisateurs.\n\nEtes-vous s&ucirc;r de ne pas vouloir sp&eacute;cifier\nd\'attribut scope aux cellules d\'en-t&ecirc;te ?\n\n',
cellprops_delta_width : 50
});
