/**
 * IT lang variables
 * 
 * Author : Luciano Vernaschi <luciano@virgilio.it>
 * Last Updated : Mar. 1st, 2007
 * TinyMCE Version : 2.1.0
 */

tinyMCE.addToLang('table',{
general_tab : 'Generale',
advanced_tab : 'Avanzate',
general_props : 'Propriet&agrave; generali',
advanced_props : 'Propriet&agrave; avanzate',
desc : 'Inserisci una nuova tabella',
row_before_desc : 'Inserisci una riga prima',
row_after_desc : 'Inserisci una riga dopo',
delete_row_desc : 'Cancella riga',
col_before_desc : 'Inserisci una colonna prima',
col_after_desc : 'Inserisci una colonna dopo',
delete_col_desc : 'Cancella colonna',
rowtype : 'Tipo di riga',
title : 'Inserisci o modifica tabella',
width : 'Larghezza',
height : 'Altezza',
cols : 'Colonne',
rows : 'Righe',
cellspacing : 'Spaziatura tra celle',
cellpadding : 'Margine interno celle',
border : 'Bordo',
align : 'Allineamento',
align_default : 'Predefinito',
align_left : 'A sinistra',
align_right : 'A destra',
align_middle : 'Al centro',
row_title : 'Propriet&agrave; di riga',
cell_title : 'Propriet&agrave; di cella',
cell_type : 'Tipo di cella',
row_desc : 'Propriet&agrave; di riga',
cell_desc : 'Propriet&agrave; di cella',
valign : 'Allineamento verticale',
align_top : 'In alto',
align_bottom : 'In basso',
props_desc : 'Propriet&agrave; di tabella',
bordercolor : 'Colore del bordo',
bgcolor : 'Colore di sfondo',
merge_cells_title : 'Unisci celle',
split_cells_desc : 'Dividi celle',
merge_cells_desc : 'Unisci celle',
cut_row_desc : 'Taglia riga',
copy_row_desc : 'Copia riga',
paste_row_before_desc : 'Incolla riga prima',
paste_row_after_desc : 'Incolla riga dopo',
id : 'Id',
style: 'Stile',
langdir : 'Direzione del testo',
langcode : 'Codifica lingua',
mime : 'Tipo MIME destinazione',
ltr : 'Da sinistra a destra',
rtl : 'Da destra a sinistra',
bgimage : 'Immagine di sfondo',
summary : 'Riassunto',
td : "Normale",
th : "Intestazione",
cell_cell : 'Aggiorna cella corrente',
cell_row : 'Aggiorna tutte le celle della riga',
cell_all : 'Aggiorna tutte le celle della tabella',
row_row : 'Aggiorna riga corrente',
row_odd : 'Aggiorna righe dispari della tabella',
row_even : 'Aggiorna righe pari della tabella',
row_all : 'Aggiorna tutte le righe della tabella',
thead : 'Intestazione',
tbody : 'Corpo',
tfoot : 'Footer',
del : 'Elimina tabella',
scope : 'Ambito',
row : 'Riga',
col : 'Colonna',
rowgroup : 'Gruppo di righe',
colgroup : 'Gruppo di colonne',
col_limit : 'Hai superato il massimo numero di colonne di {$cols}.',
row_limit : 'Hai superato il massimo numero di righe di {$rows}.',
cell_limit : 'Hai superato il massimo numero di celle di {$cells}.',
missing_scope: 'Sei sicuro di voler omettere un ambito per questa cella di intestazione? L\'ambito &egrave; utile alle persone con disabilit&agrave; per interpretare i contenuti della tabella.',
caption : 'Intestazione tabella',
cellprops_delta_width : 150
});
