// 日本語 utf-8 lang variables

tinyMCE.addToLang('table',{
general_tab : '一般',
advanced_tab : '詳細',
general_props : '一般のプロパティ',
advanced_props : '詳細のプロパティ',
desc : 'テーブルを挿入',
row_before_desc : '前に行を挿入',
row_after_desc : '後に行を挿入',
delete_row_desc : '行を削除',
col_before_desc : '前に列を挿入',
col_after_desc : '後に列を挿入',
delete_col_desc : '列を削除',
rowtype : 'テーブルの行',
title : 'テーブルを挿入・編集',
width : '幅',
height : '高さ',
cols : '列数',
rows : '行数',
cellspacing : 'セル間隔',
cellpadding : 'セル余白',
border : 'ボーダー',
align : '行揃え',
align_default : '指定なし',
align_left : '左',
align_right : '右',
align_middle : '中央',
row_title : '行',
cell_title : 'セルのプロパティ',
cell_type : 'Cell type',
row_desc : '行のプロパティ',
cell_desc : 'セルのプロパティ',
valign : '上下揃え',
align_top : '上',
align_bottom : '下',
props_desc : 'テーブルのプロパティ',
bordercolor : 'ボーダーカラー',
bgcolor : '背景色',
merge_cells_title : 'セルのマージ',
split_cells_desc : 'セルの分割',
merge_cells_desc : 'セルのマージ',
cut_row_desc : '行を切り抜き',
copy_row_desc : '行を貼り付け',
paste_row_before_desc : '前に行を貼り付け',
paste_row_after_desc : '後に行を貼り付け',
id : 'テーブル ID',
style: 'スタイル',
langdir : '言葉の向き',
langcode : '言葉のコード',
mime : 'ターゲット MIME タイプ',
ltr : '左から右へ',
rtl : '右から左へ',
bgimage : '背景イメージ',
summary : '要約',
td : "データ",
th : "ヘッダ",
cell_cell : 'セルを更新',
cell_row : 'この行のセルを更新',
cell_all : '全セルを更新',
row_row : '行を更新',
row_odd : '奇数の行を更新',
row_even : '偶数の行を更新',
row_all : '全行を更新',
thead : 'ヘッダー',
tbody : 'テーブルBody',
tfoot : 'フッター',
del : 'テーブルを削除',
scope : 'スコープ',
row : '行',
col : '列',
rowgroup : '行のグループ',
colgroup : '列のグループ',
missing_scope: 'ヘッダーのスコープを設定しなくてもいいですか。スコープがなければ、障害者が理解し辛いかもしれません。'
});
