// PL lang variables
// fixed by Wooya
// http://www.mfusion.prv.pl

tinyMCE.addToLang('table',{
general_tab : 'Główne ustawienia',
advanced_tab : 'Zaawansowane',
general_props : 'Główne ustawienia',
advanced_props : 'Zaawansowane ustawienia',
desc : 'Wstawia nową tabelę',
row_before_desc : 'Wstaw wiersz przed',
row_after_desc : 'Wstaw wiersz za',
delete_row_desc : 'Usuń wiersz',
col_before_desc : 'Wstaw kolumnę przed',
col_after_desc : 'Wstaw kolumnę za',
delete_col_desc : 'Usuń kolumnę',
rowtype : 'Wiersz w części tabeli',
title : 'Wstaw/Zmień tabelę',
width : 'Szerokość',
height : 'Wysokość',
cols : 'Kolumn',
rows : 'Wierszy',
cellspacing : 'Odstępy między komórkami',
cellpadding : 'Margines wewnątrz komórek',
border : 'Ramka',
align : 'Wyrównanie',
align_default : 'Domyślne',
align_left : 'Lewo',
align_right : 'Prawo',
align_middle : 'środek',
row_title : 'Właściwości wiersza',
cell_title : 'Właściwości komórki',
cell_type : 'Typ komórki',
row_desc : 'Właściwości wiersza',
cell_desc : 'Właściwości komórki',
valign : 'Wyrównanie pionowe',
align_top : 'Do góry',
align_bottom : 'Do dołu',
props_desc : 'Właściwości tabeli',
bordercolor : 'Kolor ramki',
bgcolor : 'Kolor tła',
merge_cells_title : 'Połącz komórki',
split_cells_desc : 'Rozdziel komórki',
merge_cells_desc : 'Połącz komórki',
cut_row_desc : 'Wytnij wiersz',
copy_row_desc : 'Kopiuj wiersz',
paste_row_before_desc : 'Wklej wiersz przed',
paste_row_after_desc : 'Wklej wiersz za',
id : 'Id',
style: 'Styl',
langdir : 'Kierunek tekstu',
langcode : 'Kod języka',
mime : 'Docelowy typ MIME',
ltr : 'Lewy do prawego',
rtl : 'Prawy do lewego',
bgimage : 'Obrazek tła',
summary : 'Podsumowanie',
td : "Dane",
th : "Nagłówek",
cell_cell : 'Aktualizuj bieżącą komórkę',
cell_row : 'Aktualizuj wszystkie komórki w wierszu',
cell_all : 'Aktualizuj wszystkie komórki w tabeli',
row_row : 'Aktualizuj bierzącą komórkę',
row_odd : 'Aktualizuj nieparzyste komórki w tabeli',
row_even : 'Aktualizuj parzyste komórki w tabeli',
row_all : 'Aktualizuj wszystkie komórki w tabeli',
thead : 'Nagłówek tabeli',
tbody : 'Ciało tabeli',
tfoot : 'Stopka tabeli',
del : 'Usuń tabelę',
scope : 'Zasięg',
row : 'Wiersz',
col : 'Kolumna',
rowgroup : 'Grupa wiersza',
colgroup : 'Grupa kolumny',
missing_scope: 'Czy jesteś pewien, że chcesz kontynuować bez sprecyzowania zasięgu dla nagłówka tej tabeli? Bez tego, niektórzy użytkownicy mogą mieć problem ze zrozumieniem zawartości tej tabeli, jeżeli mają włączone jakieś ograniczenia w przeglądarkach.',
cellprops_delta_width : 70
});
