/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Author
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * First Release : November 26, 2005 - TinyMCE Version : 2.0RC4
 * Last Updated : November 20, 2006 - TinyMCE Version : 2.0.8
 */
tinyMCE.addToLang('table',{
general_tab : 'Geral',
advanced_tab : 'Avan&ccedil;ado',
general_props : 'Propriedades Gerais',
advanced_props : 'Propriedades Avan&ccedil;adas',
desc : 'Inserir uma nova tabela',
row_before_desc : 'Inserir uma linha antes',
row_after_desc : 'Inserir uma linha depois',
delete_row_desc : 'Apagar linha',
col_before_desc : 'Inserir uma coluna antes',
col_after_desc : 'Inserir uma coluna depois',
delete_col_desc : 'Remover coluna',
rowtype : 'Linhas na tabela parcial',
title : 'Inserir/Modificar Tabela',
width : 'Largura',
height : 'Altura',
cols : 'Colunas',
rows : 'Linhas',
cellspacing : 'Espa&ccedil;amento das c&eacute;lulas',
cellpadding : 'Margem interna',
border : 'Borda',
align : 'Alinhamento',
align_default : 'Padr&atilde;o',
align_left : 'Esquerda',
align_right : 'Direita',
align_middle : 'Centrado',
row_title : 'Propriedades das linha',
cell_title : 'Propriedades da c&eacute;lula',
cell_type : 'Tipo de c&eacute;lula',
row_desc : 'Propriedades das linhas',
cell_desc : 'Propriedades da c&eacute;lula',
valign : 'Alinhamento vertical',
align_top : 'Superior',
align_bottom : 'Inferior',
props_desc : 'Propriedades da tabela',
bordercolor : 'C&ocirc;r da borda',
bgcolor : 'C&ocirc;r do fundo',
merge_cells_title : 'Juntar c&eacute;lulas',
merge_cells_desc : 'Juntar c&eacute;lulas da tabela',
split_cells_title : 'Separar c&eacute;lulas',
split_cells_desc : 'Separar c&eacute;lulas',
cut_row_desc : 'Apagar linha',
copy_row_desc : 'Copiar linha',
paste_row_before_desc : 'Colar linha antes',
paste_row_after_desc : 'Colar linha depois',
id : 'Id',
style: 'Estilo',
langdir : 'Dire&ccedil;&atilde;o do texto',
langcode : 'C&oacute;digo do idioma',
mime : 'Tipo de MIME do objeto',
ltr : 'Esquerda para direita',
rtl : 'Direita para esquerda',
bgimage : 'Imagem de fundo',
summary : 'Sum&aacute;rio',
td : "Dados",
th : "Cabe&ccedil;alho",
cell_cell : 'Atulizar c&eacute;lula atual',
cell_row : 'Atualizar todas as c&eacute;dulas na linha',
cell_all : 'Atualizar todas as c&eacute;dulas da tabela',
row_row : 'Atualizar linha atual',
row_odd : 'Atualizar linhas &iacute;mpares na tabela',
row_even : 'Atualizar linhas pares na tabela',
row_all : 'Atualizar todas as linhas na tabela',
thead : 'Cabe&ccedil;alho da tabela',
tbody : 'Corpo da tabela',
tfoot : 'Rodap&eacute; da tabela',
del : 'Apagar tabela',
dir : 'Dire&ccedil;&atilde;o',
scope : 'Escopo',
row : 'Linha',
col : 'Coluna',
rowgroup : 'Grupo de linhas',
colgroup : 'Grupo de colunas',
missing_scope: 'Tem certeza que deseja continuar sem especificar um escopo para este c&eacute;lula de cabe&ccedil;alho. Sem isso talvez seja dif&iacute;cil para alguns usu&aacute;rios especiais entender ou conte&uacute;do ou visualizar a tabela.',
cellprops_delta_width : 55
});
