// RO lang variables

tinyMCE.addToLang('table',{
general_tab : 'General',
advanced_tab : 'Avansat',
general_props : 'Propriet&#259;&#355;i generale',
advanced_props : 'Propriet&#259;&#355;i avansate',
desc : 'Insereaz&#259; un tabel nou',
row_before_desc : 'Insereaz&#259; un r&#226;nd &#238;nainte',
row_after_desc : 'Insereaz&#259; un r&#226;nd dup&#259;',
delete_row_desc : '&#350;terge r&#226;nd',
col_before_desc : 'Insereaz&#259; coloan&#259; &#238;nainte',
col_after_desc : 'Insereaz&#259; colana dup&#259;',
delete_col_desc : '&#350;terge coloana',
rowtype : 'R&#226;nd &#238;n partea de tabel',
title : 'Inserare/Modificare tabel',
width : 'L&#259;&#355;ime',
height : '&#206;n&#259;l&#355;ime',
cols : 'Coloane',
rows : 'R&#226;nduri',
cellspacing : 'Spa&#355;iere celule',
cellpadding : 'Spa&#355;iu interior celule',
border : 'Margine',
align : 'Aliniament',
align_default : 'Implicit',
align_left : 'St&#226;nga',
align_right : 'Dreapta',
align_middle : 'Centru',
row_title : 'Propriet&#259;&#355;i r&#226;nd',
cell_title : 'Propriet&#259;&#355;i celul&#259;',
cell_type : 'Tip celul&#259;',
row_desc : 'Propriet&#259;&#355;i r&#226;nd',
cell_desc : 'Propriet&#259;&#355;i celul&#259;',
valign : 'Aliniament vertical',
align_top : 'Sus',
align_bottom : 'Jos',
props_desc : 'Propriet&#259;&#355;i tabel',
bordercolor : 'Culoare margine',
bgcolor : 'Culoare fundal',
merge_cells_title : 'Unire celule',
split_cells_desc : '&#206;mparte celulele',
merge_cells_desc : 'Une&#351;te celulele',
cut_row_desc : 'Decupeaz&#259; r&#226;nd',
copy_row_desc : 'Copiaz&#259; r&#226;nd',
paste_row_before_desc : 'Lipe&#351;te r&#226;nd &#238;nainte',
paste_row_after_desc : 'Lipe&#351;te r&#226;nd dup&#259;',
id : 'Id',
style: 'Stil',
langdir : 'Direc&#355;ia limbii',
langcode : 'Cod limb&#259;',
mime : 'Tip MIME &#355;int&#259;',
ltr : 'St&#226;nga la dreapta',
rtl : 'Dreapta la st&#226;nga',
bgimage : 'Imagine fundal',
summary : 'Sumar',
td : "Date",
th : "Antet",
cell_cell : 'Actualizeaz&#259; celula curent&#259;',
cell_row : 'Actualizeaz&#259; toate celulele din r&#226;nd',
cell_all : 'Actualizeaz&#259; toate celulele din tabel',
row_row : 'Actualizeaz&#259; r&#226;ndul curent',
row_odd : 'Actualizeaz&#259; r&#226;ndurile impare din tabel',
row_even : 'Actualizeaz&#259; r&#226;ndurile pare din tabel',
row_all : 'Actualizeaz&#259; toate r&#226;ndurile din tabel',
thead : 'Antet tabel',
tbody : 'Corp tabel',
tfoot : 'Subsol tabel',
del : '&#350;terge tabel',
scope : 'Domeniu',
row : 'R&#226;nd',
col : 'Coloan&#259;',
rowgroup : 'Grup r&#226;nduri',
colgroup : 'Grup coloane',
col_limit : 'Ai dep&#259;&#351;it num&#259;rul maxim de coloane, din {$cols}.',
row_limit : 'Ai dep&#259;&#351;it num&#259;rul maxim de r&#226;nduri, din {$rows}.',
cell_limit : 'Ai dep&#259;&#351;it num&#259;rul maxim de celule, din {$cells}.',
missing_scope: 'E&#351;ti sigur c&#259; vrei s&#259; continui f&#259;r&#259; s&#259; specifici un domeniu pentru antetul tabelului? F&#259;r&#259; acesta, este posibil ca utilizatorii cu invaliditate s&#259; nu &#238;n&#355;eleag&#259; datele afi&#351;ate sau con&#355;inutul tabelului.'
});
