/**
 * Slovak lang variables 
 * encoding: utf-8
 * 
 * @author Marián Zvalo marian.zvalo@student.umb.sk
 *    
 * $Id: sk.js,v 1.1 2006/02/28 20:56:44 spocke Exp $ 
 */  

tinyMCE.addToLang('',{
lang_class_name: 'CSS trieda',
lang_not_set: ' ',
insert_table_title : 'Vložiť/upraviť tabuľku',
insert_table_width : 'Šírka',
insert_table_height : 'Výška',
insert_table_cols : 'Stĺpce',
insert_table_rows : 'Riadky',
insert_table_cellspacing : 'Vonkajší okraj buniek',
insert_table_cellpadding : 'Vnutorný okraj buniek',
insert_table_border : 'Riadok',
insert_table_align : 'Zarovnanie',
insert_table_align_default : 'Východzie',
insert_table_align_left : 'Vľavo',
insert_table_align_right : 'Vpravo',
insert_table_align_middle : 'Na stred',
insert_table_class : 'Trieda',
table_row_title : 'Vlastnosti riadku',
table_cell_title : 'Vlastnosti bunky',
table_row_desc : 'Vlastnosti riadku',
table_cell_desc : 'Vlastnosti bunky',
insert_table_valign : 'Vertikálne zarovnávanie',
insert_table_align_top : 'Nahor',
insert_table_align_bottom : 'Dole',
table_props_desc : 'Vlastnosti tabuľky',
table_bordercolor : 'Farba rámčeku',
table_bgcolor : 'Farba pozadia',
table_merge_cells_title : 'Zlúčiť bunky',
table_split_cells_desc : 'Rozdeliť bunky',
table_merge_cells_desc : 'Zlúčiť bunky',
table_cut_row_desc : 'Vyňať riadok',
table_copy_row_desc : 'Kopírovať riadok',
table_paste_row_before_desc : 'Vložiť riadok pred',
table_paste_row_after_desc : 'Vložiť riadok za',
table_insert_desc : 'Vložiť tabuľku',
table_general_tab : 'Hlavné',
table_advanced_tab : 'Rozšírené',
table_general_props : 'Hlavné nastavenia',
table_advanced_props : 'Rozšírené nastavenia',
table_desc : 'Vložiť novú tabuľku',
table_row_before_desc : 'Vložiť riadok pred',
table_row_after_desc : 'Vložiť riadok za',
table_delete_row_desc : 'Odstrániť riadok',
table_col_before_desc : 'Vložiť stĺpec pred',
table_col_after_desc : 'Vložiť stĺpec za',
table_delete_col_desc : 'Odstrániť stĺpec',
table_rowtype : 'Row in table part',
table_title : 'Vložiť/Upraviť tabuľku',
table_width : 'Šírka',
table_height : 'Výška',
table_cols : 'Stĺpce',
table_rows : 'Riadky',
table_cellspacing : 'Medzera medzi bunkami',
table_cellpadding : 'Medzera medzi textom a okrajom bunky',
table_border : 'Rámik',
table_align : 'Zarovnanie',
table_align_default : 'Prednastavené',
table_align_left : 'Vľavo',
table_align_right : 'Vpravo',
table_align_middle : 'Centrovať',
table_row_title : 'Nastavenie riadku tabuľky',
table_cell_title : 'Nastavenie bunky tabuľky',
table_cell_type : 'Typ bunky',
table_row_desc : 'Nastavenie riadku tabuľky',
table_cell_desc : 'Nastavenie bunky tabuľky',
table_valign : 'Vertikálne zarovnanie',
table_align_top : 'Hore',
table_align_bottom : 'Dole',
table_props_desc : 'Nastavenia tabuľky',
table_bordercolor : 'Farba rámika',
table_bgcolor : 'Farba pozadia',
table_merge_cells_title : 'Zlúčiť bunky',
table_split_cells_desc : 'Rozdeliť bunky',
table_merge_cells_desc : 'Zlúčiť bunky',
table_cut_row_desc : 'Vystrihnúť riadok',
table_copy_row_desc : 'Kopírovať riadok',
table_paste_row_before_desc : 'Vložiť riadok pred',
table_paste_row_after_desc : 'Vložiť riadok za',
table_id : 'Id',
table_style: 'CSS Štýl',
table_langdir : 'Smer textu',
table_langcode : 'Kód jazyka',
table_mime : 'Target MIME type',
table_ltr : 'Z ľava do prava',
table_rtl : 'Z prava do ľava',
table_bgimage : 'Obrázok pozadia',
table_summary : 'Popis tabuľky',
table_td : "Dáta",
table_th : "Hlavička",
table_cell_cell : 'Upraviť aktuálnu bunku',
table_cell_row : 'Upraviť všetky bunky v riadku',
table_cell_all : 'Upraviť všetky bunky v tabuľke',
table_row_row : 'Upraviť aktuálny riadok',
table_row_odd : 'Upraviť nepárne riadky v tabuľke',
table_row_even : 'Upraviť párne ridky v tabuľke',
table_row_all : 'Upraviť všetky riadky v tabuľke',
table_thead : 'Hlavička tabuľky',
table_tbody : 'Telo tabuľky',
table_tfoot : 'Pätka tabuľky',
table_del : 'Zmazať tabuľku',
table_scope : 'Scope',
table_row : 'Riadok',
table_col : 'Stĺpec',
table_rowgroup : 'Skupina riadkov',
table_colgroup : 'Skupina stĺpcov',
table_missing_scope: 'Ste si istý(á), že chcete pokračovať bez špecifikovania SCOPE pre túto hlavičku tabuľky. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.'
});

