// UK lang variables

tinyMCE.addToLang('table',{
general_tab : 'Te pergjithshme',
advanced_tab : 'E avancuar',
general_props : 'Te dhena te pergjithshme',
advanced_props : 'Te dhena te pergjithshme',
desc : 'Nderfut nje tabele te re',
row_before_desc : 'Nderfut nje rresht perpara',
row_after_desc : 'Nderfut nje rresht nga pas',
delete_row_desc : 'DeleteFshi nje rresht',
col_before_desc : 'Nderfut nje kollone perpara',
col_after_desc : 'Nderfut nje kollone nga pas',
delete_col_desc : 'Fshi nje kollone',
rowtype : 'Rresht ne tabele',
title : 'Nderfut/Ndrysho tabelen',
width : 'Gjeresi',
height : 'Lartesi',
cols : 'Kollona',
rows : 'Rreshta',
cellspacing : 'Hapesira midis qelizave',
cellpadding : 'Largesia midis qelizave',
border : 'Kufiri',
align : 'Rreshtimi',
align_default : 'Paracktuar',
align_left : 'Majtas',
align_right : 'Djathas',
align_middle : 'Ne Mes',
row_title : 'Table row properties',
cell_title : 'Table cell properties',
cell_type : 'Cell type',
row_desc : 'Table row properties',
cell_desc : 'Table cell properties',
valign : 'Vertical alignment',
align_top : 'Top',
align_bottom : 'Bottom',
props_desc : 'Table properties',
bordercolor : 'Border color',
bgcolor : 'Background color',
merge_cells_title : 'Merge table cells',
split_cells_desc : 'Split table cells',
merge_cells_desc : 'Merge table cells',
cut_row_desc : 'Cut table row',
copy_row_desc : 'Copy table row',
paste_row_before_desc : 'Paste table row before',
paste_row_after_desc : 'Paste table row after',
id : 'Id',
style: 'Style',
langdir : 'Language direction',
langcode : 'Language code',
mime : 'Target MIME type',
ltr : 'Left to right',
rtl : 'Right to left',
bgimage : 'Background image',
summary : 'Summary',
td : "Data",
th : "Header",
cell_cell : 'Update current cell',
cell_row : 'Update all cells in row',
cell_all : 'Update all cells in table',
row_row : 'Update current row',
row_odd : 'Update odd rows in table',
row_even : 'Update even rows in table',
row_all : 'Update all rows in table',
thead : 'Table Head',
tbody : 'Table Body',
tfoot : 'Table Foot',
del : 'Delete table',
scope : 'Scope',
row : 'Row',
col : 'Col',
rowgroup : 'Row Group',
colgroup : 'Col Group',
col_limit : 'You\'ve exceeded the maximum number of columns of {$cols}.',
row_limit : 'You\'ve exceeded the maximum number of rows of {$rows}.',
cell_limit : 'You\'ve exceeded the maximum number of cells of {$cells}.',
missing_scope: 'Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.'
});