// SR lang variables

tinyMCE.addToLang('table',{
general_tab : 'Generalno',
advanced_tab : 'Napredno',
general_props : 'Generalna podešavanja',
advanced_props : 'Napredna podešavanja',
desc : 'Ubacuje novu tabelu',
row_before_desc : 'Ubacuje red pre',
row_after_desc : 'Ubacuje red posle',
delete_row_desc : 'Briše red',
col_before_desc : 'Ubacuje kolonu pre',
col_after_desc : 'Ubacuje kolonu posle',
delete_col_desc : 'Uklanja kolonu',
rowtype : 'red u delu tabele',
title : 'Ubacivanje/Menjanje tabele',
width : 'Širina',
height : 'Visina',
cols : 'Kolone',
rows : 'Redovi',
cellspacing : 'Cellspacing',
cellpadding : 'Cellpadding',
border : 'Granična linija',
align : 'Poravnanje',
align_default : 'Podrazumevano',
align_left : 'Levo',
align_right : 'Desno',
align_middle : 'Centar',
row_title : 'Podešavanja reda tabele',
cell_title : 'Podešavanja ćelije tabele',
cell_type : 'Tip ćelije',
row_desc : 'Podešavanja reda tabele',
cell_desc : 'Podešavanja ćelije tabele',
valign : 'Vertikalno poravnanje',
align_top : 'Vrh',
align_bottom : 'Dno',
props_desc : 'Podešavanje tabele',
bordercolor : 'Boja granične linije',
bgcolor : 'Pozadinska boja',
merge_cells_title : 'Spajanje ćelija tabele',
split_cells_desc : 'Deljenje ćelija tabele',
merge_cells_desc : 'Spajanje ćelija tabele',
cut_row_desc : 'Cut red tabele',
copy_row_desc : 'Kopiranje reda tabele',
paste_row_before_desc : 'Zalepite red tabele pre',
paste_row_after_desc : 'Zalepite red tabele posle',
id : 'Id',
style: 'Stil',
langdir : 'Jezički pravac',
langcode : 'Kod jezika',
mime : 'MIME tip mete',
ltr : 'Levo ka desno',
rtl : 'Desno ka levo',
bgimage : 'Pozadinska slika',
summary : 'Sažetak',
td : "Podaci",
th : "Zaglavlje",
cell_cell : 'Ažuriranje trenutne ćelije',
cell_row : 'Ažuriranje svih ćelija u redu',
cell_all : 'Ažuriranje svih ćelija tabele',
row_row : 'Ažuriranje trenutnog reda',
row_odd : 'Ažuriranje neparnih redova tabele',
row_even : 'Ažuriranje parnih redova tabele',
row_all : 'Ažuriranje svih redova tabele',
thead : 'Zaglavlje tabele',
tbody : 'Telo tabele',
tfoot : 'Donji deo tabele',
del : 'Brisanje tabele',
scope : 'Raspon',
row : 'Red',
col : 'Kol',
rowgroup : 'Grupa reda',
colgroup : 'Grupa kolone',
col_limit : 'Prešli ste maksimalni broj kolona od {$cols}.',
row_limit : 'Prešli ste maksimalni broj redova od {$rows}.',
cell_limit : 'Prešli ste maksimalni broj čelija od {$cells}.',
missing_scope: 'Da li ste sigurni da želite da nastavite bez postavljanja raspona zaglavlja tabele. Bez toga, neki korisnici će imati poteškoće u pregledu podataka u tabeli.'
});
