// UK lang variables

tinyMCE.addToLang('table',{
general_tab : 'Generella inställningar',
advanced_tab : 'Avancerade inställningar',
general_props : 'Generella inställningar',
advanced_props : 'Avancerade inställningar',
desc : 'Skapa ny tabell',
before_desc : 'Skapa rad före',
after_desc : 'Skapa rad efter',
row_before_desc : 'Skapa rad före',
row_after_desc : 'Skapa rad efter',
delete_row_desc : 'Ta bort rad',
col_before_desc : 'Skapa kolumn före',
col_after_desc : 'Skapa kolumn efter',
delete_col_desc : 'Ta bort kolumn',
rowtype : 'Radtyp',
title : 'Skapa/redigera ny tabell',
width : 'Bredd',
height : 'Höjd',
cols : 'Columner',
rows : 'Rader',
cellspacing : 'Cellmellanrum',
cellpadding : 'Cellutfyllnad',
border : 'Ram',
align : 'Justering',
align_default : 'Ingen',
align_left : 'Vänster',
align_right : 'Höger',
align_middle : 'Mitten',
row_title : 'Tabell radsinställningar',
cell_title : 'Tabell cellsinställningar',
cell_type : 'Celltyp',
row_desc : 'Tabellrads inställningar',
cell_desc : 'Tabellcells inställningar',
valign : 'Vertikal justering',
align_top : 'Toppen',
align_bottom : 'Botten',
props_desc : 'Tabellinställningar',
bordercolor : 'Ramfärg',
bgcolor : 'Bakgrundsfärg',
merge_cells_title : 'Sammanfoga tabellceller',
split_cells_desc : 'Dela upp tabellceller',
merge_cells_desc : 'Sammanfoga tabellceller',
cut_row_desc : 'Klipp ut tabellrad',
copy_row_desc : 'Kopiera tabellrad',
paste_row_before_desc : 'Klistra in tabellrad före',
paste_row_after_desc : 'Klistra in tabellrad efter',
id : 'Id',
style: 'Stil',
langdir : 'Skriftriktning',
langcode : 'Språkkod',
ltr : 'Vänster till höger',
rtl : 'Höger till vänster',
bgimage : 'Bakgrundsbild',
summary : 'Sammanfattning',
td : "Data",
th : "Huvud",
cell_cell : 'Uppdatera nuvarande cell',
cell_row : 'Uppdatera alla celler i raden',
cell_all : 'Uppdatera alla celler i tabellen',
row_row : 'Uppdatera nuvarande rad',
row_odd : 'Uppdatera udda rader i tabellen',
row_even : 'Uppdatera jämna rader i tabellen',
row_all : 'Uppdatera alla rader i tabellen',
thead : 'Tabellhuvud',
tbody : 'Tabellkropp',
tfoot : 'Tabellfot',
del : 'Ta bort tabell',
scope : 'Omfattning',
row : 'Rad',
col : 'Kolumn',
rowgroup : 'Radgrupp',
colgroup : 'Kolumngrupp',
col_limit : 'Du har angivit fler kolumner än vad som är tillåtet. Max är: {$cols}.',
row_limit : 'Du har angivit fler rader än vad som är tillåtet. Max är: {$rows}.',
cell_limit : 'Du har angivit fler celler än vad som är tillåtet. Max är: {$cells}.',
missing_scope: 'Är du säker på att du vill fortsätta utan att ange en omfattning, utan denna kan det bli svårt för handikappade att förstå tabellen.'
});
