// Vietnamese lang variables - Đỗ Xuân Tiến - tiendx2002@yahoo.com Việt hóa

tinyMCE.addToLang('table',{
general_tab : 'Chung',
advanced_tab : 'Nâng cao',
general_props : 'Thuộc tính chung',
advanced_props : 'Thuộc tính nâng cao',
desc : 'Thêm một bảng mới',
row_before_desc : 'Thêm hàng trước',
row_after_desc : 'Thêm hàng sau',
delete_row_desc : 'Xóa hàng',
col_before_desc : 'Thêm cột bên trái',
col_after_desc : 'Thêm cột bên phải',
delete_col_desc : 'Xóa cột',
rowtype : 'Hàng trong một phần bảng',
title : 'Thêm/Sửa bảng',
width : 'Độ rộng',
height : 'Chiều cao',
cols : 'Cột',
rows : 'Hàng',
cellspacing : 'Khoảng cách ô',
cellpadding : 'Căn lề ô',
border : 'Khung bao quanh',
align : 'Căn lề',
align_default : 'Mặc định',
align_left : 'Trái',
align_right : 'Phải',
align_middle : 'Giữa',
row_title : 'Thuộc tính hàng',
cell_title : 'Thuộc tính ô',
cell_type : 'Kiểu ô',
row_desc : 'Thuộc tính hàng',
cell_desc : 'Thuộc tính ô',
valign : 'Căn lề chiều dọc',
align_top : 'Trên cùng',
align_bottom : 'Dưới cùng',
props_desc : 'Thuộc tính bảng',
bordercolor : 'Màu khung',
bgcolor : 'Màu nền',
merge_cells_title : 'Trộn ô',
split_cells_desc : 'Tách ô',
merge_cells_desc : 'Trộn ô',
cut_row_desc : 'Cắt hàng của bảng',
copy_row_desc : 'Sao chép hàng của bảng',
paste_row_before_desc : 'Dán hàng lên trên',
paste_row_after_desc : 'Dán hàng xuống dưới',
id : 'Id',
style: 'Style',
langdir : 'Hướng ngôn ngữ',
langcode : 'Mã ngôn ngữ',
mime : 'Kiểu MIME mục tiêu',
ltr : 'Trái sang phải',
rtl : 'Phải sang trái',
bgimage : 'Ảnh nền',
summary : 'Tóm tắt',
td : "Dữ liệu",
th : "Tiêu đề",
cell_cell : 'Cập nhật ô hiện thời',
cell_row : 'Cập nhật tất cả các ô trong hàng',
cell_all : 'Cập nhật tất cả các ô trong bảng',
row_row : 'Cập nhật hàng hiện thời',
row_odd : 'Cập nhật các hàng lẻ trong bảng',
row_even : 'Cập nhật các hàng chẵn trong bảng',
row_all : 'Cập nhật tất cả các hàng trong bảng',
thead : 'Đầu bảng',
tbody : 'Thân bảng',
tfoot : 'Chân bảng',
del : 'Xóa bảng',
scope : 'Phạm vi',
row : 'Hàng',
col : 'Cột',
rowgroup : 'Nhóm hàng',
colgroup : 'Nhóm cột',
col_limit : 'Bạn đã chạm đến số tối đa cột của {$cols}.',
row_limit : 'Bạn đã chạm đến số tối đa hàng của {$rows}.',
cell_limit : 'Bạn đã chạm đến số tối đa ô của {$cells}.',
missing_scope: 'Bạn có chắc bạn muốn tiếp tục mà không cần xác định phạm vi cho ô tiêu đề bảng này? Nếu thiếu nó, có thể những người sử dụng khuyết thiếu sẽ khó có thể hiểu nội dung của dữ liệu trong bảng.'
});
