<?php

/**
 * ---------------------------------------------------------------------
 *
 * GLPI - Gestionnaire Libre de Parc Informatique
 *
 * http://glpi-project.org
 *
 * @copyright 2015-2026 Teclib' and contributors.
 * @licence   https://www.gnu.org/licenses/gpl-3.0.html
 *
 * ---------------------------------------------------------------------
 *
 * LICENSE
 *
 * This file is part of GLPI.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * ---------------------------------------------------------------------
 */

namespace tests\units\Glpi\Controller\Security;

use Glpi\Controller\Security\ReAuthController;
use Glpi\Security\ReAuth\ReAuthManager;
use Glpi\Tests\DbTestCase;
use PHPUnit\Framework\Attributes\Group;
use RuntimeException;
use Safe\DateTime;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

#[Group('reauth')]
final class ReAuthControllerTest extends DbTestCase
{
    /** Returns a 200 response containing the verify action URL. */
    public function testPromptRendersTheReAuthForm(): void
    {
        // --- arrange ---
        $this->login();
        $controller = new ReAuthController($this->getRouterMock());

        // --- act ---
        $response = $controller->prompt();

        // --- assert : the verify route generated by the router appears in the form ---
        $this->assertSame(200, $response->getStatusCode());
        $this->assertStringContainsString('/ReAuth/Verify', $response->getContent());
    }

    /** Sets glpi_reauth_until in session when the correct password is submitted. */
    public function testVerifyReAuthenticatesUser(): void
    {
        // --- arrange : logged-in user, not yet re-authenticated ---
        $this->login();
        unset($_SESSION['glpi_reauth_until']);
        $expected_reauth_until = (new DateTime($_SESSION['glpi_currenttime']))->getTimestamp() + ReAuthManager::REAUTH_DELAY_SECONDS;
        $controller = new ReAuthController($this->getRouterMock());

        // --- act : submit the correct password ---
        $response = $controller->verify(Request::create('/ReAuth/Verify', 'POST', ['user_input' => TU_PASS]));

        // --- assert : a fresh reauth window is opened ---
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame($expected_reauth_until, $_SESSION['glpi_reauth_until']);
    }

    /** Re-renders the prompt without setting glpi_reauth_until when a wrong password is submitted. */
    public function testVerifyDoesNotReAuthenticate(): void
    {
        // --- arrange : logged-in user, not yet re-authenticated ---
        $this->login();
        unset($_SESSION['glpi_reauth_until']);
        $controller = new ReAuthController($this->getRouterMock());

        // --- act : submit a wrong password ---
        $response = $controller->verify(Request::create('/ReAuth/Verify', 'POST', ['user_input' => 'wrong-password']));

        // --- assert : the prompt is re-rendered and no reauth window is opened ---
        $this->assertSame(200, $response->getStatusCode());
        $this->assertStringContainsString('/ReAuth/Verify', $response->getContent());
        $this->assertArrayNotHasKey('glpi_reauth_until', $_SESSION);
    }

    /**
     * prompt() calls buildTemplateContext() which calls $router->generate('reauth_verify')
     * to build the form action URL — the stub provides a fixed URL so the template renders.
     */
    private function getRouterMock(): UrlGeneratorInterface
    {
        $router = $this->createStub(UrlGeneratorInterface::class);
        $router->method('generate')->willReturn('/ReAuth/Verify');

        return $router;
    }
}
