tinyMCE.addI18n('tr.media_dlg',{
title:"T\u00FCmle\u015Fik medya ekle/dt",
general:"Genel",
advanced:"Geli\u015Fm",
file:"Dosya/URL",
list:"Liste",
size:"Boyutlar",
preview:"\u00D6nizle",
constrain_proportions:"Orant\u0131y\u0131 ",
type:"Tip",
id:"Id",
name:"\u0130s",
class_name:"S\u0131",
vspace:"Dik.Bo\u015Fl",
hspace:"Yty.Bo\u015Fl",
play:"Oto.\u00C7",
loop:"D\u00F6n",
menu:"Men\u00FC g\u00F6",
quality:"Kalite",
scale:"\u00D6l",
align:"Hizala",
salign:"SHizala",
wmode:"WMode",
bgcolor:"Arkaplan",
base:"Taban",
flashvars:"Flash de\u011F",
liveconnect:"SWLiveConnect",
autohref:"Oto.HREF",
cache:"\u00D6nbell",
hidden:"Gizli",
controller:"Kontrolc ",
kioskmode:"Kiosk modu",
playeveryframe:"Her \u00E7er\u00E7evey",
targetcache:"Hedef \u00F6nbell",
correction:"D\u00FCzeltmes",
enablejavascript:"JavaScript etkin",
starttime:"Ba\u015Flang\u0131c za",
endtime:"Biti\u015F zama",
href:"Href",
qtsrcchokespeed:"T\u0131kanma h",
target:"Hedef",
volume:"Ses d\u00FCze",
autostart:"Oto.ba\u015Fl",
enabled:"Etkin",
fullscreen:"Tam ekran",
invokeurls:"\u00C7a\u011Fr\u0131lacak U",
mute:"Sessiz",
stretchtofit:"S\u0131\u011Facak \u015Fekilde boyut",
windowlessvideo:"Penceresiz video",
balance:"Balans",
baseurl:"Taban URL",
captioningid:"Ba\u015Fl\u0131kland\u0131",
currentmarker:"\u015Eimdiki i\u015Far",
currentposition:"\u015Eimdiki kon",
defaultframe:"Varsay\u0131lan \u00E7e",
playcount:"\u00C7alma say",
rate:"Oran",
uimode:"UI Modu",
flash_options:"Flash se\u00E7enekle",
qt_options:"Quicktime se\u00E7enekle",
wmp_options:"Windows media player se\u00E7enekle",
rmp_options:"Real media player se\u00E7enekle",
shockwave_options:"Shockwave se\u00E7enekle",
autogotourl:"Otomatik gidilecek URL",
center:"Ortala",
imagestatus:"Resim durumu",
maintainaspect:"Orant\u0131y\u0131 ",
nojava:"Java yok",
prefetch:"\u00D6n-getir",
shuffle:"Kar\u0131",
console:"Konsol",
numloop:"D\u00F6ng\u00FC s",
controls:"Kontroller",
scriptcallbacks:"Script \u00E7a\u011Fr",
swstretchstyle:"Esnetme stili",
swstretchhalign:"Esnetme Y-Hiza",
swstretchvalign:"Esnetme D-Hiza",
sound:"Ses",
progress:"\u0130lerle",
qtsrc:"QT Kay.",
qt_stream_warn:"Ak\u0131nt\u0131 rtsp kaynaklar\u0131 geli\u015Fmi\u015F alt\u0131ndaki QT Kay. alan\u0131na girilmeli.\nSrc alan\u0131na ayr\u0131ca ak\u0131nt\u0131l\u0131 olmayan b",
align_top:"\u00DC",
align_right:"Sae",
align_bottom:"Alt",
align_left:"Sola",
align_center:"Ortala",
align_top_left:"Sol \u00DC",
align_top_right:"Sa\u011F ",
align_bottom_left:"Sol alt",
align_bottom_right:"Sa\u011F a",
flv_options:"Flash video se\u00E7enekle",
flv_scalemode:"Esnetme modu",
flv_buffer:"Tampon",
flv_startimage:"Ba\u015Flang\u0131\u00E7",
flv_starttime:"Ba\u015Flang\u0131\u00E7 ",
flv_defaultvolume:"Varsay\u0131lan ses d\u00FC",
flv_hiddengui:"Gizli GUI",
flv_autostart:"Otomatik ba\u015Fl",
flv_loop:"D\u00F6n",
flv_showscalemodes:"\u00D6l\u00E7ek modlar\u0131n",
flv_smoothvideo:"Video'yu yumu\u015F",
flv_jscallback:"JS \u00C7a\u011Fr"
});