// FR lang variables
// Modified by Motte, last updated 2006-03-23

tinyMCE.addToLang('fullpage',{
	title : 'Propri&eacute;t&eacute;s de la page',
	desc : 'Propri&eacute;t&eacute;s de la page',
	meta_tab : 'G&eacute;n&eacute;ral',
	appearance_tab : 'Apparence',
	advanced_tab : 'Avanc&eacute;',
	meta_props : 'Balises Meta',
	langprops : 'Langue et encodage',
	meta_title : 'Titre',
	meta_keywords : 'Mots cl&eacute;s',
	meta_description : 'Description',
	meta_robots : 'Robots',
	doctypes : 'Doctype',
	langcode : 'Code langue',
	langdir : 'Sens de l\'&eacute;criture',
	ltr : 'Gauche &agrave; droite',
	rtl : 'Droite &agrave; gauche',
	xml_pi : 'En-t&ecirc;te XML',
	encoding : 'Encodage',
	appearance_bgprops : 'Arri&egrave;re-plan',
	appearance_marginprops : 'Marges du document',
	appearance_linkprops : 'Couleur des liens',
	appearance_textprops : 'Propri&eacute;t&eacute;s du texte',
	bgcolor : 'Couleur de fond',
	bgimage : 'Image de fond',
	left_margin : 'Gauche',
	right_margin : 'Droite',
	top_margin : 'Haut',
	bottom_margin : 'Bas',
	text_color : 'Couleur du texte',
	font_size : 'Taille',
	font_face : 'Police',
	link_color : 'Couleur des liens',
	hover_color : 'Liens survol&eacute;s',
	visited_color : 'Liens visit&eacute;s',
	active_color : 'Liens actifs',
	textcolor : 'Couleur',
	fontsize : 'Taille',
	fontface : 'Police',
	meta_index_follow : 'Page actuelle et pages li&eacute;es',
	meta_index_nofollow : 'Page actuelle uniquement',
	meta_noindex_follow : 'Uniquement les pages li&eacute;es',
	meta_noindex_nofollow : 'Aucune indexation',
	appearance_style : 'Feuille de style et propri&eacute;t&eacute;s',
	stylesheet : 'Feuille de style',
	style : 'Style',
	author : 'Auteur',
	copyright : 'Copyright',
	add : 'Ajouter un &eacute;l&eacute;ment',
	remove : 'Retirer l\'&eacute;l&eacute;ment s&eacute;lectionn&eacute;',
	moveup : 'Vers le haut',
	movedown : 'Vers le bas',
	head_elements : 'En-t&ecirc;tes',
	info : 'Information',
	info_text : '',
	add_title : 'Balise Titre',
	add_meta : 'Balise Meta',
	add_script : 'Balise Script',
	add_style : 'Balise Style',
	add_link : 'Balise Lien',
	add_base : 'Balise Base',
	add_comment : 'Ajouter un commentaire',
	title_element : 'Balise Titre',
	script_element : 'Balise Script',
	style_element : 'Balise Style',
	base_element : 'Balise Base',
	link_element : 'Balise Lien',
	meta_element : 'Balise Meta',
	comment_element : 'Commentaire',
	src : 'Src',
	language : 'Langage',
	href : 'Href',
	target : 'Target',
	rel : 'Rel',
	type : 'Type',
	charset : 'Charset',
	defer : 'Defer',
	media : 'Media',
	properties : 'Propri&eacute;t&eacute;s',
	name : 'Nom',
	value : 'Valeur',
	content : 'Contenu',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'G&eacute;n&eacute;ral',
	advanced_props : 'Avanc&eacute;',
	delta_width : 0,
	delta_height : 0
});
