/**
 * ---------------------------------------------------------------------
 *
 * GLPI - Gestionnaire Libre de Parc Informatique
 *
 * http://glpi-project.org
 *
 * @copyright 2015-2025 Teclib' and contributors.
 * @licence   https://www.gnu.org/licenses/gpl-3.0.html
 *
 * ---------------------------------------------------------------------
 *
 * LICENSE
 *
 * This file is part of GLPI.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * ---------------------------------------------------------------------
 */

import { test, expect } from '../../fixtures/glpi_fixture';
import { GlpiPage } from '../../pages/GlpiPage';
import { Profiles } from '../../utils/Profiles';

test.afterEach(async ({ entity }) => {
    // Make sure we go back to the expected entity for this worker
    await entity.resetToDefaultWorkerEntity();
});

test('Can switch to full structure', async ({ page, profile }) => {
    // Go to any page
    await profile.set(Profiles.SuperAdmin);
    await page.goto('/front/preference.php');
    const glpi_page = new GlpiPage(page);

    // Make sure we are not already in full structure mode
    await expect(glpi_page.active_entity).not.toHaveText(
        'Root entity (full structure)'
    );

    // Open the entity selector and switch to full structure
    await glpi_page.doOpenEntitySelector();
    await glpi_page.doSwitchToAllEntities();

    // The current entity should now be in full structure mode
    await expect(glpi_page.active_entity).toHaveText(
        'Root entity (full structure)'
    );
});

test('Can search for entities', async ({ page, profile }) => {
    // Go to any page
    await profile.set(Profiles.SuperAdmin);
    await page.goto('/front/preference.php');
    const glpi_page = new GlpiPage(page);

    // Open the entity selector
    const entity_04 = glpi_page.getEntityFromTree("E2E worker entity 04");
    const entity_05 = glpi_page.getEntityFromTree("E2E worker entity 05");
    await glpi_page.doOpenEntitySelector();

    // By default, all entities are shown
    await expect(entity_04).toBeVisible();
    await expect(entity_05).toBeVisible();

    // We now execute a search
    await glpi_page.doSearchForEntity("entity 05");

    // Only one entity should be shown
    await expect(entity_05).toBeVisible();
    await expect(entity_04).toBeHidden(); // Does not match the search
});

test('Can fold/unfold tree', async ({ page, profile }) => {
    // Go to any page
    await page.goto('/front/preference.php');
    await profile.set(Profiles.SuperAdmin);
    const glpi_page = new GlpiPage(page);

    // Open the entity selector
    await glpi_page.doOpenEntitySelector();
    const root_entity = glpi_page.getEntityFromTree("Root entity");
    const child_entity = glpi_page.getEntityFromTree("E2E worker entity 05");

    // By default, all entities are shown
    await expect(root_entity).toBeVisible();
    await expect(child_entity).toBeVisible();

    // Fold at the root entity level
    // We can't use a proper locator because this code is generated by a JS lib
    // so we have no control over it.
    // eslint-disable-next-line playwright/no-raw-locators
    await page.locator('.fancytree-expander').first().click();

    // Now only the root entity should be shown
    await expect(child_entity).toBeHidden();
    await expect(root_entity).toBeVisible();
});

test('Can switch to another entity with sub entities', async ({ page, profile }) => {
    // Go to any page
    await page.goto('/front/preference.php');
    await profile.set(Profiles.SuperAdmin);
    const glpi_page = new GlpiPage(page);

    // Open the entity selector
    await glpi_page.doOpenEntitySelector();

    // By default, we are not on root with sub entities enabled
    await expect(glpi_page.active_entity).not.toHaveText(
        'Root entity (tree structure)'
    );

    // Open the entity selector
    await glpi_page.doOpenEntitySelector();
    await glpi_page.doSwitchToEntityWithRecursion("Root entity");

    // We are now root with sub entities enabled
    await expect(glpi_page.active_entity).toHaveText(
        'Root entity (tree structure)'
    );
});

test('Can switch to another entity without sub entities', async ({ page, profile }) => {
    // Go to any page
    await page.goto('/front/preference.php');
    await profile.set(Profiles.SuperAdmin);
    const glpi_page = new GlpiPage(page);

    // Open the entity selector
    await glpi_page.doOpenEntitySelector();

    // By default, we are not on root with sub entities disabled
    await expect(glpi_page.active_entity).not.toHaveText(
        'Root entity'
    );

    // Open the entity selector
    await glpi_page.doOpenEntitySelector();
    await glpi_page.doSwitchToEntityWithoutRecursion("Root entity");

    // We are now root with sub entities disabled
    await expect(glpi_page.active_entity).toHaveText(
        'Root entity'
    );
});
