services:
  app:
    container_name: "glpi-test-app-e2e"
    image: "ghcr.io/glpi-project/${PHP_IMAGE:-githubactions-php-apache:8.3}"
    environment:
      CODE_COVERAGE: "${CODE_COVERAGE:-false}"
      CI: true # Will be used to alter some configuration when running on github vs locally.
      PLAYWRIGHT_BROWSERS_PATH: /opt/pw-browsers # Custom browser path to prevent some rights issues.
      GLPI_BASE_URL: http://localhost:80 # Default URL for GLPI. Used for e2e tests.
      PHP: php
      GLPI_ENVIRONMENT_TYPE: e2e_testing
    volumes:
      - type: "bind"
        source: "${APPLICATION_ROOT}"
        target: "/var/www/glpi"
      - type: "bind"
        source: "${APP_CONTAINER_HOME}"
        target: "/home/www-data"
