<?php

/**
 * ---------------------------------------------------------------------
 *
 * GLPI - Gestionnaire Libre de Parc Informatique
 *
 * http://glpi-project.org
 *
 * @copyright 2015-2026 Teclib' and contributors.
 * @licence   https://www.gnu.org/licenses/gpl-3.0.html
 *
 * ---------------------------------------------------------------------
 *
 * LICENSE
 *
 * This file is part of GLPI.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * ---------------------------------------------------------------------
 */

namespace Glpi\Api\HL\Search;

use Glpi\Api\HL\APIException;
use Glpi\Api\HL\Search;
use Glpi\DBAL\QueryExpression;
use Glpi\Toolbox\ArrayPathAccessor;

/**
 * Utility class to handle the generation of cursor tokens and conversion of tokens to criteria.
 */
final class CursorPagination
{
    public const TYPE_PREVIOUS = 'previous';
    public const TYPE_NEXT = 'next';

    /**
     * Generates a token that can be used for previous or next page retrieval based on the edge result (first or last) of the current and sort/order
     * @param self::TYPE_* $type The type of token to generate, either 'next' or 'previous'.
     * The cursor type is saved in the token so the API knows how to handle results.
     * With a 'next' token the API retrieves result normally, but with 'previous' tokens the API needs to reverse the criteria to read backwards, then reverse the results back to the normal order.
     * @param array $edge_result The result from the edge (first or last) of the current page's results
     * @param array<string, 'ASC'|'DESC'> $sort_order The sort order used for the current search where the keys are the property names and the values are the sort direction ASC or DESC
     * @return string A URL-safe base64 encoded JSON string token that can be used for pagination in subsequent requests
     */
    public static function generateCursorToken(string $type, array $edge_result, array $sort_order): string
    {
        $cursor_params = [
            'type' => $type,
            'sort' => [],
        ];
        foreach ($sort_order as $property => $direction) {
            $cursor_params['sort'][] = [
                'field' => $property,
                'direction' => $direction === 'DESC' ? 'DESC' : 'ASC',
                'value' => ArrayPathAccessor::getElementByArrayPath($edge_result, $property),
            ];
        }
        return rtrim(strtr(base64_encode(json_encode($cursor_params, JSON_THROW_ON_ERROR)), '+/', '-_'), '=');
    }

    /**
     * Decode and validate a cursor token.
     * @param string $token The token generated by {@link self::generateCursorToken()}
     * @return array{type: self::TYPE_*, sort: list<array{field: string, direction: 'ASC'|'DESC', value: scalar|null}>}
     * @throws APIException If the token is invalid
     */
    public static function decodeCursorToken(string $token): array
    {
        $fn_invalid = static fn(string $reason) => new APIException(
            message: 'Invalid cursor token: ' . $reason,
            user_message: 'Invalid cursor token: ' . $reason,
            code: 400,
        );

        $json = base64_decode(strtr($token, '-_', '+/'), true);
        if ($json === false) {
            throw $fn_invalid('not valid base64');
        }
        try {
            $cursor_params = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $e) {
            throw $fn_invalid($e->getMessage());
        }
        if (
            !is_array($cursor_params)
            || !in_array($cursor_params['type'] ?? null, [self::TYPE_PREVIOUS, self::TYPE_NEXT], true)
            || !is_array($cursor_params['sort'] ?? null)
            || $cursor_params['sort'] === []
        ) {
            throw $fn_invalid('malformed token');
        }
        foreach ($cursor_params['sort'] as $sort) {
            if (
                !is_array($sort)
                || !is_string($sort['field'] ?? null)
                || !in_array($sort['direction'] ?? null, ['ASC', 'DESC'], true)
                || !array_key_exists('value', $sort)
                || (!is_scalar($sort['value']) && $sort['value'] !== null)
            ) {
                throw $fn_invalid('malformed token');
            }
        }
        return $cursor_params;
    }

    /**
     * @param array $cursor_params Cursor parameters returned by {@link self::decodeCursorToken()}
     * @param Search $search The search the criteria is for
     * @return array WHERE criteria to fetch the records after (or before for a 'previous' cursor) the cursor position
     * @throws APIException
     */
    public static function getCriteriaFromCursor(array $cursor_params, Search $search): array
    {
        $cursor_type = $cursor_params['type'];

        // The cursor must have been generated for the same sort order as the current request. Otherwise, the position is meaningless.
        $expected_sort = $search->getSortOrder(true);
        $cursor_sort = array_column($cursor_params['sort'], 'direction', 'field');
        if ($cursor_sort !== $expected_sort) {
            throw new APIException(
                message: 'The cursor does not match the requested sort order',
                user_message: 'The cursor does not match the requested sort order',
                code: 400,
            );
        }

        $db = $search->getDBRead();
        // Build a lexicographic comparison: (a > va) OR (a = va AND b > vb) OR (a = va AND b = vb AND c > vc)...
        // A row value comparison like (a, b) > (va, vb) would be shorter, but it cannot handle mixed directions properly and gives NULL if any value is NULL.
        // MySQL considers NULL lower than any other value, so NULLs come first in ASC sorts and last in DESC sorts.
        $or_conditions = [];
        $equal_conditions = [];
        foreach ($cursor_params['sort'] as $field) {
            $sql_field = $db::quoteName($search->getSQLFieldForProperty($field['field']));
            $direction = $field['direction'];
            if ($cursor_type === self::TYPE_PREVIOUS) {
                // Reading backwards is the same as reading forwards with the reversed sort
                $direction = $direction === 'ASC' ? 'DESC' : 'ASC';
            }
            if ($field['value'] === null) {
                // Only non-NULL values come after NULL in ASC sorts. Nothing comes after NULL in DESC sorts.
                $after_condition = $direction === 'ASC' ? "{$sql_field} IS NOT NULL" : null;
                $equal_condition = "{$sql_field} IS NULL";
            } else {
                $value = $db::quoteValue($field['value']);
                $after_condition = $direction === 'ASC'
                    ? "{$sql_field} > {$value}"
                    : "({$sql_field} < {$value} OR {$sql_field} IS NULL)";
                $equal_condition = "{$sql_field} = {$value}";
            }
            if ($after_condition !== null) {
                $or_conditions[] = '(' . implode(' AND ', [...$equal_conditions, $after_condition]) . ')';
            }
            $equal_conditions[] = $equal_condition;
        }
        if ($or_conditions === []) {
            // Nothing can come after the cursor position
            return [new QueryExpression('0 = 1')];
        }
        return [new QueryExpression('(' . implode(' OR ', $or_conditions) . ')')];
    }
}
