<?php
/*
 * @version $Id$
 -------------------------------------------------------------------------
 GLPI - Gestionnaire Libre de Parc Informatique
 Copyright (C) 2003-2006 by the INDEPNET Development Team.

 http://indepnet.net/   http://glpi-project.org
 -------------------------------------------------------------------------

 LICENSE

 This file is part of GLPI.

 GLPI is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 GLPI is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with GLPI; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 --------------------------------------------------------------------------
 */

// ----------------------------------------------------------------------
// Original Author of file: Julien Dombre
// Purpose of file:
// ----------------------------------------------------------------------


$SEARCH_OPTION=array(
COMPUTER_TYPE => array(	
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_computers", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
"meta" => 1,
),
	2 => array(	"table" => "glpi_computers", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
"meta" => 1,
),
	3 => array(	"table" => "glpi_dropdown_locations", 
"field" => "completename",
"linkfield"=>"location",
"name" => $lang["common"][15],
"meta" => 2,
),
	4 => array(	"table" => "glpi_type_computers", 
"field" => "name",
"linkfield"=>"type",
"name" => $lang["common"][17],
"meta" => 2,
),
	5 => array(	"table" => "glpi_dropdown_model", 
	"field" => "name",
	"linkfield"=>"model",
	"name" => $lang["common"][22],
	"meta" => 2,
  ),
	31 => array(	"table" => "glpi_dropdown_state", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["state"][0],
	"meta" => 0,
   ),
	6 => array(	"table" => "glpi_dropdown_os", 
	"field" => "name",
	"linkfield"=>"os",
	"name" => $lang["computers"][9],
	"meta" => 2,
  ),
	40 => array(	"table" => "glpi_dropdown_os_version", 
	"field" => "name",
	"linkfield"=>"os_version",
	"name" => $lang["computers"][52],
	"meta" => 2,
   ),
	41 => array(	"table" => "glpi_dropdown_os_sp", 
	"field" => "name",
	"linkfield"=>"os_sp",
	"name" => $lang["computers"][53],
	"meta" => 2,
   ),
	42 => array(	"table" => "glpi_dropdown_auto_update", 
	"field" => "name",
	"linkfield"=>"auto_update",
	"name" => $lang["computers"][51],
	"meta" => 2,
   ),
	8 => array(	"table" => "glpi_computers", 
	"field" => "serial",
	"linkfield"=>"serial",
	"name" => $lang["common"][19],
	"meta" => 1,
  ),
	9 => array(	"table" => "glpi_computers", 
	"field" => "otherserial",
	"linkfield"=>"otherserial",
	"name" => $lang["common"][20],
	"meta" => 1,
  ),
	16 => array(	"table" => "glpi_computers", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
	"meta" => 1,
   ),
	17 => array(	"table" => "glpi_computers", 
	"field" => "contact",
	"linkfield"=>"contact",
	"name" => $lang["common"][18],
	"meta" => 1,
   ),
	18 => array(	"table" => "glpi_computers", 
	"field" => "contact_num",
	"linkfield"=>"contact_num",
	"name" => $lang["common"][21],
	"meta" => 1,
   ),
	70 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"FK_users",
	"name" => $lang["common"][34],
	"meta" => 0,
   ),
	71 => array(	"table" => "glpi_groups", 
	"field" => "name",
	"linkfield"=>"FK_groups",
	"name" => $lang["common"][35],
	"meta" => 0,
   ),
	19 => array(	"table" => "glpi_computers", 
	"field" => "date_mod",
	"linkfield"=>"",
	"name" => $lang["common"][26],
	"meta" => 1,
   ),
	32 => array(	"table" => "glpi_dropdown_network", 
	"field" => "name",
	"linkfield"=>"network",
	"name" => $lang["setup"][88],
	"meta" => 0,
   ),
	33 => array(	"table" => "glpi_dropdown_domain", 
	"field" => "name",
	"linkfield"=>"domain",
	"name" => $lang["setup"][89],
	"meta" => 0,
   ),
	23 => array(	"table" => "glpi_enterprises", 
	"field" => "name",
	"linkfield"=>"FK_glpi_enterprise",
	"name" => $lang["common"][5],
	"meta" => 2,
   ),
	24 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"tech_num",
	"name" => $lang["common"][10],
	"meta" => 0,
   ),
	"periph" => $lang["devices"][10],
	7 => array(	"table" => "glpi_device_processor", 
	"field" => "designation",
	"linkfield"=>"",
	"name" => $lang["computers"][21],
	"meta" => 1,
  ),
	36 => array(	"table" => "glpi_device_processor", 
	"field" => "specif_default",
	"linkfield"=>"",
	"name" => $lang["computers"][21]." ".$lang["setup"][35],
	"meta" => 1,
   ),
	10 => array(	"table" => "glpi_device_ram", 
	"field" => "designation",
	"linkfield"=>"",
	"name" => $lang["computers"][23],
	"meta" => 1,
   ),
	35 => array(	"table" => "glpi_device_ram", 
	"field" => "specif_default",
	"linkfield"=>"",
	"name" => $lang["computers"][24],
	"meta" => 1,
   ),
	11 => array(	"table" => "glpi_device_iface", 
	"field" => "designation",
	"linkfield"=>"",
	"name" => $lang["setup"][9],
	"meta" => 1,
   ),
	12 => array(	"table" => "glpi_device_sndcard", 
	"field" => "designation",
	"linkfield"=>"",
	"name" => $lang["devices"][7],
	"meta" => 1,
   ),
	13 => array(	"table" => "glpi_device_gfxcard", 
	"field" => "designation",
	"linkfield"=>"",
	"name" => $lang["devices"][2],
	"meta" => 1,
   ),
	14 => array(	"table" => "glpi_device_moboard", 
	"field" => "designation",
	"linkfield"=>"",
	"name" => $lang["devices"][5],
	"meta" => 1,
   ),
	15 => array(	"table" => "glpi_device_hdd", 
	"field" => "designation",
	"linkfield"=>"",
	"name" => $lang["computers"][36],
	"meta" => 1,
   ),
	34 => array(	"table" => "glpi_device_hdd", 
	"field" => "specif_default",
	"linkfield"=>"",
	"name" => $lang["computers"][25],
	"meta" => 1,
   ),
	"network" => $lang["setup"][88],
	20 => array(	"table" => "glpi_networking_ports", 
	"field" => "ifaddr",
	"linkfield"=>"",
	"name" => $lang["networking"][14],
	"meta" => 0,
   ),
	21 => array(	"table" => "glpi_networking_ports", 
	"field" => "ifmac",
	"linkfield"=>"",
	"name" => $lang["networking"][15],
	"meta" => 0,
   ),
	22 => array(	"table" => "glpi_dropdown_netpoint", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["networking"][51],
	"meta" => 0,
   ),
	"tracking" => $lang["setup"][143],
	60 => array(	"table" => "glpi_tracking", 
	"field" => "count",
	"linkfield"=>"",
	"name" => $lang["stats"][13],
	"meta" => 0,
   ),
	"financial"=>$lang["financial"][3],
	29 => array(	"table" => "glpi_contracts", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["common"][16]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	30 => array(	"table" => "glpi_contracts", 
	"field" => "num",
	"linkfield"=>"",
	"name" => $lang["financial"][4]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	25 => array(	"table" => "glpi_infocoms", 
	"field" => "num_immo",
	"linkfield"=>"",
	"name" => $lang["financial"][20],
	"meta" => 0,
   ),
	26 => array(	"table" => "glpi_infocoms", 
	"field" => "num_commande",
	"linkfield"=>"",
	"name" => $lang["financial"][18],
	"meta" => 0,
   ),
	27 => array(	"table" => "glpi_infocoms", 
	"field" => "bon_livraison",
	"linkfield"=>"",
	"name" => $lang["financial"][19],
	"meta" => 0,
   ),
	28 => array(	"table" => "glpi_infocoms", 
	"field" => "facture",
	"linkfield"=>"",
	"name" => $lang["financial"][82],
	"meta" => 0,
   ),
	37 => array(	"table" => "glpi_infocoms",
	"field" => "buy_date",
	"linkfield"=>"",
	"name" => $lang["financial"][14],
	"meta" => 0,
   ),
	38 => array(    "table" => "glpi_infocoms",
	"field" => "use_date",
	"linkfield"=>"",
	"name" => $lang["financial"][76],
	"meta" => 0,
   ),
	50 => array(	"table" => "glpi_dropdown_budget", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][87],
	"meta" => 0,
   ),
	51 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_duration",
	"linkfield"=>"",
	"name" => $lang["financial"][15],
	"meta" => 0,
   ),
	52 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_info",
	"linkfield"=>"",
	"name" => $lang["financial"][16],
	"meta" => 0,
   ),
	53 => array(	"table" => "glpi_enterprises_infocoms", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][3]." ".$lang["financial"][26],
	"meta" => 0,
   ),
	54 => array(	"table" => "glpi_infocoms", 
	"field" => "value",
	"linkfield"=>"",
	"name" => $lang["financial"][21],
	"meta" => 0,
   ),
	55 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_value",
	"linkfield"=>"",
	"name" => $lang["financial"][78],
	"meta" => 0,
   ),
	56 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_time",
	"linkfield"=>"",
	"name" => $lang["financial"][23],
	"meta" => 0,
   ),
	57 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_type",
	"linkfield"=>"",
	"name" => $lang["financial"][22],
	"meta" => 0,
   ),
	58 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_coeff",
	"linkfield"=>"",
	"name" => $lang["financial"][77],
	"meta" => 0,
   ),
	"ocsng" => $lang["Menu"][33],
	100 => array(	"table" => "glpi_computers", 
	"field" => "ocs_import",
	"linkfield"=>"",
	"name" => $lang["ocsng"][7],
	"meta" => 0,
    ),
	101 => array(	"table" => "glpi_ocs_link", 
	"field" => "auto_update",
	"linkfield"=>"",
	"name" => $lang["ocsng"][6]." ".$lang["Menu"][33],
	"meta" => 0,
    ),
	102 => array(	"table" => "glpi_ocs_link", 
	"field" => "last_update",
	"linkfield"=>"",
	"name" => $lang["ocsng"][13],
	"meta" => 0,
    ),
	103 => array(	"table" => "glpi_ocs_link", 
	"field" => "last_ocs_update",
	"linkfield"=>"",
	"name" => $lang["ocsng"][14],
	"meta" => 0,
    ),
	),
	NETWORKING_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_networking", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
"meta" => 1,
),
	2 => array(	"table" => "glpi_networking", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
"meta" => 1,
),
	3 => array(	"table" => "glpi_dropdown_locations", 
"field" => "completename",
"linkfield"=>"location",
"name" => $lang["common"][15],
"meta" => 2,
),
	4 => array(	"table" => "glpi_type_networking", 
"field" => "name",
"linkfield"=>"type",
"name" => $lang["common"][17],
"meta" => 2,
),
	40 => array(	"table" => "glpi_dropdown_model_networking", 
	"field" => "name",
	"linkfield"=>"model",
	"name" => $lang["common"][22],
	"meta" => 2,
   ),
	31 => array(	"table" => "glpi_dropdown_state", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["state"][0],
	"meta" => 0,
   ),
	5 => array(	"table" => "glpi_networking", 
	"field" => "serial",
	"linkfield"=>"serial",
	"name" => $lang["common"][19],
	"meta" => 1,
  ),
	6 => array(	"table" => "glpi_networking", 
	"field" => "otherserial",
	"linkfield"=>"otherserial",
	"name" => $lang["common"][20],
	"meta" => 1,
  ),
	7 => array(	"table" => "glpi_networking", 
	"field" => "contact",
	"linkfield"=>"contact",
	"name" => $lang["common"][18],
	"meta" => 1,
  ),
	8 => array(	"table" => "glpi_networking", 
	"field" => "contact_num",
	"linkfield"=>"contact_num",
	"name" => $lang["common"][21],
	"meta" => 1,
  ),
	70 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"FK_users",
	"name" => $lang["common"][34],
	"meta" => 0,
   ),
	71 => array(	"table" => "glpi_groups", 
	"field" => "name",
	"linkfield"=>"FK_groups",
	"name" => $lang["common"][35],
	"meta" => 0,
   ),
	9 => array(	"table" => "glpi_networking", 
	"field" => "date_mod",
	"linkfield"=>"",
	"name" => $lang["common"][26],
	"meta" => 1,
  ),
	10 => array(	"table" => "glpi_networking", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
	"meta" => 1,
   ),
	11 => array(	"table" => "glpi_dropdown_firmware", 
	"field" => "name",
	"linkfield"=>"firmware",
	"name" => $lang["networking"][49],
	"meta" => 2,
   ),
	12 => array(	"table" => "glpi_networking", 
	"field" => "ifaddr",
	"linkfield"=>"ifaddr",
	"name" => $lang["networking"][14]." ".$lang["networking"][12],
	"meta" => 1,
   ),
	13 => array(	"table" => "glpi_networking", 
	"field" => "ifmac",
	"linkfield"=>"ifmac",
	"name" => $lang["networking"][15]." ".$lang["networking"][12],
	"meta" => 1,
   ),	
	32 => array(	"table" => "glpi_dropdown_network", 
	"field" => "name",
	"linkfield"=>"network",
	"name" => $lang["setup"][88],
	"meta" => 0,
   ),
	33 => array(	"table" => "glpi_dropdown_domain", 
	"field" => "name",
	"linkfield"=>"domain",
	"name" => $lang["setup"][89],
	"meta" => 0,
   ),
	23 => array(	"table" => "glpi_enterprises", 
	"field" => "name",
	"linkfield"=>"FK_glpi_enterprise",
	"name" => $lang["common"][5],
	"meta" => 2,
   ),
	24 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"tech_num",
	"name" => $lang["common"][10],
	"meta" => 0,
   ),
	"network" => $lang["setup"][88],
	20 => array(	"table" => "glpi_networking_ports", 
	"field" => "ifaddr",
	"linkfield"=>"",
	"name" => $lang["networking"][14],
	"meta" => 0,
   ),
	21 => array(	"table" => "glpi_networking_ports", 
	"field" => "ifmac",
	"linkfield"=>"",
	"name" => $lang["networking"][15],
	"meta" => 0,
   ),
	22 => array(	"table" => "glpi_dropdown_netpoint", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["networking"][51],
	"meta" => 0,
   ),
	"tracking" => $lang["setup"][143],
	60 => array(	"table" => "glpi_tracking", 
	"field" => "count",
	"linkfield"=>"",
	"name" => $lang["stats"][13],
	"meta" => 0,
   ),
	"financial"=>$lang["financial"][3],
	29 => array(	"table" => "glpi_contracts", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["common"][16]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	30 => array(	"table" => "glpi_contracts", 
	"field" => "num",
	"linkfield"=>"",
	"name" => $lang["financial"][4]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	25 => array(	"table" => "glpi_infocoms", 
	"field" => "num_immo",
	"linkfield"=>"",
	"name" => $lang["financial"][20],
	"meta" => 0,
   ),
	26 => array(	"table" => "glpi_infocoms", 
	"field" => "num_commande",
	"linkfield"=>"",
	"name" => $lang["financial"][18],
	"meta" => 0,
   ),
	27 => array(	"table" => "glpi_infocoms", 
	"field" => "bon_livraison",
	"linkfield"=>"",
	"name" => $lang["financial"][19],
	"meta" => 0,
   ),
	28 => array(	"table" => "glpi_infocoms", 
	"field" => "facture",
	"linkfield"=>"",
	"name" => $lang["financial"][82],
	"meta" => 0,
   ),
	37 => array(	"table" => "glpi_infocoms",
	"field" => "buy_date",
	"linkfield"=>"",
	"name" => $lang["financial"][14],
	"meta" => 0,
   ),
	38 => array(    "table" => "glpi_infocoms",
	"field" => "use_date",
	"linkfield"=>"",
	"name" => $lang["financial"][76],
	"meta" => 0,
   ),
	50 => array(	"table" => "glpi_dropdown_budget", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][87],
	"meta" => 0,
   ),
	51 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_duration",
	"linkfield"=>"",
	"name" => $lang["financial"][15],
	"meta" => 0,
   ),
	52 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_info",
	"linkfield"=>"",
	"name" => $lang["financial"][16],
	"meta" => 0,
   ),
	53 => array(	"table" => "glpi_enterprises_infocoms", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][3]." ".$lang["financial"][26],
	"meta" => 0,
   ),
	54 => array(	"table" => "glpi_infocoms", 
	"field" => "value",
	"linkfield"=>"",
	"name" => $lang["financial"][21],
	"meta" => 0,
   ),
	55 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_value",
	"linkfield"=>"",
	"name" => $lang["financial"][78],
	"meta" => 0,
   ),
	56 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_time",
	"linkfield"=>"",
	"name" => $lang["financial"][23],
	"meta" => 0,
   ),
	57 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_type",
	"linkfield"=>"",
	"name" => $lang["financial"][22],
	"meta" => 0,
   ),
	58 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_coeff",
	"linkfield"=>"",
	"name" => $lang["financial"][77],
	"meta" => 0,
   ),
	),
	PRINTER_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_printers", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
"meta" => 1,
),
	2 => array(	"table" => "glpi_printers", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
"meta" => 1,
),
	3 => array(	"table" => "glpi_dropdown_locations", 
"field" => "completename",
"linkfield"=>"location",
"name" => $lang["common"][15],
"meta" => 2,
),
	4 => array(	"table" => "glpi_type_printers", 
"field" => "name",
"linkfield"=>"type",
"name" => $lang["common"][17],
"meta" => 2,
),
	40 => array(	"table" => "glpi_dropdown_model_printers", 
	"field" => "name",
	"linkfield"=>"model",
	"name" => $lang["common"][22],
	"meta" => 2,
   ),
	31 => array(	"table" => "glpi_dropdown_state", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["state"][0],
	"meta" => 0,
   ),
	5 => array(	"table" => "glpi_printers", 
	"field" => "serial",
	"linkfield"=>"serial",
	"name" => $lang["common"][19],
	"meta" => 1,
  ),
	6 => array(	"table" => "glpi_printers", 
	"field" => "otherserial",
	"linkfield"=>"otherserial",
	"name" => $lang["common"][20],
	"meta" => 1,
  ),
	7 => array(	"table" => "glpi_printers", 
	"field" => "contact",
	"linkfield"=>"contact",
	"name" => $lang["printers"][8],
	"meta" => 1,
  ),
	8 => array(	"table" => "glpi_printers", 
	"field" => "contact_num",
	"linkfield"=>"contact_num",
	"name" => $lang["common"][21],
	"meta" => 1,
  ),
	70 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"FK_users",
	"name" => $lang["common"][34],
	"meta" => 0,
   ),
	71 => array(	"table" => "glpi_groups", 
	"field" => "name",
	"linkfield"=>"FK_groups",
	"name" => $lang["common"][35],
	"meta" => 0,
   ),
	9 => array(	"table" => "glpi_printers", 
	"field" => "date_mod",
	"linkfield"=>"",
	"name" => $lang["common"][26],
	"meta" => 1,
  ),
	10 => array(	"table" => "glpi_printers", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
	"meta" => 1,
   ),
	32 => array(	"table" => "glpi_dropdown_network", 
	"field" => "name",
	"linkfield"=>"network",
	"name" => $lang["setup"][88],
	"meta" => 0,
   ),
	33 => array(	"table" => "glpi_dropdown_domain", 
	"field" => "name",
	"linkfield"=>"domain",
	"name" => $lang["setup"][89],
	"meta" => 0,
   ),
	23 => array(	"table" => "glpi_enterprises", 
	"field" => "name",
	"linkfield"=>"FK_glpi_enterprise",
	"name" => $lang["common"][5],
	"meta" => 2,
   ),
	24 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"tech_num",
	"name" => $lang["common"][10],
	"meta" => 0,
   ),
	"network" => $lang["setup"][88],
	20 => array(	"table" => "glpi_networking_ports", 
	"field" => "ifaddr",
	"linkfield"=>"",
	"name" => $lang["networking"][14],
	"meta" => 0,
   ),
	21 => array(	"table" => "glpi_networking_ports", 
	"field" => "ifmac",
	"linkfield"=>"",
	"name" => $lang["networking"][15],
	"meta" => 0,
   ),
	22 => array(	"table" => "glpi_dropdown_netpoint", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["networking"][51],
	"meta" => 0,
   ),
	"tracking" => $lang["setup"][143],
	60 => array(	"table" => "glpi_tracking", 
	"field" => "count",
	"linkfield"=>"",
	"name" => $lang["stats"][13],
	"meta" => 0,
   ),
	"financial"=>$lang["financial"][3],
	25 => array(	"table" => "glpi_infocoms", 
	"field" => "num_immo",
	"linkfield"=>"",
	"name" => $lang["financial"][20],
	"meta" => 0,
   ),
	29 => array(	"table" => "glpi_contracts", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["common"][16]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	30 => array(	"table" => "glpi_contracts", 
	"field" => "num",
	"linkfield"=>"",
	"name" => $lang["financial"][4]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	26 => array(	"table" => "glpi_infocoms", 
	"field" => "num_commande",
	"linkfield"=>"",
	"name" => $lang["financial"][18],
	"meta" => 0,
   ),
	27 => array(	"table" => "glpi_infocoms", 
	"field" => "bon_livraison",
	"linkfield"=>"",
	"name" => $lang["financial"][19],
	"meta" => 0,
   ),
	28 => array(	"table" => "glpi_infocoms", 
	"field" => "facture",
	"linkfield"=>"",
	"name" => $lang["financial"][82],
	"meta" => 0,
   ),
	37 => array(	"table" => "glpi_infocoms",
	"field" => "buy_date",
	"linkfield"=>"",
	"name" => $lang["financial"][14],
	"meta" => 0,
   ),
	38 => array(    "table" => "glpi_infocoms",
	"field" => "use_date",
	"linkfield"=>"",
	"name" => $lang["financial"][76],
	"meta" => 0,
   ),
	50 => array(	"table" => "glpi_dropdown_budget", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][87],
	"meta" => 0,
   ),
	51 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_duration",
	"linkfield"=>"",
	"name" => $lang["financial"][15],
	"meta" => 0,
   ),
	52 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_info",
	"linkfield"=>"",
	"name" => $lang["financial"][16],
	"meta" => 0,
   ),
	53 => array(	"table" => "glpi_enterprises_infocoms", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][3]." ".$lang["financial"][26],
	"meta" => 0,
   ),
	54 => array(	"table" => "glpi_infocoms", 
	"field" => "value",
	"linkfield"=>"",
	"name" => $lang["financial"][21],
	"meta" => 0,
   ),
	55 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_value",
	"linkfield"=>"",
	"name" => $lang["financial"][78],
	"meta" => 0,
   ),
	56 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_time",
	"linkfield"=>"",
	"name" => $lang["financial"][23],
	"meta" => 0,
   ),
	57 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_type",
	"linkfield"=>"",
	"name" => $lang["financial"][22],
	"meta" => 0,
   ),
	58 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_coeff",
	"linkfield"=>"",
	"name" => $lang["financial"][77],
	"meta" => 0,
   ),
	),
	MONITOR_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_monitors", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
"meta" => 1,
),
	2 => array(	"table" => "glpi_monitors", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
"meta" => 1,
),
	3 => array(	"table" => "glpi_dropdown_locations", 
"field" => "completename",
"linkfield"=>"location",
"name" => $lang["common"][15],
"meta" => 2,
),
	4 => array(	"table" => "glpi_type_monitors", 
"field" => "name",
"linkfield"=>"type",
"name" => $lang["common"][17],
"meta" => 2,
),
	40 => array(	"table" => "glpi_dropdown_model_monitors", 
	"field" => "name",
	"linkfield"=>"model",
	"name" => $lang["common"][22],
	"meta" => 2,
   ),
	31 => array(	"table" => "glpi_dropdown_state", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["state"][0],
	"meta" => 0,
   ),
	5 => array(	"table" => "glpi_monitors", 
	"field" => "serial",
	"linkfield"=>"serial",
	"name" => $lang["common"][19],
	"meta" => 1,
  ),
	6 => array(	"table" => "glpi_monitors", 
	"field" => "otherserial",
	"linkfield"=>"otherserial",
	"name" => $lang["common"][20],
	"meta" => 1,
  ),
	7 => array(	"table" => "glpi_monitors", 
	"field" => "contact",
	"linkfield"=>"contact",
	"name" => $lang["common"][18],
	"meta" => 1,
  ),
	8 => array(	"table" => "glpi_monitors", 
	"field" => "contact_num",
	"linkfield"=>"contact_num",
	"name" => $lang["common"][21],
	"meta" => 1,
  ),
	70 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"FK_users",
	"name" => $lang["common"][34],
	"meta" => 0,
   ),
	71 => array(	"table" => "glpi_groups", 
	"field" => "name",
	"linkfield"=>"FK_groups",
	"name" => $lang["common"][35],
	"meta" => 0,
   ),
	9 => array(	"table" => "glpi_monitors", 
	"field" => "date_mod",
	"linkfield"=>"",
	"name" => $lang["common"][26],
	"meta" => 1,
  ),
	10 => array(	"table" => "glpi_monitors", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
	"meta" => 1,
   ),
	11 => array(	"table" => "glpi_monitors", 
	"field" => "size",
	"linkfield"=>"size",
	"name" => $lang["monitors"][21],
	"meta" => 1,
   ),
	23 => array(	"table" => "glpi_enterprises", 
	"field" => "name",
	"linkfield"=>"FK_glpi_enterprise",
	"name" => $lang["common"][5],
	"meta" => 2,
   ),
	24 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"tech_num",
	"name" => $lang["common"][10],
	"meta" => 0,
   ),
	"tracking" => $lang["setup"][143],
	60 => array(	"table" => "glpi_tracking", 
	"field" => "count",
	"linkfield"=>"",
	"name" => $lang["stats"][13],
	"meta" => 0,
   ),
	"financial"=>$lang["financial"][3],
	29 => array(	"table" => "glpi_contracts", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["common"][16]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	30 => array(	"table" => "glpi_contracts", 
	"field" => "num",
	"linkfield"=>"",
	"name" => $lang["financial"][4]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	25 => array(	"table" => "glpi_infocoms", 
	"field" => "num_immo",
	"linkfield"=>"",
	"name" => $lang["financial"][20],
	"meta" => 0,
   ),
	26 => array(	"table" => "glpi_infocoms", 
	"field" => "num_commande",
	"linkfield"=>"",
	"name" => $lang["financial"][18],
	"meta" => 0,
   ),
	27 => array(	"table" => "glpi_infocoms", 
	"field" => "bon_livraison",
	"linkfield"=>"",
	"name" => $lang["financial"][19],
	"meta" => 0,
   ),
	28 => array(	"table" => "glpi_infocoms", 
	"field" => "facture",
	"linkfield"=>"",
	"name" => $lang["financial"][82],
	"meta" => 0,
   ),
	37 => array(	"table" => "glpi_infocoms",
	"field" => "buy_date",
	"linkfield"=>"",
	"name" => $lang["financial"][14],
	"meta" => 0,
   ),
	38 => array(    "table" => "glpi_infocoms",
	"field" => "use_date",
	"linkfield"=>"",
	"name" => $lang["financial"][76],
	"meta" => 0,
   ),
	50 => array(	"table" => "glpi_dropdown_budget", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][87],
	"meta" => 0,
   ),
	51 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_duration",
	"linkfield"=>"",
	"name" => $lang["financial"][15],
	"meta" => 0,
   ),
	52 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_info",
	"linkfield"=>"",
	"name" => $lang["financial"][16],
	"meta" => 0,
   ),
	53 => array(	"table" => "glpi_enterprises_infocoms", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][3]." ".$lang["financial"][26],
	"meta" => 0,
   ),
	54 => array(	"table" => "glpi_infocoms", 
	"field" => "value",
	"linkfield"=>"",
	"name" => $lang["financial"][21],
	"meta" => 0,
   ),
	55 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_value",
	"linkfield"=>"",
	"name" => $lang["financial"][78],
	"meta" => 0,
   ),
	56 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_time",
	"linkfield"=>"",
	"name" => $lang["financial"][23],
	"meta" => 0,
   ),
	57 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_type",
	"linkfield"=>"",
	"name" => $lang["financial"][22],
	"meta" => 0,
   ),
	58 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_coeff",
	"linkfield"=>"",
	"name" => $lang["financial"][77],
	"meta" => 0,
   ),
	),
	PERIPHERAL_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_peripherals", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
"meta" => 1,
),
	2 => array(	"table" => "glpi_peripherals", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
"meta" => 1,
),
	3 => array(	"table" => "glpi_dropdown_locations", 
"field" => "completename",
"linkfield"=>"location",
"name" => $lang["common"][15],
"meta" => 2,
),
	4 => array(	"table" => "glpi_type_peripherals", 
"field" => "name",
"linkfield"=>"type",
"name" => $lang["common"][17],
"meta" => 2,
),
	40 => array(	"table" => "glpi_dropdown_model_peripherals", 
	"field" => "name",
	"linkfield"=>"model",
	"name" => $lang["common"][22],
	"meta" => 2,
   ),
	31 => array(	"table" => "glpi_dropdown_state", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["state"][0],
	"meta" => 0,
   ),
	5 => array(	"table" => "glpi_peripherals", 
	"field" => "serial",
	"linkfield"=>"serial",
	"name" => $lang["common"][19],
	"meta" => 1,
  ),
	6 => array(	"table" => "glpi_peripherals", 
	"field" => "otherserial",
	"linkfield"=>"otherserial",
	"name" => $lang["common"][20],
	"meta" => 1,
  ),
	7 => array(	"table" => "glpi_peripherals", 
	"field" => "contact",
	"linkfield"=>"contact",
	"name" => $lang["common"][18],
	"meta" => 1,
  ),
	8 => array(	"table" => "glpi_peripherals", 
	"field" => "contact_num",
	"linkfield"=>"contact_num",
	"name" => $lang["common"][21],
	"meta" => 1,
  ),
	70 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"FK_users",
	"name" => $lang["common"][34],
	"meta" => 0,
   ),
	71 => array(	"table" => "glpi_groups", 
	"field" => "name",
	"linkfield"=>"FK_groups",
	"name" => $lang["common"][35],
	"meta" => 0,
   ),
	9 => array(	"table" => "glpi_peripherals", 
	"field" => "date_mod",
	"linkfield"=>"",
	"name" => $lang["common"][26],
	"meta" => 1,
  ),
	10 => array(	"table" => "glpi_peripherals", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
	"meta" => 1,
   ),
	11 => array(	"table" => "glpi_peripherals", 
	"field" => "brand",
	"linkfield"=>"brand",
	"name" => $lang["peripherals"][18],
	"meta" => 1,
   ),
	23 => array(	"table" => "glpi_enterprises", 
	"field" => "name",
	"linkfield"=>"FK_glpi_enterprise",
	"name" => $lang["common"][5],
	"meta" => 2,
   ),
	24 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"tech_num",
	"name" => $lang["common"][10],
	"meta" => 0,
   ),
	"tracking" => $lang["setup"][143],
	60 => array(	"table" => "glpi_tracking", 
	"field" => "count",
	"linkfield"=>"",
	"name" => $lang["stats"][13],
	"meta" => 0,
   ),
	"financial"=>$lang["financial"][3],
	29 => array(	"table" => "glpi_contracts", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["common"][16]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	30 => array(	"table" => "glpi_contracts", 
	"field" => "num",
	"linkfield"=>"",
	"name" => $lang["financial"][4]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	25 => array(	"table" => "glpi_infocoms", 
	"field" => "num_immo",
	"linkfield"=>"",
	"name" => $lang["financial"][20],
	"meta" => 0,
   ),
	26 => array(	"table" => "glpi_infocoms", 
	"field" => "num_commande",
	"linkfield"=>"",
	"name" => $lang["financial"][18],
	"meta" => 0,
   ),
	27 => array(	"table" => "glpi_infocoms", 
	"field" => "bon_livraison",
	"linkfield"=>"",
	"name" => $lang["financial"][19],
	"meta" => 0,
   ),
	28 => array(	"table" => "glpi_infocoms", 
	"field" => "facture",
	"linkfield"=>"",
	"name" => $lang["financial"][82],
	"meta" => 0,
   ),
	37 => array(	"table" => "glpi_infocoms",
	"field" => "buy_date",
	"linkfield"=>"",
	"name" => $lang["financial"][14],
	"meta" => 0,
   ),
	38 => array(    "table" => "glpi_infocoms",
	"field" => "use_date",
	"linkfield"=>"",
	"name" => $lang["financial"][76],
	"meta" => 0,
   ),
	50 => array(	"table" => "glpi_dropdown_budget", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][87],
	"meta" => 0,
   ),
	51 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_duration",
	"linkfield"=>"",
	"name" => $lang["financial"][15],
	"meta" => 0,
   ),
	52 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_info",
	"linkfield"=>"",
	"name" => $lang["financial"][16],
	"meta" => 0,
   ),
	53 => array(	"table" => "glpi_enterprises_infocoms", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][3]." ".$lang["financial"][26],
	"meta" => 0,
   ),
	54 => array(	"table" => "glpi_infocoms", 
	"field" => "value",
	"linkfield"=>"",
	"name" => $lang["financial"][21],
	"meta" => 0,
   ),
	55 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_value",
	"linkfield"=>"",
	"name" => $lang["financial"][78],
	"meta" => 0,
   ),
	56 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_time",
	"linkfield"=>"",
	"name" => $lang["financial"][23],
	"meta" => 0,
   ),
	57 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_type",
	"linkfield"=>"",
	"name" => $lang["financial"][22],
	"meta" => 0,
   ),
	58 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_coeff",
	"linkfield"=>"",
	"name" => $lang["financial"][77],
	"meta" => 0,
   ),

	),
	SOFTWARE_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_software", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
"meta" => 1,
),
	2 => array(	"table" => "glpi_software", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
"meta" => 1,
),
	3 => array(	"table" => "glpi_dropdown_locations", 
"field" => "completename",
"linkfield"=>"location",
"name" => $lang["common"][15],
"meta" => 2,
),
	31 => array(	"table" => "glpi_dropdown_state", 
"field" => "name",
"linkfield"=>"",
"name" => $lang["state"][0],
"meta" => 0,
),
	4 => array(	"table" => "glpi_dropdown_os", 
	"field" => "name",
	"linkfield"=>"platform",
	"name" => $lang["software"][3],
	"meta" => 2,
  ),
	5 => array(	"table" => "glpi_software", 
	"field" => "version",
	"linkfield"=>"version",
	"name" => $lang["software"][5],
	"meta" => 1,
  ),
	6 => array(	"table" => "glpi_software", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
	"meta" => 1,
  ),
	7 => array(	"table" => "glpi_licenses", 
	"field" => "serial",
	"linkfield"=>"",
	"name" => $lang["software"][11],
	"meta" => 1,
  ),
	9 => array(	"table" => "glpi_software", 
	"field" => "date_mod",
	"linkfield"=>"",
	"name" => $lang["common"][26],
	"meta" => 1,
  ),
	23 => array(	"table" => "glpi_enterprises", 
	"field" => "name",
	"linkfield"=>"FK_glpi_enterprise",
	"name" => $lang["common"][5],
	"meta" => 2,
   ),
	24 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"tech_num",
	"name" => $lang["common"][10],
	"meta" => 0,
   ),
	70 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"FK_users",
	"name" => $lang["common"][34],
	"meta" => 0,
   ),
	71 => array(	"table" => "glpi_groups", 
	"field" => "name",
	"linkfield"=>"FK_groups",
	"name" => $lang["common"][35],
	"meta" => 0,
   ),
   	"tracking" => $lang["setup"][143],
	60 => array(	"table" => "glpi_tracking", 
	"field" => "count",
	"linkfield"=>"",
	"name" => $lang["stats"][13],
	"meta" => 0,
   ),
	"financial"=>$lang["financial"][3],
	29 => array(	"table" => "glpi_contracts", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["common"][16]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	30 => array(	"table" => "glpi_contracts", 
	"field" => "num",
	"linkfield"=>"",
	"name" => $lang["financial"][4]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	25 => array(	"table" => "glpi_infocoms", 
	"field" => "num_immo",
	"linkfield"=>"",
	"name" => $lang["financial"][20],
	"meta" => 0,
   ),
	26 => array(	"table" => "glpi_infocoms", 
	"field" => "num_commande",
	"linkfield"=>"",
	"name" => $lang["financial"][18],
	"meta" => 0,
   ),
	27 => array(	"table" => "glpi_infocoms", 
	"field" => "bon_livraison",
	"linkfield"=>"",
	"name" => $lang["financial"][19],
	"meta" => 0,
   ),
	28 => array(	"table" => "glpi_infocoms", 
	"field" => "facture",
	"linkfield"=>"",
	"name" => $lang["financial"][82],
	"meta" => 0,
   ),
	37 => array(	"table" => "glpi_infocoms",
	"field" => "buy_date",
	"linkfield"=>"",
	"name" => $lang["financial"][14],
	"meta" => 0,
   ),
	38 => array(    "table" => "glpi_infocoms",
	"field" => "use_date",
	"linkfield"=>"",
	"name" => $lang["financial"][76],
	"meta" => 0,
   ),
	50 => array(	"table" => "glpi_dropdown_budget", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][87],
	"meta" => 0,
   ),
	51 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_duration",
	"linkfield"=>"",
	"name" => $lang["financial"][15],
	"meta" => 0,
   ),
	52 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_info",
	"linkfield"=>"",
	"name" => $lang["financial"][16],
	"meta" => 0,
   ),
	53 => array(	"table" => "glpi_enterprises_infocoms", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][3]." ".$lang["financial"][26],
	"meta" => 0,
   ),
	54 => array(	"table" => "glpi_infocoms", 
	"field" => "value",
	"linkfield"=>"",
	"name" => $lang["financial"][21],
	"meta" => 0,
   ),
	55 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_value",
	"linkfield"=>"",
	"name" => $lang["financial"][78],
	"meta" => 0,
   ),
	56 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_time",
	"linkfield"=>"",
	"name" => $lang["financial"][23],
	"meta" => 0,
   ),
	57 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_type",
	"linkfield"=>"",
	"name" => $lang["financial"][22],
	"meta" => 0,
   ),
	58 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_coeff",
	"linkfield"=>"",
	"name" => $lang["financial"][77],
	"meta" => 0,
   ),

	),
	CONTACT_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_contacts", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][48],
),
	11 => array(	"table" => "glpi_contacts", 
"field" => "firstname",
"linkfield"=>"firstname",
"name" => $lang["common"][43],
),
	2 => array(	"table" => "glpi_contacts", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
),
	3 => array(	"table" => "glpi_contacts", 
"field" => "phone",
"linkfield"=>"phone",
"name" => $lang["financial"][29],
),
	4 => array(	"table" => "glpi_contacts", 
	"field" => "phone2",
	"linkfield"=>"phone2",
	"name" => $lang["financial"][29]." 2",
  ),
	10 => array(	"table" => "glpi_contacts", 
	"field" => "mobile",
	"linkfield"=>"mobile",
	"name" => $lang["common"][42],
   ),
	5 => array(	"table" => "glpi_contacts", 
	"field" => "fax",
	"linkfield"=>"fax",
	"name" => $lang["financial"][30],
  ),
	6 => array(	"table" => "glpi_contacts", 
	"field" => "email",
	"linkfield"=>"email",
	"name" => $lang["setup"][14],
  ),
	7 => array(	"table" => "glpi_contacts", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
  ),
	9 => array(	"table" => "glpi_dropdown_contact_type", 
	"field" => "name",
	"linkfield"=>"type",
	"name" => $lang["common"][17],
  ),
	),
	ENTERPRISE_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_enterprises", 
"field" => "name",
"linkfield"=>"name",	
"name" => $lang["common"][16],
),
	2 => array(	"table" => "glpi_enterprises", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
),
	3 => array(	"table" => "glpi_enterprises", 
"field" => "address",
"linkfield"=>"address",
"name" => $lang["financial"][44],
),
	10 => array(	"table" => "glpi_enterprises", 
"field" => "postcode",
"linkfield"=>"postcode",
"name" => $lang["financial"][100],
),
	11 => array(	"table" => "glpi_enterprises", 
	"field" => "town",
	"linkfield"=>"town",
	"name" => $lang["financial"][101],
   ),
	12 => array(	"table" => "glpi_enterprises", 
	"field" => "state",
	"linkfield"=>"state",
	"name" => $lang["financial"][102],
   ),
	13 => array(	"table" => "glpi_enterprises", 
	"field" => "country",
	"linkfield"=>"country",
	"name" => $lang["financial"][103],
   ),
	4 => array(	"table" => "glpi_enterprises", 
	"field" => "website",
	"linkfield"=>"website",
	"name" => $lang["financial"][45],
  ),
	5 => array(	"table" => "glpi_enterprises", 
	"field" => "phonenumber",
	"linkfield"=>"phonenumber",
	"name" => $lang["financial"][29],
  ),
	10 => array(	"table" => "glpi_enterprises", 
	"field" => "fax",
	"linkfield"=>"fax",
	"name" => $lang["financial"][30],
   ),
	6 => array(	"table" => "glpi_enterprises", 
	"field" => "email",
	"linkfield"=>"email",
	"name" => $lang["setup"][14],
  ),
	7 => array(	"table" => "glpi_enterprises", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
  ),
	9 => array(	"table" => "glpi_dropdown_enttype", 
	"field" => "name",
	"linkfield"=>"type",
	"name" => $lang["financial"][79],
  ),
	),
	//INFOCOM_TYPE => ,
	CONTRACT_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_contracts", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
),
	2 => array(	"table" => "glpi_contracts", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
),
	3 => array(	"table" => "glpi_contracts", 
"field" => "num",
"linkfield"=>"num",
"name" => $lang["financial"][4],
),
	4 => array(	"table" => "glpi_dropdown_contract_type", 
"field" => "name",
"linkfield"=>"contract_type",
"name" => $lang["common"][17],
),
	5 => array(	"table" => "glpi_contracts", 
	"field" => "begin_date",
	"linkfield"=>"",
	"name" => $lang["search"][8],
  ),
	6 => array(	"table" => "glpi_contracts", 
	"field" => "duration",
	"linkfield"=>"",
	"name" => $lang["financial"][8],
  ),
	20 => array(	"table" => "glpi_contracts", 
	"field" => "end_date",
	"linkfield"=>"",
	"name" => $lang["search"][9],
   ),
	7 => array(	"table" => "glpi_contracts", 
	"field" => "notice",
	"linkfield"=>"",
	"name" => $lang["financial"][10],
  ),
	11 => array(	"table" => "glpi_contracts", 
	"field" => "cost",
	"linkfield"=>"cost",
	"name" => $lang["financial"][5],
   ),
	21 => array(	"table" => "glpi_contracts", 
	"field" => "periodicity",
	"linkfield"=>"",
	"name" => $lang["financial"][69],
   ),
	22 => array(	"table" => "glpi_contracts", 
	"field" => "facturation",
	"linkfield"=>"",
	"name" => $lang["financial"][11],
   ),
	10 => array(	"table" => "glpi_contracts", 
	"field" => "compta_num",
	"linkfield"=>"compta_num",
	"name" => $lang["financial"][13],
   ),
	23 => array(	"table" => "glpi_contracts", 
	"field" => "renewal",
	"linkfield"=>"",
	"name" => $lang["financial"][107],
   ),
	12 => array(	"table" => "glpi_contracts", 
	"field" => "expire",
	"linkfield"=>"",
	"name" => $lang["financial"][98],
   ),	
	13 => array(	"table" => "glpi_contracts", 
	"field" => "expire_notice",
	"linkfield"=>"",
	"name" =>$lang["financial"][99],
   ),	


	),
	CARTRIDGE_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_cartridges_type", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
),
	2 => array(	"table" => "glpi_cartridges_type", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
),
	3 => array(	"table" => "glpi_cartridges_type", 
"field" => "ref",
"linkfield"=>"ref",
"name" => $lang["cartridges"][2],
),
	4 => array(	"table" => "glpi_dropdown_cartridge_type", 
"field" => "name",
"linkfield"=>"type",
"name" => $lang["common"][17],
),
	5 => array(	"table" => "glpi_enterprises", 
	"field" => "name",
	"linkfield"=>"FK_glpi_enterprise",
	"name" => $lang["common"][5],
  ),
	6 => array(	"table" => "glpi_dropdown_locations", 
	"field" => "completename",
	"linkfield"=>"location",
	"name" => $lang["cartridges"][36],
  ),
	7 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"tech_num",
	"name" => $lang["common"][10],
  ),
	),
	TYPEDOC_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_type_docs", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
),
	2 => array(	"table" => "glpi_type_docs", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
),
	3 => array(	"table" => "glpi_type_docs", 
"field" => "ext",
"linkfield"=>"ext",
"name" => $lang["document"][9],
),
	6 => array(	"table" => "glpi_type_docs", 
"field" => "icon",
"linkfield"=>"",
"name" => $lang["document"][10],
),
	4 => array(	"table" => "glpi_type_docs", 
	"field" => "mime",
	"linkfield"=>"mime",
	"name" => $lang["document"][4],
  ),
	5 => array(	"table" => "glpi_type_docs", 
	"field" => "upload",
	"linkfield"=>"",
	"name" => $lang["document"][15],
  ),
	),
	DOCUMENT_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_docs", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
),
	2 => array(	"table" => "glpi_docs", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
),
	3 => array(	"table" => "glpi_docs", 
"field" => "filename",
"linkfield"=>"",
"name" => $lang["document"][2],
),
	4 => array(	"table" => "glpi_docs", 
"field" => "link",
"linkfield"=>"link",
"name" => $lang["document"][33],
),
	5 => array(	"table" => "glpi_docs", 
	"field" => "mime",
	"linkfield"=>"mime",
	"name" => $lang["document"][4],
  ),
	6 => array(	"table" => "glpi_docs", 
	"field" => "comment",
	"linkfield"=>"",
	"name" => $lang["common"][25],
  ),
	7 => array(	"table" => "glpi_dropdown_rubdocs", 
	"field" => "name",
	"linkfield"=>"rubrique",
	"name" => $lang["document"][3],
  ),	
	),
	//KNOWBASE_TYPE => "glpi_kbitems",
	USER_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_users", 
"field" => "name",
"linkfield"=>"",
"name" => $lang["setup"][18],
),
	2 => array(	"table" => "glpi_users", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
),
	3 => array(	"table" => "glpi_users", 
"field" => "realname",
"linkfield"=>"realname",
"name" => $lang["common"][48],
),
	9 => array(	"table" => "glpi_users", 
"field" => "firstname",
"linkfield"=>"firstname",
"name" => $lang["common"][43],
),
	4 => array(	"table" => "glpi_profiles", 
	"field" => "name",
	"linkfield"=>"profile",
	"name" => $lang["profiles"][22],
  ),
	5 => array(	"table" => "glpi_users", 
	"field" => "email",
	"linkfield"=>"email",
	"name" => $lang["setup"][14],
  ),
	6 => array(	"table" => "glpi_users", 
	"field" => "phone",
	"linkfield"=>"phone",
	"name" => $lang["financial"][29],
  ),
	10 => array(	"table" => "glpi_users", 
	"field" => "phone2",
	"linkfield"=>"phone2",
	"name" => $lang["financial"][29]." 2",
   ),
	11 => array(	"table" => "glpi_users", 
	"field" => "mobile",
	"linkfield"=>"mobile",
	"name" => $lang["common"][42],
   ),
	7 => array(	"table" => "glpi_dropdown_locations", 
	"field" => "completename",
	"linkfield"=>"location",
	"name" => $lang["common"][15],
  ),
	8 => array(	"table" => "glpi_users", 
	"field" => "active",
	"linkfield"=>"active",
	"name" => $lang["setup"][400],
  ),
	12 => array(	"table" => "glpi_users", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
   ),
	13 => array(	"table" => "glpi_groups", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["common"][35],
   ),

	),
	//TRACKING_TYPE => "glpi_tracking",
	CONSUMABLE_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_consumables_type", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
),
	2 => array(	"table" => "glpi_consumables_type", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
),
	3 => array(	"table" => "glpi_consumables_type", 
"field" => "ref",
"linkfield"=>"ref",
"name" => $lang["consumables"][2],
),
	4 => array(	"table" => "glpi_dropdown_consumable_type", 
"field" => "name",
"linkfield"=>"type",
"name" => $lang["common"][17],
),
	5 => array(	"table" => "glpi_enterprises", 
	"field" => "name",
	"linkfield"=>"FK_glpi_enteprise",
	"name" => $lang["common"][5],
  ),
	6 => array(	"table" => "glpi_dropdown_locations", 
	"field" => "completename",
	"linkfield"=>"location",
	"name" => $lang["consumables"][36],
  ),
	7 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"tech_num",
	"name" => $lang["common"][10],
  ),
	),
	//CONSUMABLE_ITEM_TYPE => "glpi_consumables",
	//CARTRIDGE_ITEM_TYPE => "glpi_cartridges",
	//LICENSE_TYPE => "glpi_licenses",
	LINK_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_links", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
),
	2 => array(	"table" => "glpi_links", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
),
	3 => array(	"table" => "glpi_links", 
"field" => "link",
"linkfield"=>"link",
"name" => $lang["links"][1],
),

	),
	//STATE_TYPE => "",
	PHONE_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_phones", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
"meta" => 1,
),
	2 => array(	"table" => "glpi_phones", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
"meta" => 1,
),
	3 => array(	"table" => "glpi_dropdown_locations", 
"field" => "completename",
"linkfield"=>"location",
"name" => $lang["common"][15],
"meta" => 2,
),
	4 => array(	"table" => "glpi_type_phones", 
"field" => "name",
"linkfield"=>"type",
"name" => $lang["common"][17],
"meta" => 2,
),
	40 => array(	"table" => "glpi_dropdown_model_phones", 
	"field" => "name",
	"linkfield"=>"model",
	"name" => $lang["common"][22],
	"meta" => 2,
   ),
	31 => array(	"table" => "glpi_dropdown_state", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["state"][0],
	"meta" => 0,
   ),
	5 => array(	"table" => "glpi_phones", 
	"field" => "serial",
	"linkfield"=>"serial",
	"name" => $lang["common"][19],
	"meta" => 1,
  ),
	6 => array(	"table" => "glpi_phones", 
	"field" => "otherserial",
	"linkfield"=>"otherserial",
	"name" => $lang["common"][20],
	"meta" => 1,
  ),
	7 => array(	"table" => "glpi_phones", 
	"field" => "contact",
	"linkfield"=>"contact",
	"name" => $lang["common"][18],
	"meta" => 1,
  ),
	8 => array(	"table" => "glpi_phones", 
	"field" => "contact_num",
	"linkfield"=>"contact_num",
	"name" => $lang["common"][21],
	"meta" => 1,
  ),
	70 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"FK_users",
	"name" => $lang["common"][34],
	"meta" => 0,
   ),
	71 => array(	"table" => "glpi_groups", 
	"field" => "name",
	"linkfield"=>"FK_groups",
	"name" => $lang["common"][35],
	"meta" => 0,
   ),
	9 => array(	"table" => "glpi_phones", 
	"field" => "date_mod",
	"linkfield"=>"",
	"name" => $lang["common"][26],
	"meta" => 1,
  ),
	10 => array(	"table" => "glpi_phones", 
	"field" => "comments",
	"linkfield"=>"",
	"name" => $lang["common"][25],
	"meta" => 1,
   ),
	23 => array(	"table" => "glpi_enterprises", 
	"field" => "name",
	"linkfield"=>"FK_glpi_enterprise",
	"name" => $lang["common"][5],
	"meta" => 2,
   ),
	24 => array(	"table" => "glpi_users", 
	"field" => "name",
	"linkfield"=>"tech_num",
	"name" => $lang["common"][10],
	"meta" => 2,
   ),
	42 => array(	"table" => "glpi_dropdown_phone_power", 
	"field" => "name",
	"linkfield"=>"power",
	"name" => $lang["phones"][36],
	"meta" => 1,
   ),
	"tracking" => $lang["setup"][143],
	60 => array(	"table" => "glpi_tracking", 
	"field" => "count",
	"linkfield"=>"",
	"name" => $lang["stats"][13],
	"meta" => 0,
   ),
	"financial"=>$lang["financial"][3],
	29 => array(	"table" => "glpi_contracts", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["common"][16]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	30 => array(	"table" => "glpi_contracts", 
	"field" => "num",
	"linkfield"=>"",
	"name" => $lang["financial"][4]." ".$lang["financial"][1],
	"meta" => 0,
   ),
	25 => array(	"table" => "glpi_infocoms", 
	"field" => "num_immo",
	"linkfield"=>"",
	"name" => $lang["financial"][20],
	"meta" => 0,
   ),
	26 => array(	"table" => "glpi_infocoms", 
	"field" => "num_commande",
	"linkfield"=>"",
	"name" => $lang["financial"][18],
	"meta" => 0,
   ),
	27 => array(	"table" => "glpi_infocoms", 
	"field" => "bon_livraison",
	"linkfield"=>"",
	"name" => $lang["financial"][19],
	"meta" => 0,
   ),
	28 => array(	"table" => "glpi_infocoms", 
	"field" => "facture",
	"linkfield"=>"",
	"name" => $lang["financial"][82],
	"meta" => 0,
   ),
	37 => array(	"table" => "glpi_infocoms",
	"field" => "buy_date",
	"linkfield"=>"",
	"name" => $lang["financial"][14],
	"meta" => 0,
   ),
	38 => array(    "table" => "glpi_infocoms",
	"field" => "use_date",
	"linkfield"=>"",
	"name" => $lang["financial"][76],
	"meta" => 0,
   ),

	50 => array(	"table" => "glpi_dropdown_budget", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][87],
	"meta" => 0,
   ),
	51 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_duration",
	"linkfield"=>"",
	"name" => $lang["financial"][15],
	"meta" => 0,
   ),
	52 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_info",
	"linkfield"=>"",
	"name" => $lang["financial"][16],
	"meta" => 0,
   ),
	53 => array(	"table" => "glpi_enterprises_infocoms", 
	"field" => "name",
	"linkfield"=>"",
	"name" => $lang["financial"][3]." ".$lang["financial"][26],
	"meta" => 0,
   ),
	54 => array(	"table" => "glpi_infocoms", 
	"field" => "value",
	"linkfield"=>"",
	"name" => $lang["financial"][21],
	"meta" => 0,
   ),
	55 => array(	"table" => "glpi_infocoms", 
	"field" => "warranty_value",
	"linkfield"=>"",
	"name" => $lang["financial"][78],
	"meta" => 0,
   ),
	56 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_time",
	"linkfield"=>"",
	"name" => $lang["financial"][23],
	"meta" => 0,
   ),
	57 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_type",
	"linkfield"=>"",
	"name" => $lang["financial"][22],
	"meta" => 0,
   ),
	58 => array(	"table" => "glpi_infocoms", 
	"field" => "amort_coeff",
	"linkfield"=>"",
	"name" => $lang["financial"][77],
	"meta" => 0,
   ),

	),
	//DEVICE_TYPE => "",
	//REMINDER_TYPE => "",
	//STAT_TYPE => "",
	GROUP_TYPE => array(
	"common" => $lang["common"][32],
	1 => array(	"table" => "glpi_groups", 
"field" => "name",
"linkfield"=>"name",
"name" => $lang["common"][16],
"meta" => 1,
),
	2 => array(	"table" => "glpi_groups", 
"field" => "ID",
"linkfield"=>"",
"name" => $lang["common"][2],
"meta" => 1,
),
	16 => array(	"table" => "glpi_groups", 
"field" => "comments",
"linkfield"=>"",
"name" => $lang["common"][25],
"meta" => 1,
),
	3 => array(	"table" => "glpi_groups", 
"field" => "ldap_field",
"linkfield"=>"ldap_field",
"name" => $lang["setup"][260],
"meta" => 1,
),
	4 => array(	"table" => "glpi_groups", 
	"field" => "ldap_value",
	"linkfield"=>"ldap_value",
	"name" => $lang["setup"][601],
	"meta" => 1,
  ),
	5 => array(	"table" => "glpi_groups", 
	"field" => "ldap_group_dn",
	"linkfield"=>"ldap_group_dn",
	"name" => $lang["setup"][261],
	"meta" => 1,
  ),

	),
);

$SEARCH_OPTION[PERIPHERAL_TYPE]['network']=$lang["setup"][88];

$SEARCH_OPTION[PERIPHERAL_TYPE][20]['table']='glpi_networking_ports';
$SEARCH_OPTION[PERIPHERAL_TYPE][20]['field']='ifaddr';
$SEARCH_OPTION[PERIPHERAL_TYPE][20]['linkfield']='';
$SEARCH_OPTION[PERIPHERAL_TYPE][20]['name']=$lang["networking"][14];
$SEARCH_OPTION[PERIPHERAL_TYPE][20]['meta']=0;

$SEARCH_OPTION[PERIPHERAL_TYPE][21]['table']='glpi_networking_ports';
$SEARCH_OPTION[PERIPHERAL_TYPE][21]['field']='ifmac';
$SEARCH_OPTION[PERIPHERAL_TYPE][21]['linkfield']='';
$SEARCH_OPTION[PERIPHERAL_TYPE][21]['name']=$lang["networking"][15];
$SEARCH_OPTION[PERIPHERAL_TYPE][21]['meta']=0;

$SEARCH_OPTION[PERIPHERAL_TYPE][22]['table']='glpi_dropdown_netpoint';
$SEARCH_OPTION[PERIPHERAL_TYPE][22]['field']='name';
$SEARCH_OPTION[PERIPHERAL_TYPE][22]['linkfield']='';
$SEARCH_OPTION[PERIPHERAL_TYPE][22]['name']=$lang["networking"][51];
$SEARCH_OPTION[PERIPHERAL_TYPE][22]['meta']=0;
?>
