tinyMCE.addI18n('et.advlink_dlg',{
title:"Sisesta muuda linki",
url:" URL\u2019i link",
target:"Sihtm\u00E4rk",
titlefield:"Pealkiri",
is_email:" URL, mille sisestasid, tundub olevat e-posti aadress, kas soovid sellele lisada mailto: funktsiooni?",
is_external:"URL, mille sisestasid, tundub olevat v\u00E4line link, kas soovid sellele lisada http://?",
list:"Linkide nimekiri",
general_tab:"\u00DCldine",
popup_tab:"Pop-up",
events_tab:"S\u00FCndmused",
advanced_tab:"P\u00F5hjalikum",
general_props:"\u00DCldised seadistused",
popup_props:"Pop-up\u2019i seadistus",
event_props:"S\u00FCndmused",
advanced_props:"\u00DCldised seadistused",
popup_opts:"Valikud",
anchor_names:"Ankrud",
target_same:"Ava selles aknas/raamis",
target_parent:"Ava pea-aknas/raamis",
target_top:"Ava k\u00F5rgeimas raamis (asenda k\u00F5ik raamid)",
target_blank:"Ava uues aknas",
popup:"Javascript\u2019i pop-up",
popup_url:"Pop-up\u2019i URL",
popup_name:"Akna nimi",
popup_return:"Sisesta 'tagasiminek eba\u00F5nnestus'",
popup_scrollbars:"N\u00E4ita kerimisribasid",
popup_statusbar:"N\u00E4ita staatuse riba",
popup_toolbar:"N\u00E4ita seadistusriba",
popup_menubar:"N\u00E4ita men\u00FC\u00FCriba",
popup_location:"N\u00E4ita asukohariba",
popup_resizable:"Muuda akna suurus muudetavaks",
popup_dependent:"S\u00F5ltuv (ainult Mozilla/Firefox)",
popup_size:"Suurus",
popup_position:"Positsioon (X/Y)",
id:"ID",
style:"Stiil",
classes:"Klassid",
target_name:"Sihtm\u00E4rgi nimi",
langdir:"Keele suund",
target_langcode:"Sihtm\u00E4rgi keel",
langcode:"Keele kood",
encoding:"Sihtm\u00E4rgi kodeering",
mime:"M\u00E4rgista MIME t\u00FC\u00FCp",
rel:"Seo leht sihtm\u00E4rgiga",
rev:"Seo sihtm\u00E4rk lehega",
tabindex:"Sisujuht",
accesskey:"Ligip\u00E4\u00E4suklahv",
ltr:"Vasakult paremale",
rtl:"Paremalt vasakule",
link_list:"Linkide list"
});