tinyMCE.addI18n('fi.advlink_dlg',{
title:"Lis\u00E4\u00E4/muokkaa linkki\u00E4",
url:"Linkin URL",
target:"Kohde (target)",
titlefield:"Otsikko",
is_email:"Sy\u00F6tt\u00E4m\u00E4si URL n\u00E4ytt\u00E4\u00E4 olevan s\u00E4hk\u00F6postiosoite, haluatko lis\u00E4t\u00E4 mailto:-etuliitteen?",
is_external:"Sy\u00F6tt\u00E4m\u00E4si URL n\u00E4ytt\u00E4\u00E4 olevan sivuston ulkoinen osoite, haluatko lis\u00E4t\u00E4 http://-etuliitteen?",
list:"Linkkilista",
general_tab:"Yleiset",
popup_tab:"Ponnahdusikkuna",
events_tab:"Tapahtumat",
advanced_tab:"Edistynyt",
general_props:"Yleiset asetukset",
popup_props:"Ponnahdusikkunan asetukset",
event_props:"Tapahtumat (events)",
advanced_props:"Edistyneet asetukset",
popup_opts:"Valinta",
anchor_names:"Ankkurit",
target_same:"Avaa t\u00E4ss\u00E4 ikkunassa",
target_parent:"Avaa ylemm\u00E4ss\u00E4 ikkunassa",
target_top:"Avaa ylimm\u00E4ss\u00E4 ruudussa (korvaa kaikki ruudut)",
target_blank:"Avaa uudessa ikkunassa",
popup:"Javascript ponnahdusikkuna",
popup_url:"Ponnahdusikkunan URL",
popup_name:"Ikkunan nimi",
popup_return:"Lis\u00E4\u00E4 'return false'",
popup_scrollbars:"N\u00E4yt\u00E4 vierityspalkit",
popup_statusbar:"N\u00E4yt\u00E4 tilapalkki",
popup_toolbar:"N\u00E4yt\u00E4 ty\u00F6kalut",
popup_menubar:"N\u00E4yt\u00E4 valikkopalkki",
popup_location:"N\u00E4yt\u00E4 sijaintipalkki",
popup_resizable:"Tee ikkunan koko muokattavaksi",
popup_dependent:"Riippuvainen (vain Mozilla/Firefox)",
popup_size:"Koko",
popup_position:"Sijainti (X/Y)",
id:"Id",
style:"Tyyli",
classes:"Luokat",
target_name:"Kohteen nimi",
langdir:"Kielen suunta",
target_langcode:"Kohteen kieli",
langcode:"Kielen koodi",
encoding:"Kohteen merkist\u00F6koodaus",
mime:"Kohteen MIME-tyyppi",
rel:"Sivun suhde kohteeseen",
rev:"Kohteen suhde sivuun",
tabindex:"Tabulaattori-indeksi",
accesskey:"Pikan\u00E4pp\u00E4in",
ltr:"Vasemmalta oikealle",
rtl:"Oikealta vasemmalle",
link_list:"Linkkilista"
});