tinyMCE.addI18n('nn.advlink_dlg',{
title:"Set inn / rediger lenkje",
url:"Lenkje-URL",
target:"M\u00E5l",
titlefield:"Tittel",
is_email:"URL-en du skreiv inn ser ut til \u00E5 vere ei e-postadresse. \u00D8nskjer du \u00E5 leggje til det obligatoriske mailto:-prefikset?",
is_external:"URL-en du skreiv inn ser ut til \u00E5 vere ei eksern lenkje. \u00D8nskjer du \u00E5 leggje til det obligatoriske http://-prefikset?",
list:"Lenkjeliste",
general_tab:"Generelt",
popup_tab:"Popup",
events_tab:"Hendingar",
advanced_tab:"Avansert",
general_props:"Generelt",
popup_props:"Popup-eigenskapar",
event_props:"Hendingar",
advanced_props:"Generelle eigenskapar",
popup_opts:"Innstillingar",
anchor_names:"Anker",
target_same:"Opne i same vindauge/ramme",
target_parent:"Opne i overordna vindauge/ramme",
target_top:"Opne i toppvindauge (erstattar alle rammer)",
target_blank:"Opne i nytt vindauge",
popup:"Javascript-popup",
popup_url:"Popup URL",
popup_name:"Namn p\u00E5 vindauge",
popup_return:"Set inn \'return false\'",
popup_scrollbars:"Vis rullefelt",
popup_statusbar:"Vis statusline",
popup_toolbar:"Vis verktyliner",
popup_menubar:"Vis menyline",
popup_location:"Vis plasseringsline",
popup_resizable:"Gjer vindauget skalerbart",
popup_dependent:"Avhengig vindu (berre i Mozilla/Firefox)",
popup_size:"Storleik",
popup_position:"Posisjon (X/Y)",
id:"Id",
style:"Stil",
classes:"Klasser",
target_name:"M\u00E5lnamn",
langdir:"Skriftretning",
target_langcode:"M\u00E5lspr\u00E5k",
langcode:"Spr\u00E5kkode",
encoding:"Teiknkonvertering",
mime:"M\u00E5let sin MIME-type",
rel:"Sida sitt forhold til m\u00E5let",
rev:"M\u00E5let sitt forhold til sida",
tabindex:"Tabulatorindeks",
accesskey:"Hurtigtast",
ltr:"Venstre mot h\u00F8gre",
rtl:"H\u00F8gre mot venstre",
link_list:"Lenkjeliste"
});