tinyMCE.addI18n('pl.advlink_dlg',{
title:"Wstaw/edytuj link",
url:"Link URL",
target:"Cel",
titlefield:"Tytu\u0142",
is_email:"Podany adres wydaje si\u0119 by\u0107 adresem emailowym, czy chcesz doda\u0107 wymagany prefix mailto: ?",
is_external:"Podany adres wydaje si\u0119 by\u0107 zewn\u0119trznym linkiem, czy chcesz doda\u0107 wymagany prefix http:// ?",
list:"Lista link\u00F3w",
general_tab:"Og\u00F3lny",
popup_tab:"Popup",
events_tab:"Wydarzenia",
advanced_tab:"Zaawansowany",
general_props:"Og\u00F3lne w\u0142a\u015Bciwo\u015Bci",
popup_props:"Popup w\u0142a\u015Bciwo\u015Bci",
event_props:"Wydarzenia",
advanced_props:"Zaawansowae w\u0142a\u015Bciwo\u015Bci",
popup_opts:"Opcje",
anchor_names:"Kotwice",
target_same:"Otw\u00F3rz w tym oknie / ramce",
target_parent:"Otw\u00F3rz w nadrz\u0119dnej oknie / ramce",
target_top:"Otw\u00F3rz w g\u00F3rnej ramce (zamie\u0144 wszystkie ramki)",
target_blank:"Otw\u00F3rz w nowym oknie",
popup:"Wyskakuj\u0105ce okienko",
popup_url:"URL okienka",
popup_name:"Nazwa okiena",
popup_return:"Wklej 'return false'",
popup_scrollbars:"Poka\u017C paski przewijania",
popup_statusbar:"Poka\u017C pasek statusu",
popup_toolbar:"Poka\u017C narz\u0119dzia",
popup_menubar:"Poka\u017C pasek menu",
popup_location:"Poka\u017C pasek adresu",
popup_resizable:"Stw\u00F3rz okno z w\u0142a\u015Bciwo\u015Bciami zmiany rozmiaru",
popup_dependent:"Podleg\u0142y (Mozilla/Firefox wy\u0142\u0105cznie)",
popup_size:"Rozmiar",
popup_position:"Pozycja (X/Y)",
id:"Id",
style:"Wz\u00F3r",
classes:"Klasy",
target_name:"Cel",
langdir:"Kierunek czytania tekstu",
target_langcode:"Docelowy kod j\u0119zyka",
langcode:"Kod j\u0119zyka",
encoding:"Kodowanie znak\u00F3w celu",
mime:"Cel MIME type",
rel:"Relacje strony do celu",
rev:"Relacje celu do strony",
tabindex:"Tabindex",
accesskey:"Klawisz skr\u00F3tu",
ltr:"Kierunek z lewej do prawej",
rtl:"Kierunek z prawej do lewej",
link_list:"Lista odno\u015Bnik\u00F3w"
});