// Greek lang variables by Jacaranda Bill
// Revised by Dimitris Giannitsaros / MediSign SA

tinyMCE.addToLang('',{
theme_style_select : 'Θέματα',
theme_code_desc : 'Επεξεργασία HTML κώδικα',
theme_code_title : 'Επεξεργαστής HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Δείκτης',
theme_sup_desc : 'Εκθέτης',
theme_hr_desc : 'Εισαγωγή οριζόντιας γραμμής',
theme_removeformat_desc : 'Απαλοιφή μορφοποίησης',
theme_custom1_desc : 'Περιγραφή',
insert_image_border : 'Περίγραμμα',
insert_image_dimensions : 'Διαστάσεις',
insert_image_vspace : 'Κάθ. περιθώριο',
insert_image_hspace : 'Οριζ. περιθώριο',
insert_image_align : 'Στοίχιση',
insert_image_align_default : 'Προκαθορισμένη',
insert_image_align_baseline : 'Σε ευθυγράμμιση με το κείμενο',
insert_image_align_top : 'Πάνω',
insert_image_align_middle : 'Στο κέντρο',
insert_image_align_bottom : 'Κάτω',
insert_image_align_texttop : 'Το κείμενο πάνω',
insert_image_align_absmiddle : 'Απόλυτα στο κέντρο',
insert_image_align_absbottom : 'Απόλυτα κάτω',
insert_image_align_left : 'Αριστερά',
insert_image_align_right : 'Δεξιά',
theme_font_size : '-- Μέγεθος γραμματοσειράς --',
theme_fontdefault : '-- Είδος γραμματοσειράς --',
theme_block : '-- Φορμά --',
theme_paragraph : 'Παράγραφος',
theme_div : 'Div',
theme_address : 'Διεύθυνση',
theme_pre : 'Ακριβώς',
theme_h1 : 'Επικεφαλίδα 1',
theme_h2 : 'Επικεφαλίδα 2',
theme_h3 : 'Επικεφαλίδα 3',
theme_h4 : 'Επικεφαλίδα 4',
theme_h5 : 'Επικεφαλίδα 5',
theme_h6 : 'Επικεφαλίδα 6',
theme_colorpicker_title : 'Χρώματα',
theme_colorpicker_apply : 'Εφαρμογή',
theme_forecolor_desc : 'Επιλογή χρώματος γραμματοσειράς',
theme_backcolor_desc : 'Επιλογή χρώματος background',
theme_charmap_title : 'Επιλογή ειδικού χαρακτήρα',
theme_charmap_desc : 'Εισαγωγή ειδικού χαρακτήρα',
theme_visualaid_desc : 'Εμφάνιση/Απόκρυψη γραμμών',
insert_anchor_title : 'Εισαγωγή/Διόρθωση άγκυρας',
insert_anchor_name : 'Ονομασία άγκυρας',
theme_anchor_desc : 'Εισαγωγή/Διόρθωση άγκυρας',
theme_insert_link_titlefield : 'Τίτλος',
theme_clipboard_msg : 'Η Αντιγραφή/Αποκοπή/Επικόλληση δεν είναι διαθέσιμες στο Mozilla και στο Firefox.\nΘέλετε πληροφορίες για αυτό το θέμα;',
theme_path : 'Διαδρομή',
cut_desc : 'Αποκοπή',
copy_desc : 'Αντιγραφή',
paste_desc : 'Επικόλληση',
link_list : 'Λίστα συνδέσμων',
image_list : 'Λίστα εικόνων',
browse : 'Περιήγηση',
image_props_desc : 'Ιδιότητες εικόνας',
newdocument_desc : 'Νέο έγγραφο',
class_name : 'Κλάση',
newdocument : 'Θέλετε σίγουρα να καθαρίσετε όλα τα περιεχόμενα;'
});
