/**
 * ES lang variables
 * 
 * Authors : Alvaro Velasco,
 *           Adolfo Sanz De Diego (asanzdiego) <asanzdiego@yahoo.es>,
 *           Carlos C Soto (eclipxe) <csoto@sia-solutions.com>
 *           Eneko Castresana Vara
 * Last Updated : July 14, 2006
 * TinyMCE Version : 2.0.6.1
 */

tinyMCE.addToLang('',{
theme_style_select : '-- Estilos --',
theme_code_desc : 'Editar c&oacute;digo HTML',
theme_code_title : 'Editor c&oacute;digo HTML',
theme_code_wordwrap : 'Ajuste de l&iacute;nea',
theme_sub_desc : 'Sub&iacute;ndice',
theme_sup_desc : 'Super&iacute;ndice',
theme_hr_desc : 'Insertar una barra horizontal',
theme_removeformat_desc : 'Quitar formato',
theme_custom1_desc : 'Tu descripci&oacute;n aqu&iacute;',
insert_image_border : 'Borde',
insert_image_dimensions : 'Dimensiones',
insert_image_vspace : 'Espacio vertical',
insert_image_hspace : 'Espacio horizontal',
insert_image_align : 'Alineaci&oacute;n',
insert_image_align_default : '-- Por defecto --',
insert_image_align_baseline : 'Linea base',
insert_image_align_top : 'Arriba',
insert_image_align_middle : 'Centrado',
insert_image_align_bottom : 'Abajo',
insert_image_align_texttop : 'Texto arriba',
insert_image_align_absmiddle : 'Centrado total',
insert_image_align_absbottom : 'Abajo total',
insert_image_align_left : 'Izquierda',
insert_image_align_right : 'Derecha',
theme_font_size : '-- Tama&ntilde;o del texto --',
theme_fontdefault : '-- Tipo de fuente --',
theme_block : '-- Formato del texto --',
theme_paragraph : 'P&aacute;rrafo',
theme_div : 'Capa',
theme_address : 'Direcci&oacute;n',
theme_pre : 'Preformateado',
theme_h1 : 'T&iacute;tulo 1',
theme_h2 : 'T&iacute;tulo 2',
theme_h3 : 'T&iacute;tulo 3',
theme_h4 : 'T&iacute;tulo 4',
theme_h5 : 'T&iacute;tulo 5',
theme_h6 : 'T&iacute;tulo 6',
theme_colorpicker_title : 'Selecciona un color',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Selecciona un color para el texto',
theme_backcolor_desc : 'Selecciona un color de fondo',
theme_charmap_title : 'Selecciona un car&aacute;cter especial',
theme_charmap_desc : 'Inserta un car&aacute;cter especial',
theme_charmap_all_title : 'Todos',
theme_charmap_all_desc : 'Todos los caracteres',
theme_charmap_alpha_title : 'Alfab&eacute;ticos',
theme_charmap_alpha_desc : 'Caracteres alfab&eacute;ticos',
theme_charmap_arrows_title : 'Flechas',
theme_charmap_arrows_desc : 'Caracteres de flechas',
theme_charmap_greek_title : 'Griegos',
theme_charmap_greek_desc : 'Caracteres Griegos',
theme_charmap_math_title : 'Mathem&aacute;ticos',
theme_charmap_math_desc : 'Caracteres mathem&aacute;ticos',
theme_charmap_misc_title : 'Miscel&aacute;neos',
theme_charmap_misc_desc : 'Caracteres miscel&aacute;neos',
theme_charmap_money_title : 'Monedas',
theme_charmap_money_desc : 'Caracteres de monedas',
theme_charmap_quotaion_title : 'Comillas',
theme_charmap_quotaion_desc : 'Caracteres de comillas',
theme_visualaid_desc : 'Cambiar las l&iacute;neas de ayuda por elementos invisibles',
insert_anchor_title : 'Insertar/editar ancla',
insert_anchor_name : 'Nombre del ancla',
theme_anchor_desc : 'Insertar/editar ancla',
theme_insert_link_titlefield : 'T&iacute;tulo',
theme_clipboard_msg : 'No se pueden utilizar los comandos Copiar / Cortar / Pegar en Mozilla y en Firefox.\r\nUse el teclado Copiar (Ctrl+C) / Cortar (Ctrl+X) / Pegar (Ctrl+V)\r\n&#191;Quieres obtener m&aacute;s informaci&oacute;n?',
theme_path : 'Ruta',
cut_desc : 'Cortar (Ctrl+X)',
copy_desc : 'Copiar (Ctrl+C)',
paste_desc : 'Pegar (Ctrl+V)',
link_list : 'Lista de enlaces',
image_list : 'Lista de im&aacute;genes',
browse : 'Navegar',
image_props_desc : 'Propiedades de la imagen',
newdocument_desc : 'Nuevo documento',
class_name : 'Clase',
newdocument : '&#191;Est&aacute;s seguro de que quieres borrar todo el contenido?',
about_title : 'Acerca de TinyMCE',
about : 'Acerca',
license : 'Licencia',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Autor',
version : 'Versi&oacute;n',
loaded_plugins : 'Plugins cargados',
help : 'Ayuda',
not_set : '-- Por defecto --',
close : 'Cerrar',
toolbar_focus : 'Saltar a la barra de herramientas - Alt+Q, Saltar al editor - Alt+Z, Saltar al elemento de la ruta - Alt+X',
theme_advanced_anchor_delta_width : 20
});
