// FR lang variables
// Modified by shadow walker, last updated 2007-03-16, based on the work of Motte

tinyMCE.addToLang('',{
theme_style_select : '-- Style --',
theme_code_desc : 'Afficher le code source',
theme_code_title : 'Edition du code source',
theme_code_wordwrap : 'Retour &agrave; la ligne automatique',
theme_sub_desc : 'Indice',
theme_sup_desc : 'Exposant',
theme_hr_desc : 'Ins&eacute;rer une r&egrave;gle horizontale ordinaire',
theme_removeformat_desc : 'Supprimer le formatage',
theme_custom1_desc : 'Votre description personnalis&eacute;e ici',
insert_image_border : 'Bordure',
insert_image_dimensions : 'Dimensions',
insert_image_vspace : 'Espacement vertical',
insert_image_hspace : 'Espacement horizontal',
insert_image_align : 'Alignement',
insert_image_align_default : '-- Ind&eacute;fini --',
insert_image_align_baseline : 'Ligne de base',
insert_image_align_top : 'Haut',
insert_image_align_middle : 'Milieu',
insert_image_align_bottom : 'Bas',
insert_image_align_texttop : 'Haut du texte',
insert_image_align_absmiddle : 'Milieu absolu',
insert_image_align_absbottom : 'Bas absolu',
insert_image_align_left : 'En flottement &agrave; gauche',
insert_image_align_right : 'En flottement &agrave; droite',
theme_font_size : '-- Taille --',
theme_fontdefault : '-- Police --',
theme_block : '-- Bloc de texte --',
theme_paragraph : 'Paragraphe',
theme_div : 'Div',
theme_address : 'Infos sur l\'auteur',
theme_pre : 'Texte pr&eacute;format&eacute;',
theme_h1 : 'Titre de niveau 1',
theme_h2 : 'Titre de niveau 2',
theme_h3 : 'Titre de niveau 3',
theme_h4 : 'Titre de niveau 4',
theme_h5 : 'Titre de niveau 5',
theme_h6 : 'Titre de niveau 6',
theme_blockquote : 'Citation',
theme_code : 'Code',
theme_samp : 'Exemple de code',
theme_dt : 'Definition du therme ',
theme_dd : 'Definition de la description',
theme_colorpicker_title : 'Choisir une couleur',
theme_colorpicker_apply : 'Appliquer',
theme_forecolor_desc : 'Couleur du texte',
theme_backcolor_desc : 'Couleur d\'arri&egrave;re-plan',
theme_charmap_title : 'S&eacute;lectionner un caract&egrave;re sp&eacute;cial',
theme_charmap_desc : 'Ins&eacute;rer un caract&egrave;re sp&eacute;cial',
theme_visualaid_desc : 'Activer/D&eacute;sactiver les lignes guides et les &eacute;l&eacute;ments invisibles',
insert_anchor_title : 'Gestionnaire d\'ancre',
insert_anchor_name : 'Nom de l\'ancre',
theme_anchor_desc : 'Ins&eacute;rer/Modifier une ancre',
theme_insert_link_titlefield : 'Info-bulle',
theme_clipboard_msg : 'Pour des raisons de s&eacute;curit&eacute;, les fonctions « Copier », « Couper » et « Coller »\nne sont pas disponibles dans Mozilla et Firefox.\n\n\nVoulez-vous plus d\'information &agrave; ce sujet?\n',
theme_path : 'El&eacute;ment(s) en cours ',
cut_desc : 'Couper',
copy_desc : 'Copier',
paste_desc : 'Coller',
link_list : 'Lien de la liste',
image_list : 'Image de la liste',
browse : 'Naviguer',
image_props_desc : 'Propri&eacute;t&eacute;s de l\'image',
newdocument_desc : 'Nouveau document',
class_name : 'Classe CSS',
newdocument : 'Etes-vous s&ucirc;r de vouloir supprimer tout le contenu ?',
about_title : 'A propos de TinyMCE',
about : 'A propos',
license : 'License',
plugins : 'Extensions',
plugin : 'Extension',
author : 'Auteur',
version : 'Version',
loaded_plugins : 'Extensions install&eacute;es',
help : 'Aide',
not_set : '-- Ind&eacute;fini --',
close : 'Fermer',
toolbar_focus : 'Atteindre la barre d\'outils (Alt+Q), Atteindre l\'&eacute;diteur (Alt-Z), Atteindre l\'&eacute;l&eacute;ment en cours (Alt-X)',
invalid_data : 'Erreur: La valeur en rouge est incorrecte.',
more_colors : 'Plus de couleurs',
color_picker_tab : 'Pipette',
color_picker : 'Palette de couleur',
web_colors_tab : 'S&eacute;curis&eacute; pour le web',
web_colors : 'Couleur s&eacute;curis&eacute;e pour le web',
named_colors_tab : 'Nom',
named_colors : 'Nom de la couleur',
color : 'Couleur:',
color_name : 'Nom:'
});
