/**
 * IT lang variables
 * 
 * Author : Luciano Vernaschi <luciano@virgilio.it>
 * Last Updated : Mar. 1st, 2007
 * TinyMCE Version : 2.1.0
 */

tinyMCE.addToLang('',{
theme_style_select : '-- Stili --',
theme_code_desc : 'Modifica codice HTML',
theme_code_title : 'Editor HTML',
theme_code_wordwrap : 'A capo',
theme_sub_desc : 'Apice',
theme_sup_desc : 'Pedice',
theme_hr_desc : 'Inserisci riga orizzontale',
theme_removeformat_desc : 'Rimuovi formattazione',
theme_custom1_desc : 'La tua descrizione personalizzata',
insert_image_border : 'Bordo',
insert_image_dimensions : 'Dimensioni',
insert_image_vspace : 'Spaziatura verticale',
insert_image_hspace : 'Spaziatura orizzontale',
insert_image_align : 'Allineamento',
insert_image_align_default : '-- Non impostato --',
insert_image_align_baseline : 'Alla base',
insert_image_align_top : 'In alto',
insert_image_align_middle : 'In mezzo',
insert_image_align_bottom : 'In basso',
insert_image_align_texttop : 'In alto col testo',
insert_image_align_absmiddle : 'In mezzo (assoluto)',
insert_image_align_absbottom : 'In basso (assoluto)',
insert_image_align_left : 'A sinistra',
insert_image_align_right : 'A destra',
theme_font_size : '-- Dimensione --',
theme_fontdefault : '-- Font --',
theme_block : '-- Formato --',
theme_paragraph : 'Paragrafo',
theme_div : 'Div',
theme_address : 'Indirizzo',
theme_pre : 'Preformattato',
theme_h1 : 'Intestazione 1',
theme_h2 : 'Intestazione 2',
theme_h3 : 'Intestazione 3',
theme_h4 : 'Intestazione 4',
theme_h5 : 'Intestazione 5',
theme_h6 : 'Intestazione 6',
theme_blockquote : 'Blockquote',
theme_code : 'Codice',
theme_samp : 'Esempio di codice',
theme_dt : 'Definizione',
theme_dd : 'Descrizione di definizione',
theme_colorpicker_title : 'Seleziona un colore',
theme_colorpicker_apply : 'Applica',
theme_forecolor_desc : 'Seleziona il colore del testo',
theme_backcolor_desc : 'Seleziona il colore di sfondo',
theme_charmap_title : 'Seleziona un carattere personalizzato',
theme_charmap_desc : 'Inserisci un carattere personalizzato',
theme_visualaid_desc : 'Abilita o disabilita guide visuali',
insert_anchor_title : 'Inserisci o modifica un\'ancora',
insert_anchor_name : 'Nome dell\'ancora',
theme_anchor_desc : 'Inserisci o modifica l\'ancora',
theme_insert_link_titlefield : 'Titolo',
theme_clipboard_msg : 'Le operazioni di taglia, copia e incolla non sono disponibili in Firefox. Vuoi ricevere ulteriori informazioni al riguardo?',
theme_path : 'Percorso',
cut_desc : 'Taglia',
copy_desc : 'Copia',
paste_desc : 'Incolla',
link_list : 'Lista di link',
image_list : 'Lista di immagini',
browse : 'Sfoglia',
image_props_desc : 'Propriet&agrave; dell\'immagine',
newdocument_desc : 'Nuovo documento',
class_name : 'Classe',
newdocument : 'Sei sicuro di voler cancellare tutto?',
about_title : 'Informazioni su TinyMCE',
about : 'Informazioni',
license : 'Licenza',
plugins : 'Plugin',
plugin : 'Plugin',
author : 'Autore',
version : 'Versione',
loaded_plugins : 'Plugin caricati',
help : 'Aiuto',
not_set : '-- Non impostato --',
close : 'Chiudi',
toolbar_focus : 'Passa ai bottoni - Alt+Q, Passa all\'editor - Alt-Z, Passa al percorso - Alt-X',
invalid_data : 'Errore: introdotti valori non validi (sono indicati in rosso).',
more_colors : 'Pi&ugrave; colori',
color_picker_tab : 'Selettore',
color_picker : 'Selettore di colori',
web_colors_tab : 'Web safe',
web_colors : 'Colori web safe',
named_colors_tab : 'Per nome',
named_colors : 'Colori per nome',
color : 'Colore:',
color_name : 'Nome:',
theme_advanced_anchor_delta_width : 25
});
