// JA lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- スタイル --',
theme_code_desc : 'HTMLで編集する',
theme_code_title : 'HTMLの編集',
theme_code_wordwrap : '折り返し',
theme_sub_desc : '下付き',
theme_sup_desc : '上付き',
theme_hr_desc : '水平線を挿入する',
theme_removeformat_desc : '書式を削除する',
theme_custom1_desc : 'Your custom description here',
insert_image_border : '枠線',
insert_image_dimensions : 'サイズ',
insert_image_vspace : '垂直方向の余白',
insert_image_hspace : '水平方向の余白',
insert_image_align : '表示位置',
insert_image_align_default : '-- 指定しない --',
insert_image_align_baseline : '文字の下端に揃える',
insert_image_align_top : '上に揃える',
insert_image_align_middle : '中央に揃える',
insert_image_align_bottom : '下に揃える',
insert_image_align_texttop : '文字の上端に揃える',
insert_image_align_absmiddle : '中央に揃える（絶対位置）',
insert_image_align_absbottom : '下に揃える（絶対位置）',
insert_image_align_left : '左に揃える',
insert_image_align_right : '右に揃える',
theme_font_size : '-- フォントサイズ --',
theme_fontdefault : '-- フォントの種類 --',
theme_block : '-- 書式 --',
theme_paragraph : '標準（&lt;P&gt;）',
theme_div : 'グループ（&lt;DIV&gt;）',
theme_address : 'シグネチャ（&lt;ADDRESS&gt;）',
theme_pre : '整形済み（&lt;PRE&gt;）',
theme_h1 : '見出し１（&lt;H1&gt;）',
theme_h2 : '見出し２（&lt;H2&gt;）',
theme_h3 : '見出し３（&lt;H3&gt;）',
theme_h4 : '見出し４（&lt;H4&gt;）',
theme_h5 : '見出し５（&lt;H5&gt;）',
theme_h6 : '見出し６（&lt;H6&gt;）',
theme_blockquote : '引用（&lt;BLOCKQUOTE&gt;）',
theme_code : 'コード（&lt;CODE&gt;）',
theme_samp : 'サンプルコード（&lt;SAMP&gt;）',
theme_dt : '定義語（&lt;DT&gt;）',
theme_dd : '定義の説明（&lt;DD&gt;）',
theme_colorpicker_title : '色の選択',
theme_colorpicker_apply : '選択',
theme_forecolor_desc : '文字色の選択',
theme_backcolor_desc : '背景色の選択',
theme_charmap_title : '記号の選択',
theme_charmap_desc : '記号の挿入',
theme_visualaid_desc : 'ガイドライン／非表示部品の表示を切り替える',
insert_anchor_title : 'しおりの編集',
insert_anchor_name : '名前',
theme_anchor_desc : 'しおりの追加',
theme_insert_link_titlefield : 'タイトル',
theme_clipboard_msg : 'コピー/切り取り/貼り付けはMozillaまたはFirefoxでは使用できません\nこの警告に関する詳細情報を表示しますか？',
theme_path : 'パス',
cut_desc : '切り取り',
copy_desc : 'コピー',
paste_desc : '貼り付け',
link_list : 'ハイパーリンクの一覧',
image_list : '画像の一覧',
browse : 'ブラウズ',
image_props_desc : '画像のプロパティ',
newdocument_desc : '新しい文書の作成',
class_name : 'クラス',
newdocument : '編集中の文書を破棄してもよろしいですか？',
about_title : 'TinyMCEについて',
about : 'TinyMCEについて',
license : 'ライセンス',
plugins : 'プラグイン',
plugin : 'プラグイン',
author : '作成者',
version : 'バージョン',
loaded_plugins : '読み込み済みのプラグイン',
help : 'ヘルプ',
not_set : '-- 未設定 --',
close : '閉じる',
toolbar_focus : 'ツールバーへ移動 - Alt+Q, エディタへ移動 - Alt-Z, エレメントパスへ移動 - Alt-X',
invalid_data : 'エラー：正しくない値が入力されました。赤く表示してある項目を修正してください'
});
