// 日本語 japanese utf-8 lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- スタイル --',
theme_code_desc : 'ソースを編集',
theme_code_title : 'HTML ソース編集',
theme_code_wordwrap : '右端で折り返す',
theme_sub_desc : '下付き',
theme_sup_desc : '上付き',
theme_hr_desc : '水平面線を挿入',
theme_removeformat_desc : 'フォーマットを取消す',
theme_custom1_desc : '独自の説明がここ',
insert_image_border : 'ボーダー',
insert_image_dimensions : '寸法',
insert_image_vspace : '縦間隔',
insert_image_hspace : '横間隔',
insert_image_align : '揃え',
insert_image_align_default : '--デフォルト--',
insert_image_align_baseline : 'ベースライン',
insert_image_align_top : '上',
insert_image_align_middle : '中央',
insert_image_align_bottom : '下',
insert_image_align_texttop : 'テキスト上部',
insert_image_align_absmiddle : '中央 (絶対的)',
insert_image_align_absbottom : '下部 (絶対的)',
insert_image_align_left : '左',
insert_image_align_right : '右',
theme_font_size : '-- フォントサイズ --',
theme_fontdefault : '-- フォントファミリ --',
theme_block : '--フォーマット--',
theme_paragraph : '段落',
theme_div : 'Div',
theme_address : 'アドレス',
theme_pre : '書式あり',
theme_h1 : 'ヘッダ 1',
theme_h2 : 'ヘッダ 2',
theme_h3 : 'ヘッダ 3',
theme_h4 : 'ヘッダ 4',
theme_h5 : 'ヘッダ 5',
theme_h6 : 'ヘッダ 6',
theme_colorpicker_title : '色を選択',
theme_colorpicker_apply : '適応',
theme_forecolor_desc : '文字色を選択',
theme_backcolor_desc : '背景色を選択',
theme_charmap_title : '特殊文字を選択',
theme_charmap_desc : '特殊文字を挿入',
theme_visualaid_desc : '隠れたガイドをトグル',
insert_anchor_title : 'アンカーを挿入・編集',
insert_anchor_name : 'アンカー名',
theme_anchor_desc : 'アンカーを挿入・編集',
theme_insert_link_titlefield : 'タイトル',
theme_clipboard_msg : 'コピー、切り取り、貼り付けがFirefoxに利用できません。\n詳しくしりたい?',
theme_path : 'パース',
cut_desc : '切り取り',
copy_desc : 'コピー',
paste_desc : '貼り付け',
link_list : 'リンクのリスト',
image_list : 'イメージのリスト',
browse : 'ブラウズ',
image_props_desc : 'イメージのプロパティ',
newdocument_desc : '新規',
class_name : 'クラス',
newdocument : '全てを削除?',
about_title : 'TinyMCEについて',
about : 'TinyMCEについて',
license : 'ライセンス',
plugins : 'プラグイン',
plugin : 'プラグイン',
author : '作者',
version : 'バージョン',
loaded_plugins : '有効なプラグイン',
help : 'ヘルプ',
not_set : '-- 設定されていない --',
close : '閉じる',
toolbar_focus : 'ツールへ - Alt+Q, エディターへ - Alt-Z, パスへ - Alt-X'
});
