// PL lang variables
// fixed by Wooya
// http://www.mfusion.prv.pl
// fixed by lemiel 14.11.2005

tinyMCE.addToLang('',{
theme_style_select : 'Styl',
theme_code_desc : 'Edytuj zróddło html',
theme_code_title : 'Edytor zródła html',
theme_code_wordwrap : 'Zawijanie wierszy',
theme_sub_desc : 'Nadpisywanie',
theme_sup_desc : 'Podpisywanie',
theme_hr_desc : 'Wstaw poziomą linię',
theme_removeformat_desc : 'Usuń formatowanie',
theme_custom1_desc : 'Wstaw własny opis',
insert_image_border : 'Ramka',
insert_image_dimensions : 'Wymiary',
insert_image_vspace : 'Pionowy odstęp',
insert_image_hspace : 'Poziomy odstęp',
insert_image_align : 'Otaczanie',
insert_image_align_default : 'Domyślne',
insert_image_align_baseline : 'Do linii bazowej',
insert_image_align_top : 'Górne',
insert_image_align_middle : '¦rodkowe',
insert_image_align_bottom : 'Dolne',
insert_image_align_texttop : 'Tekst powyżej',
insert_image_align_absmiddle : 'Absolutny środek',
insert_image_align_absbottom : 'Absolutny dół',
insert_image_align_left : 'Lewe',
insert_image_align_right : 'Prawe',
theme_font_size : '-- Rozmiar czcionki --',
theme_fontdefault : '-- Rodzina czcionki --',
theme_block : '-- Format --',
theme_paragraph : '-- Paragraf --',
theme_div : 'Div',
theme_address : 'Adres',
theme_pre : 'Preformatowanie',
theme_h1 : 'Nagłówek 1',
theme_h2 : 'Nagłówek 2',
theme_h3 : 'Nagłówek 3',
theme_h4 : 'Nagłówek 4',
theme_h5 : 'Nagłówek 5',
theme_h6 : 'Nagłówek 6',
theme_colorpicker_title : 'Wybierz kolor',
theme_colorpicker_apply : 'Wybierz',
theme_forecolor_desc : 'Wybierz kolor tekstu',
theme_backcolor_desc : 'Wybierz kolor tła',
theme_charmap_title : 'Wybierz znak',
theme_charmap_desc : 'Wstaw znak',
theme_visualaid_desc : 'Przełącz linie prowadzące/niewidoczne elementy',
insert_anchor_title : 'Kotwica',
insert_anchor_name : 'Nazwa kotwicy',
theme_anchor_desc : 'Wstaw/Edytuj kotwicę',
theme_insert_link_titlefield : 'Tytuł',
theme_clipboard_msg : 'Kopiuj/Edytuj/Wklej nie jest dostępne w przeglądarkach Mozilla i Firefox.\nPotrzebujesz więcej informacji na ten temat?',
theme_path : 'Ścieżka',
cut_desc : 'Wytnij',
copy_desc : 'Kopiuj',
paste_desc : 'Wklej',
link_list : 'Lista linków',
image_list : 'Lista obrazków',
browse : 'Przeglądaj',
image_props_desc : 'Właściwosci obrazka',
newdocument_desc : 'Nowy dokument',
class_name : 'Klasa',
newdocument : 'Czy jesteś pewien, że chcesz wyczyścić zawartość tego dokumentu?',
about_title : 'O TinyMCE ...',
about : 'O ...',
license : 'Licencja',
plugins : 'Pluginy',
plugin : 'Plugin',
author : 'Autor',
version : 'Wersja',
loaded_plugins : 'Załadowane pluginy',
help : 'Pomoc',
not_set : '-- Nie wybrano --',
close : 'Zamknij',
toolbar_focus : 'Skocz do przycisków narzędzi - Alt+Q, Skocz do edytora - Alt-Z, Skocz do ścieżki elementu - Alt-X'
});
