/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Author
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * First Release : November 26, 2005 - TinyMCE Version : 2.0RC4
 * Last Updated : November 20, 2006 - TinyMCE Version : 2.0.8
 */
tinyMCE.addToLang('',{
theme_style_select : 'Estilos',
theme_code_desc : 'Editar C&oacute;digo HTML',
theme_code_title : 'Editor de C&oacute;digo HTML',
theme_code_wordwrap : 'Quebrar Linhas',
theme_sub_desc : 'Subscrito',
theme_sup_desc : 'Subrescrito',
theme_hr_desc : 'Inserir linha horizontal',
theme_removeformat_desc : 'Remover formata&ccedil;&atilde;o',
theme_custom1_desc : 'Sua descri&ccedil;&atilde;o personalizada aqui',
insert_image_border : 'Borda',
insert_image_dimensions : 'Dimens&otilde;es',
insert_image_vspace : 'Espa&ccedil;o Vertical',
insert_image_hspace : 'Espa&ccedil;o Horizontal',
insert_image_align : 'Alinhamento',
insert_image_align_default : 'Padr&atilde;o',
insert_image_align_baseline : 'Linha base',
insert_image_align_top : 'Topo',
insert_image_align_middle : 'Centro',
insert_image_align_bottom : 'Fundo',
insert_image_align_texttop : 'Texto ao Topo',
insert_image_align_absmiddle : 'Centro Absoluto',
insert_image_align_absbottom : 'Fundo Absoluto',
insert_image_align_left : 'Esquerda',
insert_image_align_right : 'Direita',
theme_font_size : '-- Corpo --',
theme_fontdefault : '-- Tipo de Fonte --',
theme_block : '-- Formato --',
theme_paragraph : 'Par&aacute;grafo',
theme_div : 'Div',
theme_address : 'Endere&ccedil;o',
theme_pre : 'Pr&eacute;-formatado',
theme_h1 : 'Cabe&ccedil;alho 1',
theme_h2 : 'Cabe&ccedil;alho 2',
theme_h3 : 'Cabe&ccedil;alho 3',
theme_h4 : 'Cabe&ccedil;alho 4',
theme_h5 : 'Cabe&ccedil;alho 5',
theme_h6 : 'Cabe&ccedil;alho 6',
theme_colorpicker_title : 'Selecionar c&ocirc;r',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Selecionar c&ocirc;r do texto',
theme_backcolor_desc : 'Selecionar c&ocirc;r de fundo',
theme_charmap_title : 'Selecionar caracter especial',
theme_charmap_desc : 'Inserir caracter especial',
theme_charmap_alpha_desc : 'Caracteres alfab&eacute;ticos',
theme_charmap_arrows_title : 'Flechas',
theme_charmap_arrows_desc : 'Caracteres de flechas',
theme_charmap_greek_title : 'Gregos',
theme_charmap_greek_desc : 'Caracteres Gregos',
theme_charmap_math_title : 'Mathematicos',
theme_charmap_math_desc : 'Caracteres mathematicos',
theme_charmap_misc_title : 'Diversos',
theme_charmap_misc_desc : 'Caracteres diversos',
theme_charmap_money_title : 'Moedas',
theme_charmap_money_desc : 'Caracteres de moedas',
theme_charmap_quotaion_title : 'Ap&oacute;strofes',
theme_charmap_quotaion_desc : 'Caracteres de Ap&oacute;strofe',
theme_visualaid_desc : 'Trocar as linhas de ajuda por elementos invis&iacute;veis',
insert_anchor_title : 'Inserir/editar &acirc;ncora',
insert_anchor_name : 'Nome da &acirc;ncora',
theme_anchor_desc : 'Inserir/editar &acirc;ncora',
theme_insert_link_titlefield : 'T&iacute;tulo',
theme_clipboard_msg : 'N&atilde;o se pode utiliza os comando de Copiar / Cortar / Colar no Mozilla e Firefox.\r\nUse o teclado para Copiar (Ctrl+C) / Cortar (Ctrl+X) / Colar (Ctrl+V)\r\nQuer obter mais informa&ccedil;&atilde;o?',
theme_path : 'Rota',
cut_desc : 'Cortar (Ctrl+X)',
copy_desc : 'Copiar (Ctrl+C)',
paste_desc : 'Colar (Ctrl+V)',
link_list : 'Lista de links',
image_list : 'Lista de imagens',
browse : 'Navegar',
image_props_desc : 'Propriedades da imagem',
newdocument_desc : 'Novo documento',
class_name : 'Classe',
newdocument : 'Tem certesa que deseja apagar todo o conte&uacute;do?',
about_title : 'Sobre o TinyMCE',
about : 'Sobre',
license : 'Licen&ccedil;a',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Autor',
version : 'Vers&atilde;o',
loaded_plugins : 'Plugins carregados',
help : 'Ajuda',
not_set : '-- Por padr&atilde;o --',
close : 'Fechar',
toolbar_focus : 'Ir para a barra de ferramentas - Alt+Q, Ir para o editor - Alt+Z, Ir para o elemento de destino - Alt+X',
theme_visualaid_desc : 'Tornar linhas vis&iacute;veis/invis&iacute;veis',
insert_anchor_title : 'Inserir/editar &acirc;ncora',
insert_anchor_name : 'Nome da &acirc;ncora',
theme_anchor_desc : 'Inserir/editar &acirc;ncora',
theme_insert_link_titlefield : 'T&iacute;tulo',
theme_clipboard_msg : 'Copiar/Recortar/Colar n&atilde;o &eacute; permitido no Mozilla e Firefox.\nQuer mais informa&ccedil;&otilde;es sobre isso?',
theme_path : 'Caminho',
cut_desc : 'Recortar',
copy_desc : 'Copiar',
paste_desc : 'Colar',
link_list : 'Lista de Links',
image_list : 'Lista de Imagens',
browse : 'Navegar',
image_props_desc : 'Propriedades da Imagem',
newdocument_desc : 'Novo Documento',
class_name : 'Classe',
newdocument : 'Tem certeza que deseja limpar todo o conte&uacute;do?',
theme_advanced_anchor_delta_width : 20
});
