/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Author
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * First Release : November 26, 2005 - TinyMCE Version : 2.0RC4
 * Last Updated : November 20, 2006 - TinyMCE Version : 2.0.8
 */
tinyMCE.addToLang('',{
theme_style_select : 'Estilos',
theme_code_desc : 'Editar código HTML',
theme_code_title : 'Editor de código HTML',
theme_code_wordwrap : 'Quebrar linhas',
theme_sub_desc : 'Subscrito',
theme_sup_desc : 'Sobrescrito',
theme_hr_desc : 'Inserir linha horizontal',
theme_removeformat_desc : 'Remover formatação',
theme_custom1_desc : 'Sua descrição personalizada aqui',
insert_image_border : 'Borda',
insert_image_dimensions : 'Dimensões',
insert_image_vspace : 'Espaço vertical',
insert_image_hspace : 'Espaço horizontal',
insert_image_align : 'Alinhamento',
insert_image_align_default : 'Padrão',
insert_image_align_baseline : 'Linha base',
insert_image_align_top : 'Topo',
insert_image_align_middle : 'Centro',
insert_image_align_bottom : 'Fundo',
insert_image_align_texttop : 'Texto ao topo',
insert_image_align_absmiddle : 'Centro absoluto',
insert_image_align_absbottom : 'Fundo absoluto',
insert_image_align_left : 'Esquerda',
insert_image_align_right : 'Direita',
theme_font_size : '-- Tamanho --',
theme_fontdefault : '-- Tipo de fonte --',
theme_block : '-- Formato --',
theme_paragraph : 'Parágrafo',
theme_div : 'Div',
theme_address : 'Endereço',
theme_pre : 'Pré-formatado',
theme_h1 : 'Cabeçalho 1',
theme_h2 : 'Cabeçalho 2',
theme_h3 : 'Cabeçalho 3',
theme_h4 : 'Cabeçalho 4',
theme_h5 : 'Cabeçalho 5',
theme_h6 : 'Cabeçalho 6',
theme_blockquote : 'Blockquote',
theme_code : 'Code',
theme_samp : 'Code sample',
theme_dt : 'Definition term ',
theme_dd : 'Definition description',
theme_colorpicker_title : 'Selecionar cor',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Selecionar cor do texto',
theme_backcolor_desc : 'Selecionar cor de fundo',
theme_charmap_title : 'Selecionar caracter especial',
theme_charmap_desc : 'Inserir caracter especial',
theme_visualaid_desc : 'Trocar as linhas de ajuda por elementos invisíveis',
insert_anchor_title : 'Inserir/editar âncora',
insert_anchor_name : 'Nome da âncora',
theme_anchor_desc : 'Inserir/editar âncora',
theme_insert_link_titlefield : 'Título',
theme_clipboard_msg : 'Não se pode utilizar os comandos de copiar/recortar/colar no Mozilla e Firefox.\r\nUse o teclado para copiar(Ctrl+C)/ cortar(Ctrl+X)/ colar(Ctrl+V)\r\nQuer obter mais informação?',
theme_path : 'Caminho',
cut_desc : 'Recortar (Ctrl+X)',
copy_desc : 'Copiar (Ctrl+C)',
paste_desc : 'Colar (Ctrl+V)',
link_list : 'Lista de links',
image_list : 'Lista de imagens',
browse : 'Navegar',
image_props_desc : 'Propriedades da imagem',
newdocument_desc : 'Novo documento',
class_name : 'Classe',
newdocument : 'Tem certeza que deseja apagar todo o conteúdo?',
about_title : 'Sobre o TinyMCE',
about : 'Sobre',
license : 'Licença',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Autor',
version : 'Versão',
loaded_plugins : 'Plugins carregados',
help : 'Ajuda',
not_set : '-- Por padrão --',
close : 'Fechar',
toolbar_focus : 'Ir para a barra de ferramentas(Alt+Q), Ir para o editor(Alt+Z), Ir para o elemento de destino(Alt+X)',
invalid_data : 'Erro: há valores inválidos e estão marcados em vermelho.',
more_colors : 'Mais cores',
color_picker_tab : 'Conta-gota',
color_picker : 'Conta-gota',
web_colors_tab : 'Web segura',
web_colors : 'Cores web segura',
named_colors_tab : 'Nomeadas',
named_colors : 'Cores nomeadas',
color : 'Cor:',
color_name : 'Nome:',
theme_advanced_anchor_delta_width : 20
});
