// RO lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stiluri --',
theme_code_desc : 'Editare surs&#259; HTML',
theme_code_title : 'Editor surs&#259; HTML',
theme_code_wordwrap : 'T&#259;iere cuvinte',
theme_sub_desc : 'Subscript',
theme_sup_desc : 'Superscript',
theme_hr_desc : 'Inserare rigl&#259; orizontal&#259;',
theme_removeformat_desc : 'Elimin&#259; formatarea',
theme_custom1_desc : 'Descrierea personalizat&#259; aici',
insert_image_border : 'Margine',
insert_image_dimensions : 'Dimensiuni',
insert_image_vspace : 'Spa&#355;iu vertical',
insert_image_hspace : 'Spa&#355;iu orizontal',
insert_image_align : 'Aliniament',
insert_image_align_default : '-- Nestabilit --',
insert_image_align_baseline : 'Linie de baz&#259;',
insert_image_align_top : 'Sus',
insert_image_align_middle : 'Mijloc',
insert_image_align_bottom : 'Jos',
insert_image_align_texttop : 'TextSus',
insert_image_align_absmiddle : 'Mijloc absolut',
insert_image_align_absbottom : 'Jos absolut',
insert_image_align_left : 'St&#226;nga',
insert_image_align_right : 'Dreapta',
theme_font_size : '-- Dimensiune font --',
theme_fontdefault : '-- Familie font --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Adres&#259;',
theme_pre : 'Preformatat',
theme_h1 : 'Aliniament 1',
theme_h2 : 'Aliniament 2',
theme_h3 : 'Aliniament 3',
theme_h4 : 'Aliniament 4',
theme_h5 : 'Aliniament 5',
theme_h6 : 'Aliniament 6',
theme_colorpicker_title : 'Alege o culoare',
theme_colorpicker_apply : 'Aplic&#259;',
theme_forecolor_desc : 'Alege culoarea textului',
theme_backcolor_desc : 'Alege culoarea fundalului',
theme_charmap_title : 'Alege caractere personalizate',
theme_charmap_desc : 'Insereaz&#259; caracter personalizat',
theme_visualaid_desc : 'Comut&#259; ghidajele/elementele invizibile',
insert_anchor_title : 'Insereaz&#259;/editeaz&#259; ancor&#259;',
insert_anchor_name : 'Nume ancor&#259;',
theme_anchor_desc : 'Insereaz&#259;/editeaz&#259; ancor&#259;',
theme_insert_link_titlefield : 'Titlu',
theme_clipboard_msg : 'Copierea/T&#259;ierea/Lipirea nu sunt disponibile &#238;n Mozilla &#351;i Firefox.\nVrei mai multe informa&#355;ii despre acest lucru?',
theme_path : 'Cale',
cut_desc : 'Taie',
copy_desc : 'Copiaz&#259;',
paste_desc : 'Lipe&#351;te',
link_list : 'List&#259; de leg&#259;turi',
image_list : 'List&#259; de imagini',
browse : 'R&#259;sfoie&#351;te',
image_props_desc : 'Propriet&#259;&#355;i imagine',
newdocument_desc : 'Document nou',
class_name : 'Clas&#259;',
newdocument : 'E&#351;ti sigur c&#259; vrei s&#259; cure&#355;i &#238;ntregul con&#355;inut?',
about_title : 'Despre TinyMCE',
about : 'Despre',
license : 'Licen&#355;&#259;',
plugins : 'Plugin-uri',
plugin : 'Plugin',
author : 'Autor',
version : 'Versiune',
loaded_plugins : 'Plugin-uri &#238;nc&#259;rcate',
help : 'Ajutor',
not_set : '-- Nestabilit --',
close : '&#206;nchide',
toolbar_focus : 'Salt la butoanele unelte - Alt+Q, Salt la editor - Alt-Z, Salt la cale elemente - Alt-X'
});
