// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stilet --',
theme_code_desc : 'Ndrysho kodin HTML',
theme_code_title : 'Ndryshues i kodit HTML',
theme_code_wordwrap : 'Shko sipas fjales',
theme_sub_desc : 'Nenshkrim',
theme_sup_desc : 'Mbishkrim',
theme_hr_desc : 'Nderfut vizore horizontale',
theme_removeformat_desc : 'Hiq formatimin',
theme_custom1_desc : 'Pershkrimi juaj ketu',
insert_image_border : 'Kufiri',
insert_image_dimensions : 'Dimensionet',
insert_image_vspace : 'Hapesira vertikale',
insert_image_hspace : 'Hapesira horizontal',
insert_image_align : 'Perngjitja',
insert_image_align_default : '-- I pacaktuar --',
insert_image_align_baseline : 'Linja baze',
insert_image_align_top : 'Siper',
insert_image_align_middle : 'Mes',
insert_image_align_bottom : 'Poshte',
insert_image_align_texttop : 'Mbi Tekst',
insert_image_align_absmiddle : 'Mesi Absolut',
insert_image_align_absbottom : 'Poshte Absolut',
insert_image_align_left : 'Majtas',
insert_image_align_right : 'Djathas',
theme_font_size : '-- Madhesia e fontit --',
theme_fontdefault : '-- Familja e fonteve --',
theme_block : '-- Formati --',
theme_paragraph : 'Paragrafi',
theme_div : 'Divizion',
theme_address : 'Adresa',
theme_pre : 'Para-formatuar',
theme_h1 : 'Koke 1',
theme_h2 : 'Koke 2',
theme_h3 : 'Koke 3',
theme_h4 : 'Koke 4',
theme_h5 : 'Koke 5',
theme_h6 : 'Koke 6',
theme_blockquote : 'Thonjez',
theme_code : 'Kod',
theme_samp : 'Shembull Kodi',
theme_dt : 'Term i percaktimit',
theme_dd : 'Pershkrim i percaktimit',
theme_colorpicker_title : 'Zgjidh nje ngjyre',
theme_colorpicker_apply : 'Apliko',
theme_forecolor_desc : 'Zgjidh nje ngjyre teksti',
theme_backcolor_desc : 'Zgjidh nje ngjyre sfondi',
theme_charmap_title : 'Zgjidh nje karakter special',
theme_charmap_desc : 'Nderfut nje karakter special',
theme_visualaid_desc : 'Cakto vizat drejtuese/elemntet e padukshem',
insert_anchor_title : 'Nderfut/ndrysho caktues',
insert_anchor_name : 'Emri i caktuesit',
theme_anchor_desc : 'Nderfut/ndrysho caktues',
theme_insert_link_titlefield : 'Titulli',
theme_clipboard_msg : '?',
theme_path : 'Rruga',
cut_desc : 'Prij',
copy_desc : 'Kopjo',
paste_desc : 'Ngjit',
link_list : 'Liste lidhjesh',
image_list : 'Liste imazhesh',
browse : 'Kerko',
image_props_desc : 'Te dhenat e imazhit',
newdocument_desc : 'Dokument i ri',
class_name : 'Klasa',
newdocument : 'Jeni i sigurte se doni ta pastroni permbajtjen?',
about_title : 'Rreth TinyMCE',
about : 'Rreth',
license : 'Liçensa',
plugins : 'Pluginet',
plugin : 'Plugin',
author : 'Autori',
version : 'Versioni',
loaded_plugins : 'Pluginet e ngarkuara',
help : 'Ndihme',
not_set : '-- i pa caktuar --',
close : 'Mbyll',
toolbar_focus : 'Kerce tek butonat - Alt+Q, kerce tek ndryshuesi - Alt-Z, Kerce tek ruga e elementeve - Alt-X'
});