// Serbian (SR) lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stilovi --',
theme_code_desc : 'Promena HTML Koda',
theme_code_title : 'HTML Kod Editor',
theme_code_wordwrap : 'Prelamanje teksta',
theme_sub_desc : 'Subscript',
theme_sup_desc : 'Superscript',
theme_hr_desc : 'Ubacivanje horizontalnog lenjira',
theme_removeformat_desc : 'Brisanje formatiranja',
theme_custom1_desc : 'Vaš opis ovde',
insert_image_border : 'Okvir',
insert_image_dimensions : 'Dimenzije',
insert_image_vspace : 'Vertikalni prostor',
insert_image_hspace : 'Horizontalni prostor',
insert_image_align : 'Poravnanje',
insert_image_align_default : '-- Nije podešeno --',
insert_image_align_baseline : 'Donja linija',
insert_image_align_top : 'Vrh',
insert_image_align_middle : 'Sredina',
insert_image_align_bottom : 'Dno',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Apsolutna sredina',
insert_image_align_absbottom : 'Apsolutno dno',
insert_image_align_left : 'Levo',
insert_image_align_right : 'Desno',
theme_font_size : '-- Veličina fonta --',
theme_fontdefault : '-- Font familija --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Adresa',
theme_pre : 'Preformatirano',
theme_h1 : 'Heading 1',
theme_h2 : 'Heading 2',
theme_h3 : 'Heading 3',
theme_h4 : 'Heading 4',
theme_h5 : 'Heading 5',
theme_h6 : 'Heading 6',
theme_blockquote : 'Blockquote',
theme_code : 'Kod',
theme_samp : 'Kod primer',
theme_dt : 'Izraz za definiciju ',
theme_dd : 'Opis definicije',
theme_colorpicker_title : 'Izaberite boju',
theme_colorpicker_apply : 'Primena',
theme_forecolor_desc : 'Odaberite boju teksta',
theme_backcolor_desc : 'Odaberite pozadinsku boju',
theme_charmap_title : 'Odaberite proizvoljni karakter',
theme_charmap_desc : 'Ubacite proizvoljni karakter',
theme_visualaid_desc : 'Linije vodilje/nevidljivi elementi',
insert_anchor_title : 'Ubacite/promenite link',
insert_anchor_name : 'Ime linka',
theme_anchor_desc : 'Ubacite/promenite link',
theme_insert_link_titlefield : 'Naslov',
theme_clipboard_msg : 'Copy/Cut/Paste nije moguće u Mozilli and Firefox-u.\nDa li želite više informacija o ovoj temi?',
theme_path : 'Putanja',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Lista linkova',
image_list : 'Lista slika',
browse : 'Pronadjite',
image_props_desc : 'Parametri slike',
newdocument_desc : 'Novi dokument',
class_name : 'Class',
newdocument : 'Da li ste sigurno da želite da izbrišete sav sadržaj?',
about_title : 'O TinyMCE editoru',
about : 'O editoru',
license : 'Licenca',
plugins : 'Pluginovi',
plugin : 'Plugin',
author : 'Autor',
version : 'Verzija',
loaded_plugins : 'Učitani pluginovi',
help : 'Pomoć',
not_set : '-- Nije podešeno --',
close : 'Zatvaranje',
toolbar_focus : 'Skok na dugmad za alate - Alt+Q, Skok na editor - Alt-Z, Skok na putanju elementa - Alt-X'
});
