// Ukrainian translation
tinyMCE.addToLang('',{
theme_style_select : '-- Стилі --',
theme_code_desc : 'Редагувати HTML коди',
theme_code_title : 'Редактор HTML кодів',
theme_code_wordwrap : 'Перенесення по словах',
theme_sub_desc : 'Нижній індекс',
theme_sup_desc : 'Верхній індекс',
theme_hr_desc : 'Вставити горизонтальний роздільник',
theme_removeformat_desc : 'Прибрати форматування',
theme_custom1_desc : 'Ваш довільний опис',
insert_image_border : 'Рамка',
insert_image_dimensions : 'Розміри',
insert_image_vspace : 'Вертикальний відступ',
insert_image_hspace : 'Горизонтальний відступ',
insert_image_align : 'Вирівнювання',
insert_image_align_default : '-- Не поставлено --',
insert_image_align_baseline : 'По базової лінії',
insert_image_align_top : 'Вгору',
insert_image_align_middle : 'До середини',
insert_image_align_bottom : 'Вниз',
insert_image_align_texttop : 'До гори тексту',
insert_image_align_absmiddle : 'До абсолютної середини',
insert_image_align_absbottom : 'До абсолютної гори',
insert_image_align_left : 'Вліво',
insert_image_align_right : 'Вправо',
theme_font_size : '-- Розмір шрифту --',
theme_fontdefault : '-- Сімейство шрифтів --',
theme_block : '-- Формат --',
theme_paragraph : 'Абзац',
theme_div : 'DivX',
theme_address : 'Стиль адреси',
theme_pre : ':`Попередньо форматированный',
theme_h1 : 'Заголовок 1',
theme_h2 : 'Заголовок 2',
theme_h3 : 'Заголовок 3',
theme_h4 : 'Заголовок 4',
theme_h5 : 'Заголовок 5',
theme_h6 : 'Заголовок 6',
theme_blockquote : 'Цитата',
theme_samp : 'Зразок коду',
theme_dt : 'Термін ',
theme_dd : 'Визначення терміна',
ttheme_colorpicker_title : 'Вибрати колір',
theme_colorpicker_apply : 'Застосувати',
theme_forecolor_desc : 'Вибрати колір тексту',
theme_backcolor_desc : 'Вибрати колір фону',
theme_charmap_title : 'Вибір довільного символу',
theme_charmap_desc : 'Вставити довільний символ',
theme_visualaid_desc : 'Показати межі прихованих елементів',
insert_anchor_title : 'Вставити/змінити якір',
insert_anchor_name : 'Ім\'я якоря',
theme_anchor_desc : 'Вставити/змінити якір',
theme_insert_link_titlefield : 'Заголовок',
theme_clipboard_msg : 'Копіювати/Вирізати/Вставити недоступні для Mozilla і Firefox.\nХочете дізнатися про це докладніше?',
theme_path : 'Шлях',
cut_desc : 'Вирізати',
copy_desc : 'Копіювати',
paste_desc : 'Вставити',
link_list : 'Перелік посилань',
image_list : 'Перелік картинок',
browse : 'Підібрати адекватні фігури',
image_props_desc : 'Властивості картинки',
newdocument_desc : 'Новий документ',
class_name : 'Клас',
newdocument : 'Ви абсолютно впевнені, що хочете очистити весь вміст?',
about_title : 'Про TinyMCE',
about : 'Про TinyMCE',
license : 'Ліцензія',
plugins : 'Плаґіни',
plugin : 'Плаґін',
author : 'Автор',
version : 'Версія',
loaded_plugins : 'Завантажені плаґіни',
help : 'Допомога',
not_set : '-- встановлено --',
close : 'Закрити',
toolbar_focus : 'Перемістити фокус на панель інструментів - Alt+Q, Перемістити фокус в редактор - Alt-Z, Перемістити фокус на елемент шляху - Alt-X',
invalid_data : 'Помилка: Введені некоректні значення, їх позначено червоним.',
more_colors : 'Ще кольору',
color_picker_tab : 'Вибір',
color_picker : 'Вибір кольорів',
web_colors_tab : 'Для веб',
web_colors : 'Кольори для веб',
named_colors_tab : 'Назви',
named_colors : 'Назви кольорів',
color : 'Колір:',
color_name : 'Назва:'
});
