// Ukrainian translation
tinyMCE.addToLang('',{
theme_style_select : '-- Стил╕ --',
theme_code_desc : 'Редагувати HTML коди',
theme_code_title : 'Редактор HTML код╕в',
theme_code_wordwrap : 'Перенесення по словах',
theme_sub_desc : 'Нижн╕й ╕ндекс',
theme_sup_desc : 'Верхн╕й ╕ндекс',
theme_hr_desc : 'Вставити горизонтальний розд╕льник',
theme_removeformat_desc : 'Прибрати форматування',
theme_custom1_desc : 'Ваш дов╕льний опис',
insert_image_border : 'Рамка',
insert_image_dimensions : 'Розм╕ри',
insert_image_vspace : 'Вертикальний в╕дступ',
insert_image_hspace : 'Горизонтальний в╕дступ',
insert_image_align : 'Вир╕внювання',
insert_image_align_default : '-- Не поставлено --',
insert_image_align_baseline : 'По базово╖ л╕н╕╖',
insert_image_align_top : 'Вгору',
insert_image_align_middle : 'До середини',
insert_image_align_bottom : 'Вниз',
insert_image_align_texttop : 'До гори тексту',
insert_image_align_absmiddle : 'До абсолютно╖ середини',
insert_image_align_absbottom : 'До абсолютно╖ гори',
insert_image_align_left : 'Вл╕во',
insert_image_align_right : 'Вправо',
theme_font_size : '-- Розм╕р шрифту --',
theme_fontdefault : '-- С╕мейство шрифт╕в --',
theme_block : '-- Формат --',
theme_paragraph : 'Абзац',
theme_div : 'DivX',
theme_address : 'Стиль адреси',
theme_pre : ':`Попередньо форматированный',
theme_h1 : 'Заголовок 1',
theme_h2 : 'Заголовок 2',
theme_h3 : 'Заголовок 3',
theme_h4 : 'Заголовок 4',
theme_h5 : 'Заголовок 5',
theme_h6 : 'Заголовок 6',
theme_blockquote : 'Цитата',
theme_samp : 'Зразок коду',
theme_dt : 'Терм╕н ',
theme_dd : 'Визначення терм╕на',
ttheme_colorpicker_title : 'Вибрати кол╕р',
theme_colorpicker_apply : 'Застосувати',
theme_forecolor_desc : 'Вибрати кол╕р тексту',
theme_backcolor_desc : 'Вибрати кол╕р фону',
theme_charmap_title : 'Виб╕р дов╕льного символу',
theme_charmap_desc : 'Вставити дов╕льний символ',
theme_visualaid_desc : 'Показати меж╕ прихованих елемент╕в',
insert_anchor_title : 'Вставити/зм╕нити як╕р',
insert_anchor_name : '╤м\'я якоря',
theme_anchor_desc : 'Вставити/зм╕нити як╕р',
theme_insert_link_titlefield : 'Заголовок',
theme_clipboard_msg : 'Коп╕ювати/Вир╕зати/Вставити недоступн╕ для Mozilla ╕ Firefox.\nХочете д╕знатися про це докладн╕ше?',
theme_path : 'Шлях',
cut_desc : 'Вир╕зати',
copy_desc : 'Коп╕ювати',
paste_desc : 'Вставити',
link_list : 'Перел╕к посилань',
image_list : 'Перел╕к картинок',
browse : 'П╕д╕брати адекватн╕ ф╕гури',
image_props_desc : 'Властивост╕ картинки',
newdocument_desc : 'Новий документ',
class_name : 'Клас',
newdocument : 'Ви абсолютно впевнен╕, що хочете очистити весь вм╕ст?',
about_title : 'Про TinyMCE',
about : 'Про TinyMCE',
license : 'Л╕ценз╕я',
plugins : 'Пла╜╕ни',
plugin : 'Пла╜╕н',
author : 'Автор',
version : 'Верс╕я',
loaded_plugins : 'Завантажен╕ пла╜╕ни',
help : 'Допомога',
not_set : '-- встановлено --',
close : 'Закрити',
toolbar_focus : 'Перем╕стити фокус на панель ╕нструмент╕в - Alt+Q, Перем╕стити фокус в редактор - Alt-Z, Перем╕стити фокус на елемент шляху - Alt-X',
invalid_data : 'Помилка: Введен╕ некоректн╕ значення, ╖х позначено червоним.',
more_colors : 'Ще кольору',
color_picker_tab : 'Виб╕р',
color_picker : 'Виб╕р кольор╕в',
web_colors_tab : 'Для веб',
web_colors : 'Кольори для веб',
named_colors_tab : 'Назви',
named_colors : 'Назви кольор╕в',
color : 'Кол╕р:',
color_name : 'Назва:'
});
