// Vietnamese lang variables - Đỗ Xuân Tiến - tiendx2002@yahoo.com Việt hóa

tinyMCE.addToLang('',{
theme_style_select : '-- Phong cách --',
theme_code_desc : 'Sửa mã nguồn HTML',
theme_code_title : 'Bộ soạn thảo mã HTML',
theme_code_wordwrap : 'Gói gọn các từ - Word wrap',
theme_sub_desc : 'Chỉ số dưới',
theme_sup_desc : 'Chỉ số trên',
theme_hr_desc : 'Thêm đường thẳng ngang',
theme_removeformat_desc : 'Xóa định dạng',
theme_custom1_desc : 'Mô tả của bạn ở đây',
insert_image_border : 'Khung',
insert_image_dimensions : 'Kích thước',
insert_image_vspace : 'Khoảng cách dọc',
insert_image_hspace : 'Khoảng cách ngang',
insert_image_align : 'Căn lề',
insert_image_align_default : '-- Chưa đặt --',
insert_image_align_baseline : 'Theo dòng',
insert_image_align_top : 'Trên cùng',
insert_image_align_middle : 'Giữa',
insert_image_align_bottom : 'Dưới cùng',
insert_image_align_texttop : 'Văn bản trên cùng',
insert_image_align_absmiddle : 'Tuyệt đối giữa',
insert_image_align_absbottom : 'Tuyệt đối dưới cùng',
insert_image_align_left : 'Trái',
insert_image_align_right : 'Phải',
theme_font_size : '-- Kích thước chữ --',
theme_fontdefault : '-- Font chữ --',
theme_block : '-- Định dạng --',
theme_paragraph : 'Đoạn',
theme_div : 'Div',
theme_address : 'Địa chỉ',
theme_pre : 'Định dạng trước',
theme_h1 : 'Tiêu đề cấp 1',
theme_h2 : 'Tiêu đề cấp 2',
theme_h3 : 'Tiêu đề cấp 3',
theme_h4 : 'Tiêu đề cấp 4',
theme_h5 : 'Tiêu đề cấp 5',
theme_h6 : 'Tiêu đề cấp 6',
theme_colorpicker_title : 'Chọn một màu',
theme_colorpicker_apply : 'Áp&nbsp;dụng',
theme_forecolor_desc : 'Chọn màu chữ',
theme_backcolor_desc : 'Chọn màu nền',
theme_charmap_title : 'Chọn ký tự đặc biệt',
theme_charmap_desc : 'Thêm ký tự đặc biệt',
theme_visualaid_desc : 'Bật tắt chế độ hướng dẫn',
insert_anchor_title : 'Thêm/sửa neo',
insert_anchor_name : 'Tên neo',
theme_anchor_desc : 'Thêm/sửa neo',
theme_insert_link_titlefield : 'Tiêu đề',
theme_clipboard_msg : 'Trên Mozilla và Firefox không sử dụng được các thao tác Sao chép/Cắt/Dán. \nBạn cần thêm thông tin về điều này?',
theme_path : 'Đường dẫn',
cut_desc : 'Cắt',
copy_desc : 'Sao chép',
paste_desc : 'Dán',
link_list : 'Danh sách liên kết',
image_list : 'Danh sách ảnh',
browse : 'Duyệt',
image_props_desc : 'Thuộc tính ảnh',
newdocument_desc : 'Văn bản mới',
class_name : 'Lớp',
newdocument : 'Bạn có chắc muốn xóa sạch nội dung?',
about_title : 'Thông tin về TinyMCE',
about : 'Thông tin',
license : 'Chứng nhận',
plugins : 'Chức năng',
plugin : 'Chức năng',
author : 'Tác giả',
version : 'Phiên bản',
loaded_plugins : 'Chức năng đã nạp',
help : 'Trợ giúp',
not_set : '-- Chưa đặt --',
close : 'Đóng',
toolbar_focus : 'Nút chuyển tới công cụ - Alt+Q, Chuyển tới bộ soạn thảo - Alt-Z, Chuyển tới đường dẫn thành phần - Alt-X'
});
