#!/bin/php
<?php
/**
 * ---------------------------------------------------------------------
 * GLPI - Gestionnaire Libre de Parc Informatique
 * Copyright (C) 2015-2017 Teclib' and contributors.
 *
 * http://glpi-project.org
 *
 * based on GLPI - Gestionnaire Libre de Parc Informatique
 * Copyright (C) 2003-2014 by the INDEPNET Development Team.
 *
 * ---------------------------------------------------------------------
 *
 * LICENSE
 *
 * This file is part of GLPI.
 *
 * GLPI is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * GLPI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GLPI. If not, see <http://www.gnu.org/licenses/>.
 * ---------------------------------------------------------------------
 */

function displayUsage() {
   die("usage: ".$_SERVER['argv'][0]." [ --file=main_styles ]\n");
}

chdir(__DIR__);

if (!defined('GLPI_ROOT')) {
   define('GLPI_ROOT', realpath('..'));
}

if ($_SERVER['argc']>1) {
   for ($i=1; $i<count($_SERVER['argv']); $i++) {
      $it           = explode("=", $argv[$i], 2);
      $it[0]        = preg_replace('/^--/', '', $it[0]);
      $args[$it[0]] = (isset($it[1]) ? $it[1] : true);
   }
}

include_once GLPI_ROOT . '/inc/includes.php';

//manage write path
$scssc_path = Html::getScssCompilePath(isset($args['file']) ? $args['file'] : 'main_styles');
$destdir    = $scssc_path['dir'];
$filename   = $scssc_path['file'];

if (!file_exists($destdir)) {
   mkdir($destdir);
} else if (!is_dir($destdir)) {
   throw new \RuntimeException('Check your dir parameter!');
}

//do not use caceh here
$args['nocache'] = true;
$css = Html::compileScss($args);

//write to file
file_put_contents($destdir . '/' . $filename, $css);
