tinyMCE.addI18n('sk.emotions_dlg',{
title:"Vlo\u017Ei\u0165 emotikonu",
desc:"Emotikony",
cool:"Namakan\u00FD",
cry:"Pla\u010D\u00FAci",
embarassed:"Zahanben\u00FD",
foot_in_mouth:"Top\u00E1nka v \u00FAstach",
frown:"Zamra\u010Den\u00FD",
innocent:"Nevinn\u00FD",
kiss:"Bozkaj\u00FAci",
laughing:"Smej\u00FAci sa",
money_mouth:"Koruny",
sealed:"Zape\u010Daten\u00FD",
smile:"Usmiaty",
surprised:"Prekvapen\u00FD",
tongue_out:"S vyplazen\u00FDm jazykom",
undecided:"Nerozhodn\u00FD",
wink:"\u017Dmurkaj\u00FAci",
yell:"Kri\u010Diaci"
});