tinyMCE.addI18n('tr.advanced_dlg',{
about_title:"TinyMCE Hakk\u0131n",
about_general:"Hakk\u0131n",
about_help:"Yard",
about_license:"Lisans",
about_plugins:"Eklentiler",
about_plugin:"Eklenti",
about_author:"Yazar",
about_version:"S\u00FC",
about_loaded:"Y\u00FCkl\u00FC eklent",
anchor_title:"\u00C7engel noktas\u0131 ekle/d",
anchor_name:"\u00C7engel noktas\u0131",
code_title:"HTML Kaynak Edit\u00F6",
code_wordwrap:"S\u00F6zc\u00FCk ka",
colorpicker_title:"Bir renk se",
colorpicker_picker_tab:"Se\u00E7i",
colorpicker_picker_title:"Renk se\u00E7i",
colorpicker_palette_tab:"Palet",
colorpicker_palette_title:"Palet renkleri",
colorpicker_named_tab:"\u0130sim",
colorpicker_named_title:"\u0130simli renkl",
colorpicker_color:"Renk:",
colorpicker_name:"\u0130si",
charmap_title:"\u00D6zel karakter s",
image_title:"Resim ekle/d\u00FCzen",
image_src:"Resim URL",
image_alt:"Resim tan\u0131",
image_list:"Resim listesi",
image_border:"Kenarl ",
image_dimensions:"Boyutlar",
image_vspace:"Dikey bo\u015Fl",
image_hspace:"Yatay bo\u015Fl",
image_align:"Hizalama",
image_align_baseline:"Taban \u00E7izgi",
image_align_top:"\u00DC",
image_align_middle:"Orta",
image_align_bottom:"Alt",
image_align_texttop:"Metin \u00FCst",
image_align_textbottom:"Metin altta",
image_align_left:"Sola",
image_align_right:"Sae",
link_title:"Ba\u011Flant\u0131 ekle/d",
link_url:"Ba\u011Flant\u0131",
link_target:"Hedef",
link_target_same:"Ba\u011Flant\u0131y\u0131 ayn\u0131 penc",
link_target_blank:"Ba\u011Flant\u0131y\u0131 yeni pencer",
link_titlefield:"Ba\u015F",
link_is_email:"Girdi\u011Finiz URL bir e-posta adresi gibi g\u00F6z\u00FCk\u00FCyor, gerekli olan mailto: \u00F6nekinin eklenmesini iste",
link_is_external:"Girdi\u011Finiz URL d\u0131\u015F bir ba\u011Flant\u0131 gibi g\u00F6z\u00FCk\u00FCyor, gerekli olan http:// \u00F6nekinin eklenmes",
link_list:"Ba\u011Flant\u0131 lis"
});