tinyMCE.addI18n('ca.fullpage_dlg',{
title:"Propietats del document",
meta_tab:"General",
appearance_tab:"Aparen\u00E7a",
advanced_tab:"Avan\u00E7at",
meta_props:"Metainformaci\u00F3",
langprops:"Idioma i codificaci\u00F3",
meta_title:"T\u00EDtol",
meta_keywords:"Paraules clau",
meta_description:"Descripci\u00F3",
meta_robots:"Robots",
doctypes:"Doctype",
langcode:"Codi d\'idioma",
langdir:"Direcci\u00F3 de l\'idioma",
ltr:"D\'esquerra a dreta",
rtl:"De dreta a esquerra",
xml_pi:"Declaraci\u00F3 XML",
encoding:"Codificaci\u00F3 dels car\u00E0cters",
appearance_bgprops:"Propietats del fons",
appearance_marginprops:"Marges del cos",
appearance_linkprops:"Colors d\'enlla\u00E7",
appearance_textprops:"Propietats del text",
bgcolor:"Color del fons",
bgimage:"Imatge del fons",
left_margin:"Marge esquerre",
right_margin:"Marge dret",
top_margin:"Marge superior",
bottom_margin:"Marge inferior",
text_color:"Color del text",
font_size:"Mida de la font",
font_face:"Font",
link_color:"Color d\'enlla\u00E7",
hover_color:"Color quan es passi per sobre",
visited_color:"Color quan ja \u00E9s visitat",
active_color:"Color quan \u00E9s actiu",
textcolor:"Color",
fontsize:"Mida de la font",
fontface:"Fam\u00EDlia de la font",
meta_index_follow:"Indexa i segueix els enlla\u00E7os",
meta_index_nofollow:"Indexa i no segueixis els enlla\u00E7os",
meta_noindex_follow:"No indexis per\u00F2 segueix els enlla\u00E7os",
meta_noindex_nofollow:"No indexis i no segueixis els enlla\u00E7os",
appearance_style:"Full d\'estils i propietats dels estils",
stylesheet:"Full d\'estils",
style:"Estil",
author:"Autor",
copyright:"Copyright",
add:"Afegeix un nou element",
remove:"Elimina l\'element seleccionat",
moveup:"Mou amunt l\'element seleccionat",
movedown:"Mou avall l\'element seleccionat",
head_elements:"Elements d\'encap\u00E7alament",
info:"Informaci\u00F3",
add_title:"Element t\u00EDtol",
add_meta:"Element meta",
add_script:"Element script",
add_style:"Element estil",
add_link:"Element enlla\u00E7",
add_base:"Element base",
add_comment:"Node comentari",
title_element:"Element t\u00EDtol",
script_element:"Element script",
style_element:"Element estil",
base_element:"Element base",
link_element:"Element enlla\u00E7",
meta_element:"Element meta",
comment_element:"Comentari",
src:"Src",
language:"Idioma",
href:"Href",
target:"Dest\u00ED",
type:"Type",
charset:"Charset",
defer:"Defer",
media:"Media",
properties:"Propietats",
name:"Nom",
value:"Valor",
content:"Contingut",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"General",
advanced_props:"Avan\u00E7at"
});