tinyMCE.addI18n('et.fullpage_dlg',{
title:"Dokumendi omadused",
meta_tab:"\u00DCldine",
appearance_tab:"V\u00E4limus",
advanced_tab:"P\u00F5hjalikum",
meta_props:"\u201EMeta\u201C informatioon",
langprops:"Keel ja kodeering",
meta_title:"Pealkiri",
meta_keywords:"M\u00E4rks\u00F5nad",
meta_description:"Kirjeldus",
meta_robots:"Robotid",
doctypes:"Dokumendi t\u00FC\u00FCp",
langcode:"Keele kood",
langdir:"Keele suund",
ltr:"Vasakult paremale",
rtl:"Paremalt vasakule",
xml_pi:"XML avaldus",
encoding:"Karakteri kodeering",
appearance_bgprops:"Tausta seadistus",
appearance_marginprops:"Sisu piir",
appearance_linkprops:"Lingi v\u00E4rv",
appearance_textprops:"Teksti seaded",
bgcolor:"Tausta v\u00E4rv",
bgimage:"Tausta pilt",
left_margin:"Vasak piir",
right_margin:"Parem piir",
top_margin:"\u00DClemine piir",
bottom_margin:"Alumine piir",
text_color:"Teksti v\u00E4rv",
font_size:"Fondi suurus",
font_face:"Fondi n\u00E4gu",
link_color:"Lingi v\u00E4rv",
hover_color:"\u00DCle-v\u00E4rv",
visited_color:"K\u00FClastatud-v\u00E4rv",
active_color:"Aktiivne-v\u00E4rv",
textcolor:"V\u00F6rv",
fontsize:"Fondi suurus",
fontface:"Font",
meta_index_follow:"M\u00E4rgi ja j\u00E4rgi linki",
meta_index_nofollow:"M\u00E4rgi ja \u00E4ra j\u00E4rgi linki",
meta_noindex_follow:"\u00C4ra m\u00E4rgi linki, aga j\u00E4rgi linki",
meta_noindex_nofollow:"\u00C4ra m\u00E4rgi linki ja \u00E4ra j\u00E4rgi linki",
appearance_style:"Stiilileht ja stiili seaded",
stylesheet:"Stiilileht",
style:"Stiil",
author:"Autor",
copyright:"Autorikaitse",
add:"Lisa uus element",
remove:"Eemalda valitud element",
moveup:"Liiguta valitud element \u00FClesse",
movedown:"Liiguta valitud element alla",
head_elements:"P\u00F5hielemendid",
info:"Informatioon",
add_title:"Pealkirja element",
add_meta:"\u201EMeta\u201C element",
add_script:"Skript\u2019i element",
add_style:"Stiili element",
add_link:"Lingi element",
add_base:"Baaselement",
add_comment:"Kommentaar",
title_element:"Pealkirja element",
script_element:"Skript\u2019i element",
style_element:"Stiili element",
base_element:"Baaselement",
link_element:"Lingi element",
meta_element:"\u201EMeta\u201C element",
comment_element:"kommentaar",
src:"Src",
language:"Keel",
href:"Href",
target:"Sihtm\u00E4rk",
type:"T\u00FC\u00FCp",
charset:"Charset",
defer:"Edasi l\u00FCkkamine",
media:"Meedia",
properties:"Seaded",
name:"Nimi",
value:"V\u00E4\u00E4rtus",
content:"Sisu",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"\u00DCldine",
advanced_props:"T\u00E4psustatud"
});