tinyMCE.addI18n('fi.fullpage_dlg',{
title:"Tiedoston asetukset",
meta_tab:"Yleinen",
appearance_tab:"Ulkoasu",
advanced_tab:"Edistynyt",
meta_props:"Meta tiedot",
langprops:"Kieli ja koodaus",
meta_title:"Otsikko",
meta_keywords:"Avainsanat",
meta_description:"Kuvaus",
meta_robots:"Robotit",
doctypes:"Dokumenttityypit",
langcode:"Kielen koodi",
langdir:"Kielen suunta",
ltr:"Vasemmalta oikealle",
rtl:"Oikealta vasemmalle",
xml_pi:"XML Ilmoitus",
encoding:"Tekstin koodaus",
appearance_bgprops:"Taustan asetukset",
appearance_marginprops:"Body marginaalit",
appearance_linkprops:"Linkkien v\u00E4rit",
appearance_textprops:"Tekstin asetukset",
bgcolor:"Taustan v\u00E4ri",
bgimage:"Taustakuva",
left_margin:"Vasen marginaali",
right_margin:"Oikea marginaali",
top_margin:"Yl\u00E4marginaali",
bottom_margin:"Alamarginaali",
text_color:"Tekstin v\u00E4ri",
font_size:"Fonttikoko",
font_face:"Fontti",
link_color:"Linkin v\u00E4ri",
hover_color:"Hover v\u00E4ri",
visited_color:"Vierailtu v\u00E4ri",
active_color:"Aktiivinen v\u00E4ri",
textcolor:"V\u00E4ri",
fontsize:"Fonttikoko",
fontface:"Fontti",
meta_index_follow:"Indeksoi ja seuraa linkkej\u00E4",
meta_index_nofollow:"Indeksoi, mutta \u00E4l\u00E4 seuraa linkkej\u00E4",
meta_noindex_follow:"\u00C4l\u00E4 indeksoi, mutta seuraa linkkej\u00E4.",
meta_noindex_nofollow:"\u00C4l\u00E4 indeksoi, \u00E4l\u00E4k\u00E4 seuraa linkkej\u00E4",
appearance_style:"Tyylitiedosto ja tyylin asetukset",
stylesheet:"Tyylitiedosto",
style:"Tyyli",
author:"Kirjoittaja",
copyright:"Copyright",
add:"Lis\u00E4\u00E4 uusi elementti",
remove:"Poista valittu elementti",
moveup:"Siirr\u00E4 valittua elementti\u00E4 yl\u00F6s",
movedown:"Siirr\u00E4 valittua elementti\u00E4 alas",
head_elements:"P\u00E4\u00E4elementti",
info:"Informaatio",
add_title:"Otsikkoelementti",
add_meta:"Meta-elementti",
add_script:"Script-elementti",
add_style:"Tyylielementti",
add_link:"Linkkielementti",
add_base:"Base-elementti",
add_comment:"Yleinen elementti",
title_element:"Otsikkoelementti",
script_element:"Script-elementti",
style_element:"Tyylielementti",
base_element:"Base-elementti",
link_element:"Linkkielementti",
meta_element:"Meta-elementti",
comment_element:"Kommentti",
src:"L\u00E4hde",
language:"Kieli",
href:"Href",
target:"Kohde",
type:"Tyyppi",
charset:"Kirjasintyyppi",
defer:"Mukautuminen",
media:"Media",
properties:"Asetukset",
name:"Nimi",
value:"Arvo",
content:"Sis\u00E4lt\u00F6",
rel:"Rel",
rev:"Rev",
hreflang:"Href kieli",
general_props:"Yleinen",
advanced_props:"Edistynyt"
});