tinyMCE.addI18n('hu.fullpage_dlg',{
title:"Dokumentum tulajdons\u00E1gai",
meta_tab:"\u00C1ltal\u00E1nos",
appearance_tab:"Megjelen\u00E9s",
advanced_tab:"Halad\u00F3",
meta_props:"Meta inform\u00E1ci\u00F3",
langprops:"Nyelv \u00E9s k\u00F3dol\u00E1s",
meta_title:"C\u00EDm",
meta_keywords:"Kulcsszavak",
meta_description:"Le\u00EDr\u00E1s",
meta_robots:"Robotok",
doctypes:"Doctype",
langcode:"Nyelvk\u00F3d",
langdir:"\u00CDr\u00E1s ir\u00E1nya",
ltr:"Balr\u00F3l jobra",
rtl:"Jobbr\u00F3l balra",
xml_pi:"XML deklar\u00E1ci\u00F3",
encoding:"Karakterk\u00F3dol\u00E1s",
appearance_bgprops:"H\u00E1tt\u00E9r tulajdons\u00E1gai",
appearance_marginprops:"Test keret",
appearance_linkprops:"Link sz\u00EDnek",
appearance_textprops:"Sz\u00F6veg tulajdons\u00E1gai",
bgcolor:"H\u00E1tt\u00E9rsz\u00EDn",
bgimage:"H\u00E1tt\u00E9rk\u00E9p",
left_margin:"Bal marg\u00F3",
right_margin:"Jobb marg\u00F3",
top_margin:"Fels\u0151 marg\u00F3",
bottom_margin:"Als\u00F3 marg\u00F3",
text_color:"Sz\u00F6vegsz\u00EDn",
font_size:"Bet\u0171m\u00E9ret",
font_face:"Bet\u0171t\u00EDpus",
link_color:"Link sz\u00EDn",
hover_color:"F\u00F6l\u00E9vitt sz\u00EDn",
visited_color:"L\u00E1togatva sz\u00EDn",
active_color:"Akt\u00EDv sz\u00EDn",
textcolor:"Sz\u00EDn",
fontsize:"Bet\u0171m\u00E9ret",
fontface:"Bet\u0171t\u00EDpus",
meta_index_follow:"Indexel \u00E9s k\u00F6veti a linkeket",
meta_index_nofollow:"Indexel, de nem k\u00F6veti a linkeket",
meta_noindex_follow:"Nem indexel, de k\u00F6veti a linkeket",
meta_noindex_nofollow:"Nem indexel \u00E9s nem k\u00F6veti a linkeket",
appearance_style:"Stylesheet \u00E9s style tulajdons\u00E1gok",
stylesheet:"Stylesheet",
style:"Style",
author:"Szerz\u0151",
copyright:"Copyright",
add:"\u00DAj elem hozz\u00E1ad\u00E1sa",
remove:"Kijel\u00F6lt elem t\u00F6rl\u00E9se",
moveup:"Kijel\u00F6lt elem felfel\u00E9 mozgat\u00E1sa",
movedown:"Kijel\u00F6lt elem lefel\u00E9 mozgat\u00E1sa",
head_elements:"Fej elemek",
info:"Inform\u00E1ci\u00F3",
add_title:"C\u00EDm elem",
add_meta:"Meta elem",
add_script:"Script elem",
add_style:"Style elem",
add_link:"Link elem",
add_base:"Base elem",
add_comment:"Comment elem",
title_element:"Title elem",
script_element:"Script elem",
style_element:"Style elem",
base_element:"Base elem",
link_element:"Link elem",
meta_element:"Meta elem",
comment_element:"Megjegyz\u00E9s",
src:"Src",
language:"Language",
href:"Href",
target:"Target",
type:"Type",
charset:"Charset",
defer:"Defer",
media:"Media",
properties:"Properties",
name:"Name",
value:"Value",
content:"Content",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"\u00C1ltal\u00E1nos",
advanced_props:"Halad\u00F3"
});