tinyMCE.addI18n('pl.fullpage_dlg',{
title:"W\u0142a\u015Bciwo\u015Bci dokumentu",
meta_tab:"Og\u00F3lne",
appearance_tab:"Wygl\u0105d",
advanced_tab:"Zaawansowane",
meta_props:"Meta informacje",
langprops:"J\u0119zyk i kodowanie",
meta_title:"Tytu\u0142",
meta_keywords:"S\u0142owa kluczowe",
meta_description:"Opis",
meta_robots:"Robots",
doctypes:"Typ dokumentu",
langcode:"Oznaczenie kodowe j\u0119zyka",
langdir:"Kierunek czytania tekstu",
ltr:"Kierunek z lewej do prawej",
rtl:"Kierunek z prawej do lewej",
xml_pi:"XML deklaracja",
encoding:"Kodowanie znak\u00F3w",
appearance_bgprops:"W\u0142a\u015Bciwo\u015Bci t\u0142a",
appearance_marginprops:"Marginesy strony",
appearance_linkprops:"Kolor odno\u015Bnik\u00F3w",
appearance_textprops:"W\u0142a\u015Bciwo\u015Bci tekstu",
bgcolor:"Kolor t\u0142a",
bgimage:"Obrazek t\u0142a",
left_margin:"Lewy margines",
right_margin:"Prawy margines",
top_margin:"G\u00F3rny margines",
bottom_margin:"Dolny margines",
text_color:"Kolor tekstu",
font_size:"Rozmiar czcionki",
font_face:"Czcionka",
link_color:"Kolor odno\u015Bnika",
hover_color:"Kolor po najechaniu myszk\u0105",
visited_color:"Kolor odwiedzonych link\u00F3w",
active_color:"Kolor aktywnych link\u00F3w",
textcolor:"Kolor",
fontsize:"Rozmiar czcionki",
fontface:"Rodzaj czcionki",
meta_index_follow:"Indeksuj i pod\u0105\u017Caj za linkami",
meta_index_nofollow:"Indeksuj i nie pod\u0105\u017Caj za odno\u015Bnikami",
meta_noindex_follow:"Nie indeksuj i pod\u0105\u017Caj za odno\u015Bnikami",
meta_noindex_nofollow:"Nie indeksuj i nie pod\u0105\u017Caj za odno\u015Bnikami",
appearance_style:"Arkusze i w\u0142a\u015Bciwo\u015Bci styl\u00F3w",
stylesheet:"Arkusz styl\u00F3w",
style:"Styl",
author:"Autor",
copyright:"Prawa autorskie",
add:"Dodaj nowy element",
remove:"Usu\u0144 wybrany element",
moveup:"Przesu\u0144 wybrane element do g\u00F3ry",
movedown:"Przesu\u0144 wybrane element w d\u00F3\u0142",
head_elements:"Elementy nag\u0142\u00F3wka",
info:"Informacja",
add_title:"Tytu\u0142",
add_meta:"Meta tag",
add_script:"Skrypt",
add_style:"Styl",
add_link:"Odno\u015Bnik",
add_base:"Baza",
add_comment:"Komentarz",
title_element:"Tytu\u0142",
script_element:"Skrypt",
style_element:"Styl",
base_element:"Baza",
link_element:"Odno\u015Bnik",
meta_element:"Meta tag",
comment_element:"Komentarz",
src:"\u0179r\u00F3d\u0142o",
language:"J\u0119zyk",
href:"Odno\u015Bnik",
target:"Cel",
type:"Typ",
charset:"Kodowanie",
defer:"Defer",
media:"Media",
properties:"W\u0142a\u015Bciwo\u015Bci",
name:"Nazwa",
value:"Warto\u015B\u0107",
content:"Zawarto\u015B\u0107",
rel:"Rel",
rev:"Rev",
hreflang:"J\u0119zyk odno\u015Bnika",
general_props:"G\u0142\u00F3wne",
advanced_props:"Zaawansowane"
});