tinyMCE.addI18n('sr.fullpage_dlg',{
title:"Svojstva dokumenta",
meta_tab:"Osnovno",
appearance_tab:"Izgled",
advanced_tab:"Napredno",
meta_props:"Meta informacije",
langprops:"Jezik i kodiranje",
meta_title:"Naslov",
meta_keywords:"Klju\u010Dne re\u010Di",
meta_description:"Opis",
meta_robots:"Robots",
doctypes:"Doctype",
langcode:"Kod jezika",
langdir:"Smjer jezika",
ltr:"S leva na desno",
rtl:"S desna na levo",
xml_pi:"XML deklaracija",
encoding:"Kodiranje znakova",
appearance_bgprops:"Svojstva pozadine",
appearance_marginprops:"Margina",
appearance_linkprops:"Boja linka",
appearance_textprops:"Svojstva teksta",
bgcolor:"Boja pozadine",
bgimage:"Pozadinska slika",
left_margin:"Leva margina",
right_margin:"Desna margina",
top_margin:"Gornja margina",
bottom_margin:"Donja margina",
text_color:"Boja teksta",
font_size:"Veli\u010Dina pisma",
font_face:"Pismo",
link_color:"Boja linka",
hover_color:"Boja linka ispod mi\u0161a",
visited_color:"Boja posje\u0107enog linka",
active_color:"Boja aktivnog linka",
textcolor:"Boja",
fontsize:"Veli\u010Dina pisma",
fontface:"Skupina pisama",
meta_index_follow:"Indeksiraj i sledi linkove",
meta_index_nofollow:"Indeksiraj i ne sledi linkove",
meta_noindex_follow:"Ne indeksiraj i sledi linkove",
meta_noindex_nofollow:"Ne indeksiraj i ne sledi linkove",
appearance_style:"CSS i svojstva stila",
stylesheet:"CSS",
style:"Stil",
author:"Autor",
copyright:"Autorska prava",
add:"Dodaj novi element",
remove:"Ukloni odabrani element",
moveup:"Pomakni odabrani element prema gore",
movedown:"Pomakni odabrani element prema dolje",
head_elements:"Zaglavni elementi",
info:"Informacije",
add_title:"Naslovni element",
add_meta:"Meta element",
add_script:"Skriptni element",
add_style:"Sitlski element",
add_link:"Element linka",
add_base:"Osnovni element",
add_comment:"Komentar",
title_element:"Naslovni element",
script_element:"Skriptni element",
style_element:"Stilski element",
base_element:"Osnovni element",
link_element:"Element linka",
meta_element:"Meta element",
comment_element:"Komentar",
src:"Src",
language:"Jezik",
href:"Href",
target:"Meta",
type:"Type",
charset:"Charset",
defer:"Defer",
media:"Media",
properties:"Svojstva",
name:"Ime",
value:"Vrednost",
content:"Sadr\u017Eaj",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Osnovno",
advanced_props:"Napredno"
});