tinyMCE.addI18n('tr.fullpage_dlg',{
title:"Belge \u00F6zellikle",
meta_tab:"Genel",
appearance_tab:"G\u00F6r",
advanced_tab:"Geli\u015Fm",
meta_props:"Meta bilgisi",
langprops:"Dil ve kodlama",
meta_title:"Ba\u015F",
meta_keywords:"Anahtar s\u00F6zc\u00FC",
meta_description:"Tanm",
meta_robots:"Robot'lar",
doctypes:"Belge tipi",
langcode:"Dil kodu",
langdir:"Dil y\u00F6neli",
ltr:"Soldan sa",
rtl:"Sa\u011Fdan so",
xml_pi:"XML tan\u0131",
encoding:"Karakter kodlama",
appearance_bgprops:"Arkaplan \u00F6zellikle",
appearance_marginprops:"G\u00F6vde kenar bo\u015Fluk",
appearance_linkprops:"Ba\u011Flant\u0131 renk",
appearance_textprops:"Metin \u00F6zellikle",
bgcolor:"Arkaplan rengi",
bgimage:"Arkaplan resmi",
left_margin:"Sol kenar bo\u015Fl",
right_margin:"Sa\u011F kenar bo\u015F",
top_margin:"\u00DCst kenar bo\u015F",
bottom_margin:"Alt kenar bo\u015Fl",
text_color:"Metin rengi",
font_size:"Yaz\u0131 boyu",
font_face:"Yaz\u0131 ti",
link_color:"Ba\u011Flant\u0131 r",
hover_color:"\u00DCzerinde ren",
visited_color:"Ziyaret edilmi",
active_color:"Aktif rengi",
textcolor:"Renk",
fontsize:"Yaz\u0131 boyu",
fontface:"Yaz\u0131 ti",
meta_index_follow:"\u0130ndeksle ve ba\u011Flant\u0131la",
meta_index_nofollow:"\u0130ndeksle ve ba\u011Flant\u0131lare",
meta_noindex_follow:"\u0130ndeksleme ama ba\u011Flant\u0131la",
meta_noindex_nofollow:"\u0130ndeksleme ve ba\u011Flant\u0131lar",
appearance_style:"Stil yapra\u011F\u0131 ve stil \u00F6zell",
stylesheet:"Stil yapra ",
style:"Stil",
author:"Yazar",
copyright:"Telif",
add:"Yeni eleman ekle",
remove:"Se\u00E7ili eleman\u0131 ka",
moveup:"Se\u00E7ili eleman\u0131 \u00FC",
movedown:"Se\u00E7ili eleman\u0131 alt",
head_elements:"Ba\u015Fl\u0131k eleman",
info:"Bilgi",
add_title:"Ba\u015Fl\u0131k ele",
add_meta:"Meta eleman",
add_script:"Script eleman",
add_style:"Stil eleman",
add_link:"Ba\u011Flant\u0131 ele",
add_base:"Taban eleman",
add_comment:"Yorum d\u00FC",
title_element:"Ba\u015Fl\u0131k ele",
script_element:"Script eleman",
style_element:"Stil eleman",
base_element:"Taban eleman",
link_element:"Ba\u011Flant\u0131 ele",
meta_element:"Meta eleman",
comment_element:"Yorum",
src:"Src",
language:"Dil",
href:"Href",
target:"Hedef",
type:"Tip",
charset:"Krk.Seti",
defer:"Ertele",
media:"Medya",
properties:"\u00D6zellikl",
name:"\u0130s",
value:"De\u011F",
content:"\u0130\u00E7",
rel:"Rel",
rev:"Rev",
hreflang:"Href dili",
general_props:"Genel",
advanced_props:"Geli\u015Fm"
});