name: "Update locales sources"

permissions:
  contents: "read"

on:
  # Runs once a week to catch up on translatable strings changed since the last extraction
  schedule:
    - cron: "0 3 * * 1"
  # Enable manual run
  workflow_dispatch:

jobs:
  push-on-transifex:
    if: github.repository == 'glpi-project/glpi'
    name: "Push locales sources (${{ matrix.branch }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - {branch: "11.0/bugfixes", php-version: "8.2"}
          - {branch: "12.0/bugfixes", php-version: "8.3"}
          - {branch: "main", php-version: "8.3"}
    env:
      COMPOSE_FILE: ".github/actions/docker-compose-app.yml"
      APPLICATION_ROOT: "${{ github.workspace }}"
      PHP_IMAGE: "githubactions-php-apache:${{ matrix.php-version }}"
      UPDATE_FILES_ACL: true
    steps:
      - name: "Set env"
        run: |
          echo "APP_CONTAINER_HOME=${{ runner.temp }}/app_home" >> $GITHUB_ENV
      - name: "Checkout"
        uses: "actions/checkout@v7"
        with:
          ref: "${{ matrix.branch }}"
      - name: "Restore dependencies cache"
        uses: "actions/cache@v6"
        with:
          path: |
            ${{ env.APP_CONTAINER_HOME }}/.cache/composer/
            ${{ env.APP_CONTAINER_HOME }}/.npm/_cacache/
          key: "app_home_deps-${{ matrix.php-version }}-${{ hashFiles('composer.lock', 'package-lock.json') }}"
          restore-keys: |
            app_home_deps-${{ matrix.php-version }}-
            app_home_deps-
      - name: "Initialize containers"
        run: |
          .github/actions/init_containers-start.sh
      - name: "Build dependencies / translations"
        run: |
          docker compose exec -T app .github/actions/init_build.sh
      - name: "Extract locales"
        run: |
          docker compose exec -T app bin/console tools:locales:extract
      - name: "Push source file"
        uses: "transifex/cli-action@v2"
        with:
          args: "push"
          token: "${{ secrets.TRANSIFEX_TOKEN }}"
