tinyMCE.addI18n('hr.advimage_dlg',{
tab_general:"Osnovno",
tab_appearance:"Izgled",
tab_advanced:"Napredno",
general:"Osnovno",
title:"Naslov",
preview:"Prikaz",
constrain_proportions:"Zadr\u017Ei proporcije",
langdir:"Smjer jezika",
langcode:"Kod jezika",
long_desc:"Poveznica dugog opisa",
style:"Stil",
classes:"Klase",
ltr:"S lijeva na desno",
rtl:"S desna na lijevo",
id:"Id",
map:"Karta slike",
swap_image:"Izmjenjiva slika",
alt_image:"Alternativna slika",
mouseover:"za prelazak mi\u0161a preko slike",
mouseout:"za izlazak mi\u0161a van slike",
misc:"Razno",
example_img:"Prikaz slike",
missing_alt:"Jeste li sigurni da \u017Eelite izostaviti opis slike? Slika mo\u017Ee biti nedostupna ljudima s pote\u0161ko\u0107ama ili onima koji koriste preglednike bez prikaza slika.",
dialog_title:"Umetni/uredi sliku",
src:"URL slike",
alt:"Opis slike",
list:"Lista slika",
border:"Obrub",
dimensions:"Dimenzije",
vspace:"Okomiti razmak",
hspace:"Vodoravni razmak",
align:"Poravnavanje",
align_baseline:"Osnovna linija",
align_top:"Vrh",
align_middle:"Sredina",
align_bottom:"Dno",
align_texttop:"Vrh teksta",
align_textbottom:"Dno teksta",
align_left:"Lijevo",
align_right:"Desno",
image_list:"Lista slika"
});