tinyMCE.addI18n('ms.advimage_dlg',{
tab_general:"Am",
tab_appearance:"Penglihatan",
tab_advanced:"Lanjutan",
general:"Am",
title:"Tajuk",
preview:"Pratonton",
constrain_proportions:"Kadar tahanan",
langdir:"Arah bahasa",
langcode:"Kod bahasa",
long_desc:"Pautan huraian panjang",
style:"Gaya",
classes:"Kelas-kelas",
ltr:"Kiri ke kanan",
rtl:"Kanan ke kiri",
id:"Id",
map:"Imej map",
swap_image:"Tukar imej",
alt_image:"Imej alternatif",
mouseover:"untuk tetikus di atas",
mouseout:"untuk tetikus di luar",
misc:"Pelbagai",
example_img:"Penglihatan pratonton imej",
missing_alt:"Adakah anda pasti untuk teruskan tanpa masukkan huraian imej? Tanpa huraian, imej mungkin tidak dapat difahami oleh orang yang kurang upaya, orang yang menggunakan pelayaran teks.",
dialog_title:"Sisip/sunting imej",
src:"URL imej",
alt:"Huraian imej",
list:"Senarai imej",
border:"Sempadan",
dimensions:"Dimensi",
vspace:"Ruangan tegak",
hspace:"Ruangan ufuk",
align:"Penyelarian",
align_baseline:"Garis pangkal",
align_top:"Atas",
align_middle:"Tengah",
align_bottom:"Bawah",
align_texttop:"Teks atas",
align_textbottom:"Teks bawah",
align_left:"Kiri",
align_right:"Kanan",
image_list:"Senarai imej"
});