tinyMCE.addI18n('nn.advimage_dlg',{
tab_general:"Generelt",
tab_appearance:"Utsj\u00E5nad",
tab_advanced:"Avansert",
general:"Generelt",
title:"Tittel",
preview:"Sj\u00E5 f\u00F8rebels utkast",
constrain_proportions:"Behald proporsjonar",
langdir:"Skriftretning",
langcode:"Spr\u00E5kkode",
long_desc:"Lang omtale",
style:"Stil",
classes:"Klasser",
ltr:"Venstre mot h\u00F8gre",
rtl:"H\u00F8gre mot venstre",
id:"Id",
map:"Biletekart",
swap_image:"Byt bilete",
alt_image:"Alternativt bilete",
mouseover:"for musepeikar over",
mouseout:"for musepeikar utanfor",
misc:"Anna",
example_img:"Sj\u00E5 f\u00F8rebels utkast av bilete",
missing_alt:"Er du sikker p\u00E5 at du vil fortsetje utan \u00E5 setje inn ei omtale av biletet? Utan omtale vil biletet ikkje gje meining for enkelte funksjonshemma eller for personar som bruker ein nettlesar med biletvisinga avsl\u00E5tt.",
dialog_title:"Set inn / endre bilete",
src:"Bilete-URL",
alt:"Bileteomtale",
list:"Bileteliste",
border:"Ramme",
dimensions:"Dimensjonar",
vspace:"Vertikal avstand",
hspace:"Horisontal avstand",
align:"Justering",
align_baseline:"Basislinje",
align_top:"Topp",
align_middle:"Midtstilt",
align_bottom:"Botn",
align_texttop:"Tekst topp",
align_textbottom:"Tekst botn",
align_left:"Venstre",
align_right:"H\u00F8gre",
image_list:"Liste med bilete"
});