tinyMCE.addI18n('pl.advimage_dlg',{
tab_general:"Og\u00F3lny",
tab_appearance:"Prezentacja",
tab_advanced:"Zaawansowany",
general:"Og\u00F3lny",
title:"Tytu\u0142",
preview:"Podgl\u0105d",
constrain_proportions:"Zachowaj proporcje",
langdir:"Kierunek j\u0119zyka",
langcode:"Kod j\u0119zyka",
long_desc:"D\u0142ugi opis linku",
style:"Styl",
classes:"Klasa",
ltr:"Lewy do prawego",
rtl:"Prawy do lewego",
id:"Id",
map:"Mapa obrazu",
swap_image:"Wymiana obrazka",
alt_image:"alternatywny obrazek",
mouseover:"for mouse over",
mouseout:"for mouse out",
misc:"R\u00F3\u017Cne",
example_img:"Podgl\u0105d wygl\u0105du obrazka",
missing_alt:"Czy jeste\u015B pewien, \u017Ce chcesz kontynuowa\u0107 bez opisu obrazka? Obrazek bez opisu mo\u017Ce nie by\u0107 dost\u0119pny dla u\u017Cytkownik\u00F3w kt\u00F3rzy u\u017Cywaj\u0105 tekstowej przegl\u0105darki, lub przegl\u0105daj\u0105cych stron\u0119 z wy\u0142\u0105czonymi obrazkami.",
dialog_title:"Wklej/edytuj obraz",
src:"URL obrazka",
alt:"Opis obrazka",
list:"Lista obrazk\u00F3w",
border:"Obramowanie",
dimensions:"Rozmiary",
vspace:"Pionowy odstep",
hspace:"Poziomy odstep",
align:"Wyr\u00F3wnanie",
align_baseline:"G\u0142\u00F3wna linia",
align_top:"G\u00F3rny",
align_middle:"\u015Arodkowy",
align_bottom:"Dolny",
align_texttop:"Tekst g\u00F3rny",
align_textbottom:"Tekst dolny",
align_left:"Lewy",
align_right:"Prawy",
image_list:"Lista obrazk\u00F3w"
});