tinyMCE.addI18n('tr.advimage_dlg',{
tab_general:"Genel",
tab_appearance:"G\u00F6r",
tab_advanced:"Geli\u015Fm",
general:"Genel",
title:"Ba\u015F",
preview:"\u00D6nizle",
constrain_proportions:"Orant\u0131y\u0131 ",
langdir:"Dil y\u00F6neli",
langcode:"Dil kodu",
long_desc:"Uzun a\u00E7\u0131klama ba\u011Fl",
style:"Stil",
classes:"S\u0131n\u0131",
ltr:"Soldan sa",
rtl:"Sa\u011Fdan so",
id:"Id",
map:"Resim haritas",
swap_image:"Resmi takas et",
alt_image:"Alternatif resim",
mouseover:"fare \u00FCzerindeyk",
mouseout:"fare d\u0131\u015F\u0131n",
misc:"\u00C7e\u015F",
example_img:"G\u00F6r\u00FCn\u00FCm \u00F6nizle",
missing_alt:"Bir Resim Tan\u0131m\u0131 girmeden devam etmek istedi\u011Finizden emin misiniz? Bu olmadan resim baz\u0131 engelli kullan\u0131c\u0131lar, metin tabanl\u0131 taray\u0131c\u0131lar veya Web'i resimleri kapatarak dola\u015Fanlar ie",
dialog_title:"Resim ekle/d\u00FCzen",
src:"Resim URL",
alt:"Resim tan\u0131",
list:"Resim listesi",
border:"Kenarl ",
dimensions:"Boyutlar",
vspace:"Dikey bo\u015Fl",
hspace:"Yatay bo\u015Fl",
align:"Hizalama",
align_baseline:"Taban \u00E7izgi",
align_top:"\u00DC",
align_middle:"Orta",
align_bottom:"Alt",
align_texttop:"Metin \u00FCst",
align_textbottom:"Metin altta",
align_left:"Sola",
align_right:"Sae",
image_list:"Resim listesi"
});